### ISSUE TITLE
图片宽度超出屏幕

### ISSUE THREAD

**Issue by KingZD** [jin-yufeng/Parser#100]
**问题描述**  
使用本组件进行HTML文本预览时，如果预览图片为
```
<img src="http://n.sinaimg.cn/sinakd202047s/250/w580h470/20200407%2Fa119-iryninw1720139.jpg" style="max-width:700px"/>
```
图片自身宽度大于手机屏幕，且style属性描述的宽度也大于屏幕。则会造成图片超出屏幕

**解决方式**
在这里上面一行加上[this.imgList.setItem(item.attrs.i, item.attrs.src);](https://github.com/jin-yufeng/Parser/blob/4b9a4a4b0dec69ef98a92ba25c4540012f210512/parser.uni/jyf-parser.vue#L407)
```html
item.attrs.style = 'max-width:100%';
```
进行自适应最大宽度

**Comment by jin-yufeng** [comment]
插件本身是有给图片加 `max-width:100%` 的，但是优先级低于 `style` 属性，所以会被覆盖  
需要的话可以在 `config.js` 里的 `userAgentStyles` 里给 `img` 的 `max-width` 加上 `!important`

**Comment by KingZD** [comment]
> 插件本身是有给图片加 `max-width:100%` 的，但是优先级低于 `style` 属性，所以会被覆盖
> 需要的话可以在 `config.js` 里的 `userAgentStyles` 里给 `img` 的 `max-width` 加上 `!important`

感谢，我没有仔细看文档
