### ISSUE TITLE
a标签被一些不常用行标签包裹时整体会被当成块标签

### ISSUE THREAD

**Issue by sockball** [jin-yufeng/Parser#101]
## 问题描述
当a标签被一些不常用行标签包裹时，APP端表现为块标签，单独成一行，如 u、big、small、strong等 

H5正常

苹果未知 测试为安卓

## 预期的表现
点击<strong><a href='https://www.baidu.com'>百度</a></strong>一下

## 实际的表现  
点击
<strong><a href='https://www.baidu.com'>百度</a></strong>
一下

## html代码

`点击<strong><a href='https://www.baidu.com'>百度</a></strong>一下`

## 尝试解决
在config中的 `默认的标签样式` 中给相应的标签加入 `display: inline-block`  即可

不知道为什么 `display: inline`不生效...

另外建议commit更细致一些 不应该一句 `已修复` 就没了

没有告诉大家你在哪个commit中修改了哪些文件 不能很快得看到是如何修复的 比如 #87

**Comment by jin-yufeng** [comment]
是最新版吗？

**Comment by sockball** [comment]
> 是最新版吗？

忘了说了 是`3.20` `2.8.2`版本

试了一下最新版是正常的

因为看到更新日志在这之后没有提到换行的问题就没有更新了😅

**Comment by jin-yufeng** [comment]
哈哈哈好的，以后会标注的详细一点
