### ISSUE TITLE
按教程使用时出现TypeError: Cannot read property '$options' of undefined

### ISSUE THREAD

**Issue by mahaoming** [jin-yufeng/Parser#102]
**问题描述**  
![image](https://user-images.githubusercontent.com/31064550/78863770-f2fdd700-7a6c-11ea-8340-cd3f40961706.png)
![image](https://user-images.githubusercontent.com/31064550/78863351-efb61b80-7a6b-11ea-9a09-afe61764768a.png)
![image](https://user-images.githubusercontent.com/31064550/78863272-c1d0d700-7a6b-11ea-9a9f-5ad51baa4182.png)
![image](https://user-images.githubusercontent.com/31064550/78863290-cc8b6c00-7a6b-11ea-8595-169a383200e0.png)

**Comment by jin-yufeng** [comment]
`uni` 的版本？

**Comment by mahaoming** [comment]
是的

**Comment by jin-yufeng** [comment]
用的 `uni-app` 编译器的版本是多少？

**Comment by mahaoming** [comment]
![image](https://user-images.githubusercontent.com/31064550/78864722-c8ad1900-7a6e-11ea-86b2-eb00b35d4a78.png)

**Comment by mahaoming** [comment]
![image](https://user-images.githubusercontent.com/31064550/78864722-c8ad1900-7a6e-11ea-86b2-eb00b35d4a78.png)

**Comment by mahaoming** [comment]
"dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-26520200314001",
    "@dcloudio/uni-h5": "^2.0.0-26520200314001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-alipay": "^2.0.0-26520200314001",
    "@dcloudio/uni-mp-baidu": "^2.0.0-26520200314001",
    "@dcloudio/uni-mp-qq": "^2.0.0-26520200314001",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-26520200314001",
    "@dcloudio/uni-mp-weixin": "^2.0.0-26520200314001",
    "@dcloudio/uni-stat": "^2.0.0-26520200314001",
    "flyio": "^0.6.2",
    "js-base64": "^2.5.1",
    "regenerator-runtime": "^0.12.1",
    "sass": "1.24.0",
    "sass-loader": "^7.3.0",
    "vue": "^2.6.11",
    "vuex": "^3.1.3"
  },
  "devDependencies": {
    "@dcloudio/uni-cli-shared": "^2.0.0-26520200314001",
    "@dcloudio/uni-migration": "^2.0.0-26520200314001",
    "@dcloudio/uni-template-compiler": "^2.0.0-26520200314001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-26520200314001",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-26520200314001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-26520200314001",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-26520200314001",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-26520200314001",
    "@types/html5plus": "*",
    "@types/uni-app": "*",
    "@vue/cli-plugin-babel": "3.5.1",
    "@vue/cli-service": "^4.2.3",
    "babel-plugin-import": "^1.11.0",
    "mini-types": "*",
    "miniprogram-api-typings": "^2.10.2",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by jin-yufeng** [comment]
你用我这个项目试一下吧 [demo.zip](https://github.com/jin-yufeng/Parser/files/4454617/demo.zip)，打开后  
```bash
npm install
npm run dev:%PLATFORM%
```
我这里是没有这个问题的

**Comment by mahaoming** [comment]
可以了, 是 `uni-app` 版本的问题, 把版本升到最新就可以了 太感谢啦
