### ISSUE TITLE
uni-app中无法引入腾讯视频插件

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#103]
**问题描述**  
在微信小程序代码中成功拓展腾讯视频，但是在uni-app中引用不到腾讯视频
![image](https://user-images.githubusercontent.com/15627064/78887313-33bc1700-7a92-11ea-8616-834ea7d07d59.png)

uniapp 中mainfest.json文件和pages.json文件对应页面均已引入腾讯视频，但是并没得到预期的效果
疑问：uni-app中都是vue单文件，没有json文件，如何引入腾讯视频插件
![image](https://user-images.githubusercontent.com/15627064/78888207-bdb8af80-7a93-11ea-9c22-97a0973b5506.png)

**预期的表现**  
uni-app和微信小程序同样可拓展腾讯视频插件

**实际的表现**  
uni-app腾讯视频插件不显示（貌似是引入不到腾讯视频插件导致）

**html代码**  
请附上出现问题的html代码（或附件），例如：

config.js
```
// 过滤器函数
	filter(node, cxt) {
		console.log("filter", node);
		// 轻站拓展
    if (node.name == 'iframe'){
      console.log("iframe", node);
      cxt.bubble(); // 使得 不被 rich-text 包含
      // safeGetValue 只是一个取值的函数，可自行编写自己的取值函数。
      node.attrs.vid = safeGetValue([1], node.attrs.src.match(/https:\/\/v\.qq\.com.*vid=(\w*)/)) || "";
    }
    // 此函数作用类似于ramda的path和pathOr，用于安全取值。
    function safeGetValue() {
      const argsLength = arguments.length

      if (argsLength !== 2 && argsLength !== 3) {
        throw '必须为两个或者三个参数'
      }
      var defaultValue
      if (argsLength === 3) {
        var [_defaultValue, keys, item] = arguments
        defaultValue = _defaultValue
      } else {
        var [keys, item] = arguments
      }
      if (!Array.isArray(keys)) {
        throw '参数有误，取值的keys必须为数组'
      }
      try {
        keys.forEach(key => {
          item = item[key]
        })
      } catch (e) {
        return defaultValue
      }
      return item
    };
  },
  ...
ignoreTags: makeMap(
		'area,base,basefont,canvas,command,frame,input,isindex,keygen,link,map,meta,param,script,source,style,svg,textarea,title,track,use,wbr'
		// #ifdef MP-WEIXIN
		+ (canIUse ? ',rp' : '')
		// #endif
	
),

...

// 信任的标签 1
trustTags: makeMap(
		'a,abbr,ad,audio,b,blockquote,br,code,col,colgroup,dd,del,dl,dt,div,em,fieldset,h1,h2,h3,h4,h5,h6,hr,i,img,ins,label,legend,li,ol,p,q,source,span,strong,sub,sup,table,tbody,td,tfoot,th,thead,tr,title,ul,video'
		// #ifdef MP-WEIXIN
		+ (canIUse ? ',bdi,bdo,caption,pre,rt,ruby' : '')
		// #endif
		
		+ ',embed,iframe'
	),
```
tress.vue
`<tx-video v-else-if="n.name=='iframe'" :style="n.attrs.style" :vid="n.attrs.vid" :playerid="n.attrs.vid" width="690rpx" height="390rpx" :class="n.attrs.class">
</tx-video>`

**Comment by jin-yufeng** [comment]
之前有人碰到过，最后好像是在 `trees` 里引入了插件就解决了（我也没问怎么引入的😂）
试试在编译后的 `trees.json` 里加进去

**Comment by macanfa108** [comment]
在编译后的 trees.json 里加进去确实是可以的，但是治标不治本。
另一个种处理方案：
在pages.json文件中，globalStyle下可以设置usingComponents，此用法和json的配置方式相同，故在此引入腾讯视频插件（注意平台编译）

再次感谢作者！

**Comment by Lich3nbo** [comment]
我这边html 是有 `iframe` 得 但他得父元素 是p标签 
在filter里面调用  node.name == iframe 是不起作用得。

**Comment by macanfa108** [comment]
> 我这边html 是有 `iframe` 得 但他得父元素 是p标签
> 在filter里面调用 node.name == iframe 是不起作用得。

应该不管父元素的事，排查下ignoreTags和trustTags是否对iframe做处理？在filter()方法中log下node调试下

**Comment by zhangyq233** [comment]
![image](https://user-images.githubusercontent.com/28673757/86705672-b3815f80-c048-11ea-88b9-d662269afd14.png)
兄弟，按照你上面的代码，出现这种情况，请问又遇到过吗，知道什么原因吗 谢谢

**Comment by macanfa108** [comment]
> ![image](https://user-images.githubusercontent.com/28673757/86705672-b3815f80-c048-11ea-88b9-d662269afd14.png)
> 兄弟，按照你上面的代码，出现这种情况，请问又遇到过吗，知道什么原因吗 谢谢

我记得当时遇到这种问题是通过以下两个步骤处理的：

1、在mainfest.json文件中，mp-weixin平台下添加对应的插件，如：
![image](https://user-images.githubusercontent.com/15627064/86706665-b597ee00-c049-11ea-8aa1-e5805f8aec01.png)

2、在pages.json文件中配置globalStyle.usingComponents，如：
![image](https://user-images.githubusercontent.com/15627064/86706902-f6900280-c049-11ea-83c9-939b0e8727a8.png)


温馨提示：微信官方需要非个体资质的小程序才能使用腾讯视频，所以这点在开发中也需注意，否则可能会面临不符合资质审核打回的问题。

**Comment by zhangyq233** [comment]
> > ![image](https://user-images.githubusercontent.com/28673757/86705672-b3815f80-c048-11ea-88b9-d662269afd14.png)
> > 兄弟，按照你上面的代码，出现这种情况，请问又遇到过吗，知道什么原因吗 谢谢
> 
> 我记得当时遇到这种问题是通过以下两个步骤处理的：
> 
> 1、在mainfest.json文件中，mp-weixin平台下添加对应的插件，如：
> ![image](https://user-images.githubusercontent.com/15627064/86706665-b597ee00-c049-11ea-8aa1-e5805f8aec01.png)
> 
> 2、在pages.json文件中配置globalStyle.usingComponents，如：
> ![image](https://user-images.githubusercontent.com/15627064/86706902-f6900280-c049-11ea-83c9-939b0e8727a8.png)
> 
> 温馨提示：微信官方需要非个体资质的小程序才能使用腾讯视频，所以这点在开发中也需注意，否则可能会面临不符合资质审核打回的问题。

那两个位置也有配置，所以自己贴的视频代码才会显示出来，请问可以提供一份已有的demo看下吗，谢谢

**Comment by zhangyq233** [comment]
> > ![image](https://user-images.githubusercontent.com/28673757/86705672-b3815f80-c048-11ea-88b9-d662269afd14.png)
> > 兄弟，按照你上面的代码，出现这种情况，请问又遇到过吗，知道什么原因吗 谢谢
> 
> 我记得当时遇到这种问题是通过以下两个步骤处理的：
> 
> 1、在mainfest.json文件中，mp-weixin平台下添加对应的插件，如：
> ![image](https://user-images.githubusercontent.com/15627064/86706665-b597ee00-c049-11ea-8aa1-e5805f8aec01.png)
> 
> 2、在pages.json文件中配置globalStyle.usingComponents，如：
> ![image](https://user-images.githubusercontent.com/15627064/86706902-f6900280-c049-11ea-83c9-939b0e8727a8.png)
> 
> 温馨提示：微信官方需要非个体资质的小程序才能使用腾讯视频，所以这点在开发中也需注意，否则可能会面临不符合资质审核打回的问题。

谢谢  可以了，原来是要在globalStyle配置 而不是在页面配置，谢谢。

**Comment by songStar0904** [comment]
模拟器没问题，真机报错：
```js
Component is not found in path "plugin://tencentvideo/video"
```
有遇到过这个问题么  咋解决

**Comment by zhangyq233** [comment]
> 模拟器没问题，真机报错：
> 
> ```js
> Component is not found in path "plugin://tencentvideo/video"
> ```
> 
> 有遇到过这个问题么 咋解决

这个是小程序使用的，你要加上编译语句

**Comment by macanfa108** [comment]
> 模拟器没问题，真机报错：
> 
> ```js
> Component is not found in path "plugin://tencentvideo/video"
> ```
> 
> 有遇到过这个问题么 咋解决

按楼上说的，排查下是否没有限制到mp-weixin平台才去编译。或者还未成功引入该插件。
