### ISSUE TITLE
在苹果端微信小程序 video 会卡住

### ISSUE THREAD

**Issue by Mradxz** [jin-yufeng/Parser#105]
**问题描述**  
在苹果端 微信小程序里 video 标签
视频会卡住 （先是黑屏 然后点几下以后 开始播放 几秒后卡住）
https://developers.weixin.qq.com/community/develop/doc/bbe040d1eb325c57412ce7b8acba7c78

**Comment by jin-yufeng** [comment]
这是 `video` 组件本身的问题吧  
你是说要加上 `custom-cache` 么，但是现在的 [video](https://developers.weixin.qq.com/miniprogram/dev/component/video.html) 文档里没有这个属性

**Comment by Mradxz** [comment]
> 这是 `video` 组件本身的问题吧
> 你是说要加上 `custom-cache` 么，但是现在的 [video](https://developers.weixin.qq.com/miniprogram/dev/component/video.html) 文档里没有这个属性

这就尴尬了 我在你的源码里 加上了这个属性以后 卡的问题解决了

**Comment by jin-yufeng** [comment]
这样的么😂我看 [官方](https://developers.weixin.qq.com/community/develop/doc/0006ec7da9cae0298729409b45b800?highLine=custom-cache) 说现在不要用该属性  
可以去发帖问一下
