### ISSUE TITLE
滚动条阻挡滑动

### ISSUE THREAD

**Issue by shy1118999** [jin-yufeng/Parser#107]
**问题描述**  
有的解析出来，某一段会带有滚动条，导致无法继续滚到到下面的位置

**预期的表现**  
文本段没有滚动条

**实际的表现**  
文本段会显示滚动条

**Comment by jin-yufeng** [comment]
提供 `html`

**Comment by shy1118999** [comment]
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>学会写作：自我进阶的高效方法</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
      @page {
        margin-bottom: 5pt;
        margin-top: 5pt;
      }
      .bold {
        font-weight: bold;
      }
      .calibre {
        display: block;
        font-size: 1em;
        line-height: 1.2;
        padding-left: 0;
        padding-right: 0;
        text-align: justify;
        margin: 0 5pt;
      }
      .calibre_ {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 2em 0 0;
      }
      .calibre_1 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 1em 0 0;
      }
      .calibre_2 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 6em 0 0;
      }
      .calibre_3 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 0;
      }
      .calibre_4 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 0;
      }
      .calibre_5 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 1em 0 0 2em;
      }
      .calibre_6 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre_7 {
        display: block;
        margin: 0 0 0 2em;
      }
      .calibre_8 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 4em 0 0;
      }
      .calibre_9 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 2em 0 0;
      }
      .calibre_10 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 3em 0 0;
      }
      .calibre_11 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 1em 0 0;
      }
      .calibre_12 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 5pt 0 0;
      }
      .calibre_13 {
        height: 155px;
        vertical-align: baseline;
        width: 154px;
      }
      .calibre_14 {
        display: block;
        text-indent: -14pt;
        margin: 1em 0 0 14pt;
      }
      .calibre_15 {
        display: block;
        text-indent: -14pt;
        margin: 0 0 0 14pt;
      }
      .calibre_16 {
        display: block;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre1 {
        font-size: 1.5em;
        line-height: 1.2;
      }
      .calibre2 {
        font-size: 1.25em;
        line-height: 1.2;
      }
      .mbp_pagebreak {
        display: block;
        margin: 0;
      }
    </style>
  </head>
  <body class="calibre">
    <p id="filepos30899" class="calibre_8">
      <a href="index_split_002.html#filepos2906"
        ><span class="calibre1"
          ><span class="bold">第一章 写作认知：重新理解写作</span></span
        ></a
      >
    </p>
    <p id="filepos31044" class="calibre_10">
      <a href="index_split_002.html#filepos3183"
        ><span class="calibre2"
          ><span class="bold">第1节 如何迈出写作的第一步</span></span
        ></a
      >
    </p>
    <p class="calibre_11">
      我的社群里有很多人想学习写作，新手普遍会问一个问题：粥老师，我特别想尝试写作，我该如何迈出第一步？
    </p>
    <p class="calibre_3">答案永远只有一个。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">
      重要的事情说三遍，这是最正确的一个答案，但我知道有人听了这个答案还是无法开始写作，针对这一情况，我调研了很多一直想写作又一直没开始写作的朋友，终于挖出了这个问题背后的症结，接下来我给大家一一破解。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">暂时接受你写得差这个事实</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">很多人不敢开始写作的理由竟然是觉得自己写得差。</p>
    <p class="calibre_3">
      合理的思路不应该是这样的吗：我现在写得差，所以要赶紧开始写，开始练。你现在写得差，就现在开始练，一年后，不就不差了吗？你现在写得差，但你又不开始练，一年之后，你不还是一样差吗？所以，你还有什么理由继续拖延，不赶紧开始写呢？
    </p>
    <p class="calibre_3">
      开始写作的第一步就是从心底接受你暂时写得差这个事实，然后尽早开始练习，这样才能尽快改变“写得差”这个现实。
    </p>
    <p class="calibre_3">
      社群里有人提问：“粥老师，我有一个很大的疑问，为什么你们能随随便便写出几千字，而我写几百字都很困难？”
    </p>
    <p class="calibre_3">
      我回答道：“如果有人说自己一开始就能随随便便写几千字，那绝对是吹牛。我高强度地写了3年，现在写五六千字的文章也得打磨半天。我清楚地记得，2015年我做小编时，第一篇发在公众号头条的文章差点把我‘逼疯’了，我写了一个多星期，写废了两篇，到第三篇才写成。”
    </p>
    <p class="calibre_3">
      知名作者@和菜头2004年时尝试写剧本，并且和一位编剧朋友打赌，称自己也能写出《老友记》那样的作品。他写了一集后自信满满地发过去，让朋友“跪读”，结果收到的回复是：“你知道你写的是什么吗？你写的就是屎。”
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4">
      <span class="bold">你要知道，别人没时间笑话你</span>
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我有一个朋友在投资机构做投资经理，他说：“这个行业，影响力非常重要。有一个可以快速提升影响力的方法，就是经常在知乎和公众号上发表文章，文章内容不限，可以是研究报告、行业见解等。”
    </p>
    <p class="calibre_3">我说：“你很适合啊，为什么不写呢？”</p>
    <p class="calibre_3">
      他说：“我想了一年了。我早就知道我应该写，就是一直没开始，因为我没有勇气公开表达自己的见解。”
    </p>
    <p class="calibre_3">
      我另一个朋友某天终于开通了自己的公众号，但她写了第一篇文章后就不敢再写了，因为她在后台发现有两个同事关注了她。
    </p>
    <p class="calibre_3">
      很多想写作又不敢写作的朋友都会有这样的顾虑：“哎呀，我写得又不好，发出来别人会怎么看？同事、朋友会不会笑话我？他们会不会觉得我的表达很幼稚？”
    </p>
    <p class="calibre_3">这绝对是多虑了。</p>
    <p class="calibre_3">
      首先，你要知道，你没有那么重要。大家都很忙，没时间笑话你。
    </p>
    <p class="calibre_3">
      其次，从心理学角度看，别人看到你写得好时，可能会挑毛病；而别人看到你写得差时，通常会鼓励你。有些人很奇怪，只有当你优秀到会损害他的优越感时，他才会“攻击”你。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">从写好一段话开始你的写作</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我玩滑板5年了，在业余选手里算滑得不错的。之前有不少朋友、同事跟我学滑板，大家学习时心态非常好，先练习站上去、站得稳，再练习慢慢滑行，然后练习转弯等，之后才尝试平地起跳或者U池滑行。
    </p>
    <p class="calibre_3">
      学习不就是这样一个循序渐进的过程吗？为什么一到写作这件事上，很多人就妄想能一下子写出长文章、好文章呢？
    </p>
    <p class="calibre_3">
      所以，迈出写作的第一步不是从写长篇文章开始，而是从写好一段话开始。比如你今天学习了一个概念叫“刻意练习”，让你直接写一篇关于“刻意练习”的干货文章很难，但你可以先尝试写一段话，给别人解释“刻意练习”这个概念。
    </p>
    <p class="calibre_3">
      从写好一两百字的段落开始，每天练习，有一天你会发现，你竟然可以比较轻松地写三四百字了，再继续练习，有一天你就可以毫不费力地写出800字。
    </p>
    <p class="calibre_3">
      想要尽快开始写作，先从降低目标、调低预期开始，要知道，没有人一开始就能写得很好。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">千万不要等你准备好了才写</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      很多人说：“等我把这门课学好了再写”“等我再多读点好文章后再写”“等我准备好了再写”。
    </p>
    <p class="calibre_3">
      可是，你一准备就是一两年，最后还是没开始写作。其实你就是打着准备的旗号，实则是在拖延。
    </p>
    <p class="calibre_3">
      对于写作，不要有完美主义倾向，好文笔是练出来的，好文章是改出来的，从这个角度理解，任何时候，你写的每一篇文章都是在为写好下一篇文章做准备。所以，写作的精进过程，就是你不断发现过去写得很差的过程。不要抱着“我先准备好，再一炮打响”这种念头学写作，要接受过程中的不如意，有句话说得好：先干起来，你就成功了一半。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">坚信一件必然会发生的事情</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      你要坚信，用正确的方法持续训练，你一定会越写越好，这是一件必然会发生的事情。从开始写作的那一天起，我就坚信这件事，从没动摇。
    </p>
    <p class="calibre_3">
      我的助理之前从我的公众号第一篇开始看，觉得每一篇都好，就以为我是天才型的，后来看到我三年前的文章才明白，我也是练出来的。
    </p>
    <p class="calibre_3">
      在这个世界上，天才和智力不足的人各占1%，我们大多数人既不是前者，也不是后者，都是普通人，我们既做不到不写不练就能一鸣惊人，也不会持续训练却没有进步。
    </p>
    <p class="calibre_3">
      我的社群每周都会做一个精华内容星友贡献榜，有一个叫“星里浣”的成员几乎每周都在星友贡献榜的前三名，但其实他并不是一开始就写得好。我特意翻出他刚加入社群时写的文章，发现都很糟，篇幅短、“碎碎念”（碎碎念是从闽南语里音译而来的，表示重复说一些琐碎没有意义的事情）、没营养，但他不管写得好不好，就是“死皮赖脸”地每天写。仅仅用了三个月，他的写作水平就有了很大的进步，第四个月时，他从深圳来到北京，成为我第二个正式员工。
    </p>
    <p class="calibre_3">
      我负责给你正确的方法，你负责持续不断地训练，剩下的交给时间。你要坚信，美好的事情一定会发生。美好的事情不是指你可以比谁厉害，而是你不断地比曾经的自己更厉害，你最大的对手是自己。
    </p>
    <p class="calibre_3">
      迈出写作的第一步，重点不在技术层面，而在心态层面。你要从心底接受自己暂时写得差这个事实；要知道你最大的对手是自己，别人没有时间笑话你；千万不要等准备好了再开始写，先干起来，你就成功了一半；从写好一段话开始你的写作，坚持用正确的方法，持续训练，你一定会越写越好。
    </p>
    <div class="mbp_pagebreak" id="calibre_pb_5"></div>
  </body>
</html>

**Comment by shy1118999** [comment]
`<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>学会写作：自我进阶的高效方法</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
      @page {
        margin-bottom: 5pt;
        margin-top: 5pt;
      }
      .bold {
        font-weight: bold;
      }
      .calibre {
        display: block;
        font-size: 1em;
        line-height: 1.2;
        padding-left: 0;
        padding-right: 0;
        text-align: justify;
        margin: 0 5pt;
      }
      .calibre_ {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 2em 0 0;
      }
      .calibre_1 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 1em 0 0;
      }
      .calibre_2 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 6em 0 0;
      }
      .calibre_3 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 0;
      }
      .calibre_4 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 0;
      }
      .calibre_5 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 1em 0 0 2em;
      }
      .calibre_6 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre_7 {
        display: block;
        margin: 0 0 0 2em;
      }
      .calibre_8 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 4em 0 0;
      }
      .calibre_9 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 2em 0 0;
      }
      .calibre_10 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 3em 0 0;
      }
      .calibre_11 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 1em 0 0;
      }
      .calibre_12 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 5pt 0 0;
      }
      .calibre_13 {
        height: 155px;
        vertical-align: baseline;
        width: 154px;
      }
      .calibre_14 {
        display: block;
        text-indent: -14pt;
        margin: 1em 0 0 14pt;
      }
      .calibre_15 {
        display: block;
        text-indent: -14pt;
        margin: 0 0 0 14pt;
      }
      .calibre_16 {
        display: block;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre1 {
        font-size: 1.5em;
        line-height: 1.2;
      }
      .calibre2 {
        font-size: 1.25em;
        line-height: 1.2;
      }
      .mbp_pagebreak {
        display: block;
        margin: 0;
      }
    </style>
  </head>
  <body class="calibre">
    <p id="filepos30899" class="calibre_8">
      <a href="index_split_002.html#filepos2906"
        ><span class="calibre1"
          ><span class="bold">第一章 写作认知：重新理解写作</span></span
        ></a
      >
    </p>
    <p id="filepos31044" class="calibre_10">
      <a href="index_split_002.html#filepos3183"
        ><span class="calibre2"
          ><span class="bold">第1节 如何迈出写作的第一步</span></span
        ></a
      >
    </p>
    <p class="calibre_11">
      我的社群里有很多人想学习写作，新手普遍会问一个问题：粥老师，我特别想尝试写作，我该如何迈出第一步？
    </p>
    <p class="calibre_3">答案永远只有一个。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">
      重要的事情说三遍，这是最正确的一个答案，但我知道有人听了这个答案还是无法开始写作，针对这一情况，我调研了很多一直想写作又一直没开始写作的朋友，终于挖出了这个问题背后的症结，接下来我给大家一一破解。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">暂时接受你写得差这个事实</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">很多人不敢开始写作的理由竟然是觉得自己写得差。</p>
    <p class="calibre_3">
      合理的思路不应该是这样的吗：我现在写得差，所以要赶紧开始写，开始练。你现在写得差，就现在开始练，一年后，不就不差了吗？你现在写得差，但你又不开始练，一年之后，你不还是一样差吗？所以，你还有什么理由继续拖延，不赶紧开始写呢？
    </p>
    <p class="calibre_3">
      开始写作的第一步就是从心底接受你暂时写得差这个事实，然后尽早开始练习，这样才能尽快改变“写得差”这个现实。
    </p>
    <p class="calibre_3">
      社群里有人提问：“粥老师，我有一个很大的疑问，为什么你们能随随便便写出几千字，而我写几百字都很困难？”
    </p>
    <p class="calibre_3">
      我回答道：“如果有人说自己一开始就能随随便便写几千字，那绝对是吹牛。我高强度地写了3年，现在写五六千字的文章也得打磨半天。我清楚地记得，2015年我做小编时，第一篇发在公众号头条的文章差点把我‘逼疯’了，我写了一个多星期，写废了两篇，到第三篇才写成。”
    </p>
    <p class="calibre_3">
      知名作者@和菜头2004年时尝试写剧本，并且和一位编剧朋友打赌，称自己也能写出《老友记》那样的作品。他写了一集后自信满满地发过去，让朋友“跪读”，结果收到的回复是：“你知道你写的是什么吗？你写的就是屎。”
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4">
      <span class="bold">你要知道，别人没时间笑话你</span>
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我有一个朋友在投资机构做投资经理，他说：“这个行业，影响力非常重要。有一个可以快速提升影响力的方法，就是经常在知乎和公众号上发表文章，文章内容不限，可以是研究报告、行业见解等。”
    </p>
    <p class="calibre_3">我说：“你很适合啊，为什么不写呢？”</p>
    <p class="calibre_3">
      他说：“我想了一年了。我早就知道我应该写，就是一直没开始，因为我没有勇气公开表达自己的见解。”
    </p>
    <p class="calibre_3">
      我另一个朋友某天终于开通了自己的公众号，但她写了第一篇文章后就不敢再写了，因为她在后台发现有两个同事关注了她。
    </p>
    <p class="calibre_3">
      很多想写作又不敢写作的朋友都会有这样的顾虑：“哎呀，我写得又不好，发出来别人会怎么看？同事、朋友会不会笑话我？他们会不会觉得我的表达很幼稚？”
    </p>
    <p class="calibre_3">这绝对是多虑了。</p>
    <p class="calibre_3">
      首先，你要知道，你没有那么重要。大家都很忙，没时间笑话你。
    </p>
    <p class="calibre_3">
      其次，从心理学角度看，别人看到你写得好时，可能会挑毛病；而别人看到你写得差时，通常会鼓励你。有些人很奇怪，只有当你优秀到会损害他的优越感时，他才会“攻击”你。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">从写好一段话开始你的写作</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我玩滑板5年了，在业余选手里算滑得不错的。之前有不少朋友、同事跟我学滑板，大家学习时心态非常好，先练习站上去、站得稳，再练习慢慢滑行，然后练习转弯等，之后才尝试平地起跳或者U池滑行。
    </p>
    <p class="calibre_3">
      学习不就是这样一个循序渐进的过程吗？为什么一到写作这件事上，很多人就妄想能一下子写出长文章、好文章呢？
    </p>
    <p class="calibre_3">
      所以，迈出写作的第一步不是从写长篇文章开始，而是从写好一段话开始。比如你今天学习了一个概念叫“刻意练习”，让你直接写一篇关于“刻意练习”的干货文章很难，但你可以先尝试写一段话，给别人解释“刻意练习”这个概念。
    </p>
    <p class="calibre_3">
      从写好一两百字的段落开始，每天练习，有一天你会发现，你竟然可以比较轻松地写三四百字了，再继续练习，有一天你就可以毫不费力地写出800字。
    </p>
    <p class="calibre_3">
      想要尽快开始写作，先从降低目标、调低预期开始，要知道，没有人一开始就能写得很好。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">千万不要等你准备好了才写</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      很多人说：“等我把这门课学好了再写”“等我再多读点好文章后再写”“等我准备好了再写”。
    </p>
    <p class="calibre_3">
      可是，你一准备就是一两年，最后还是没开始写作。其实你就是打着准备的旗号，实则是在拖延。
    </p>
    <p class="calibre_3">
      对于写作，不要有完美主义倾向，好文笔是练出来的，好文章是改出来的，从这个角度理解，任何时候，你写的每一篇文章都是在为写好下一篇文章做准备。所以，写作的精进过程，就是你不断发现过去写得很差的过程。不要抱着“我先准备好，再一炮打响”这种念头学写作，要接受过程中的不如意，有句话说得好：先干起来，你就成功了一半。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">坚信一件必然会发生的事情</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      你要坚信，用正确的方法持续训练，你一定会越写越好，这是一件必然会发生的事情。从开始写作的那一天起，我就坚信这件事，从没动摇。
    </p>
    <p class="calibre_3">
      我的助理之前从我的公众号第一篇开始看，觉得每一篇都好，就以为我是天才型的，后来看到我三年前的文章才明白，我也是练出来的。
    </p>
    <p class="calibre_3">
      在这个世界上，天才和智力不足的人各占1%，我们大多数人既不是前者，也不是后者，都是普通人，我们既做不到不写不练就能一鸣惊人，也不会持续训练却没有进步。
    </p>
    <p class="calibre_3">
      我的社群每周都会做一个精华内容星友贡献榜，有一个叫“星里浣”的成员几乎每周都在星友贡献榜的前三名，但其实他并不是一开始就写得好。我特意翻出他刚加入社群时写的文章，发现都很糟，篇幅短、“碎碎念”（碎碎念是从闽南语里音译而来的，表示重复说一些琐碎没有意义的事情）、没营养，但他不管写得好不好，就是“死皮赖脸”地每天写。仅仅用了三个月，他的写作水平就有了很大的进步，第四个月时，他从深圳来到北京，成为我第二个正式员工。
    </p>
    <p class="calibre_3">
      我负责给你正确的方法，你负责持续不断地训练，剩下的交给时间。你要坚信，美好的事情一定会发生。美好的事情不是指你可以比谁厉害，而是你不断地比曾经的自己更厉害，你最大的对手是自己。
    </p>
    <p class="calibre_3">
      迈出写作的第一步，重点不在技术层面，而在心态层面。你要从心底接受自己暂时写得差这个事实；要知道你最大的对手是自己，别人没有时间笑话你；千万不要等准备好了再开始写，先干起来，你就成功了一半；从写好一段话开始你的写作，坚持用正确的方法，持续训练，你一定会越写越好。
    </p>
    <div class="mbp_pagebreak" id="calibre_pb_5"></div>
  </body>
</html>
`

**Comment by shy1118999** [comment]
```
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>学会写作：自我进阶的高效方法</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
      @page {
        margin-bottom: 5pt;
        margin-top: 5pt;
      }
      .bold {
        font-weight: bold;
      }
      .calibre {
        display: block;
        font-size: 1em;
        line-height: 1.2;
        padding-left: 0;
        padding-right: 0;
        text-align: justify;
        margin: 0 5pt;
      }
      .calibre_ {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 2em 0 0;
      }
      .calibre_1 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 1em 0 0;
      }
      .calibre_2 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 6em 0 0;
      }
      .calibre_3 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 0;
      }
      .calibre_4 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 0;
      }
      .calibre_5 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 1em 0 0 2em;
      }
      .calibre_6 {
        display: block;
        text-align: justify;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre_7 {
        display: block;
        margin: 0 0 0 2em;
      }
      .calibre_8 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 4em 0 0;
      }
      .calibre_9 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 2em 0 0;
      }
      .calibre_10 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 3em 0 0;
      }
      .calibre_11 {
        display: block;
        text-align: justify;
        text-indent: 2em;
        margin: 1em 0 0;
      }
      .calibre_12 {
        display: block;
        text-align: center;
        text-indent: 0;
        margin: 5pt 0 0;
      }
      .calibre_13 {
        height: 155px;
        vertical-align: baseline;
        width: 154px;
      }
      .calibre_14 {
        display: block;
        text-indent: -14pt;
        margin: 1em 0 0 14pt;
      }
      .calibre_15 {
        display: block;
        text-indent: -14pt;
        margin: 0 0 0 14pt;
      }
      .calibre_16 {
        display: block;
        text-indent: 0;
        margin: 0 0 0 2em;
      }
      .calibre1 {
        font-size: 1.5em;
        line-height: 1.2;
      }
      .calibre2 {
        font-size: 1.25em;
        line-height: 1.2;
      }
      .mbp_pagebreak {
        display: block;
        margin: 0;
      }
    </style>
  </head>
  <body class="calibre">
    <p id="filepos30899" class="calibre_8">
      <a href="index_split_002.html#filepos2906"
        ><span class="calibre1"
          ><span class="bold">第一章 写作认知：重新理解写作</span></span
        ></a
      >
    </p>
    <p id="filepos31044" class="calibre_10">
      <a href="index_split_002.html#filepos3183"
        ><span class="calibre2"
          ><span class="bold">第1节 如何迈出写作的第一步</span></span
        ></a
      >
    </p>
    <p class="calibre_11">
      我的社群里有很多人想学习写作，新手普遍会问一个问题：粥老师，我特别想尝试写作，我该如何迈出第一步？
    </p>
    <p class="calibre_3">答案永远只有一个。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">别废话，直接开始写。</p>
    <p class="calibre_3">
      重要的事情说三遍，这是最正确的一个答案，但我知道有人听了这个答案还是无法开始写作，针对这一情况，我调研了很多一直想写作又一直没开始写作的朋友，终于挖出了这个问题背后的症结，接下来我给大家一一破解。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">暂时接受你写得差这个事实</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">很多人不敢开始写作的理由竟然是觉得自己写得差。</p>
    <p class="calibre_3">
      合理的思路不应该是这样的吗：我现在写得差，所以要赶紧开始写，开始练。你现在写得差，就现在开始练，一年后，不就不差了吗？你现在写得差，但你又不开始练，一年之后，你不还是一样差吗？所以，你还有什么理由继续拖延，不赶紧开始写呢？
    </p>
    <p class="calibre_3">
      开始写作的第一步就是从心底接受你暂时写得差这个事实，然后尽早开始练习，这样才能尽快改变“写得差”这个现实。
    </p>
    <p class="calibre_3">
      社群里有人提问：“粥老师，我有一个很大的疑问，为什么你们能随随便便写出几千字，而我写几百字都很困难？”
    </p>
    <p class="calibre_3">
      我回答道：“如果有人说自己一开始就能随随便便写几千字，那绝对是吹牛。我高强度地写了3年，现在写五六千字的文章也得打磨半天。我清楚地记得，2015年我做小编时，第一篇发在公众号头条的文章差点把我‘逼疯’了，我写了一个多星期，写废了两篇，到第三篇才写成。”
    </p>
    <p class="calibre_3">
      知名作者@和菜头2004年时尝试写剧本，并且和一位编剧朋友打赌，称自己也能写出《老友记》那样的作品。他写了一集后自信满满地发过去，让朋友“跪读”，结果收到的回复是：“你知道你写的是什么吗？你写的就是屎。”
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4">
      <span class="bold">你要知道，别人没时间笑话你</span>
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我有一个朋友在投资机构做投资经理，他说：“这个行业，影响力非常重要。有一个可以快速提升影响力的方法，就是经常在知乎和公众号上发表文章，文章内容不限，可以是研究报告、行业见解等。”
    </p>
    <p class="calibre_3">我说：“你很适合啊，为什么不写呢？”</p>
    <p class="calibre_3">
      他说：“我想了一年了。我早就知道我应该写，就是一直没开始，因为我没有勇气公开表达自己的见解。”
    </p>
    <p class="calibre_3">
      我另一个朋友某天终于开通了自己的公众号，但她写了第一篇文章后就不敢再写了，因为她在后台发现有两个同事关注了她。
    </p>
    <p class="calibre_3">
      很多想写作又不敢写作的朋友都会有这样的顾虑：“哎呀，我写得又不好，发出来别人会怎么看？同事、朋友会不会笑话我？他们会不会觉得我的表达很幼稚？”
    </p>
    <p class="calibre_3">这绝对是多虑了。</p>
    <p class="calibre_3">
      首先，你要知道，你没有那么重要。大家都很忙，没时间笑话你。
    </p>
    <p class="calibre_3">
      其次，从心理学角度看，别人看到你写得好时，可能会挑毛病；而别人看到你写得差时，通常会鼓励你。有些人很奇怪，只有当你优秀到会损害他的优越感时，他才会“攻击”你。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">从写好一段话开始你的写作</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      我玩滑板5年了，在业余选手里算滑得不错的。之前有不少朋友、同事跟我学滑板，大家学习时心态非常好，先练习站上去、站得稳，再练习慢慢滑行，然后练习转弯等，之后才尝试平地起跳或者U池滑行。
    </p>
    <p class="calibre_3">
      学习不就是这样一个循序渐进的过程吗？为什么一到写作这件事上，很多人就妄想能一下子写出长文章、好文章呢？
    </p>
    <p class="calibre_3">
      所以，迈出写作的第一步不是从写长篇文章开始，而是从写好一段话开始。比如你今天学习了一个概念叫“刻意练习”，让你直接写一篇关于“刻意练习”的干货文章很难，但你可以先尝试写一段话，给别人解释“刻意练习”这个概念。
    </p>
    <p class="calibre_3">
      从写好一两百字的段落开始，每天练习，有一天你会发现，你竟然可以比较轻松地写三四百字了，再继续练习，有一天你就可以毫不费力地写出800字。
    </p>
    <p class="calibre_3">
      想要尽快开始写作，先从降低目标、调低预期开始，要知道，没有人一开始就能写得很好。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">千万不要等你准备好了才写</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      很多人说：“等我把这门课学好了再写”“等我再多读点好文章后再写”“等我准备好了再写”。
    </p>
    <p class="calibre_3">
      可是，你一准备就是一两年，最后还是没开始写作。其实你就是打着准备的旗号，实则是在拖延。
    </p>
    <p class="calibre_3">
      对于写作，不要有完美主义倾向，好文笔是练出来的，好文章是改出来的，从这个角度理解，任何时候，你写的每一篇文章都是在为写好下一篇文章做准备。所以，写作的精进过程，就是你不断发现过去写得很差的过程。不要抱着“我先准备好，再一炮打响”这种念头学写作，要接受过程中的不如意，有句话说得好：先干起来，你就成功了一半。
    </p>
    <p class="calibre_3"></p>
    <p class="calibre_4"><span class="bold">坚信一件必然会发生的事情</span></p>
    <p class="calibre_3"></p>
    <p class="calibre_3">
      你要坚信，用正确的方法持续训练，你一定会越写越好，这是一件必然会发生的事情。从开始写作的那一天起，我就坚信这件事，从没动摇。
    </p>
    <p class="calibre_3">
      我的助理之前从我的公众号第一篇开始看，觉得每一篇都好，就以为我是天才型的，后来看到我三年前的文章才明白，我也是练出来的。
    </p>
    <p class="calibre_3">
      在这个世界上，天才和智力不足的人各占1%，我们大多数人既不是前者，也不是后者，都是普通人，我们既做不到不写不练就能一鸣惊人，也不会持续训练却没有进步。
    </p>
    <p class="calibre_3">
      我的社群每周都会做一个精华内容星友贡献榜，有一个叫“星里浣”的成员几乎每周都在星友贡献榜的前三名，但其实他并不是一开始就写得好。我特意翻出他刚加入社群时写的文章，发现都很糟，篇幅短、“碎碎念”（碎碎念是从闽南语里音译而来的，表示重复说一些琐碎没有意义的事情）、没营养，但他不管写得好不好，就是“死皮赖脸”地每天写。仅仅用了三个月，他的写作水平就有了很大的进步，第四个月时，他从深圳来到北京，成为我第二个正式员工。
    </p>
    <p class="calibre_3">
      我负责给你正确的方法，你负责持续不断地训练，剩下的交给时间。你要坚信，美好的事情一定会发生。美好的事情不是指你可以比谁厉害，而是你不断地比曾经的自己更厉害，你最大的对手是自己。
    </p>
    <p class="calibre_3">
      迈出写作的第一步，重点不在技术层面，而在心态层面。你要从心底接受自己暂时写得差这个事实；要知道你最大的对手是自己，别人没有时间笑话你；千万不要等准备好了再开始写，先干起来，你就成功了一半；从写好一段话开始你的写作，坚持用正确的方法，持续训练，你一定会越写越好。
    </p>
    <div class="mbp_pagebreak" id="calibre_pb_5"></div>
  </body>
</html>

```

**Comment by shy1118999** [comment]
IOS端 更明显

**Comment by jin-yufeng** [comment]
哪个平台呢？截个图看看

**Comment by MakerGYT** [comment]
table的列数较多时，会撑开组件，产生滚动行，如果采用禁用滚动会将溢出内容截断。
在这种情况下,如何使table内部横向滚动且tr不换行
![image](https://user-images.githubusercontent.com/16568561/79071738-e351ed00-7d0f-11ea-859c-f72b9a5b04d8.png)

**Comment by jin-yufeng** [comment]
@MakerGYT 在 `table` 标签外面包一个 `div`  
```html
<div style="overflow:scroll">
  <table>
  ...
  </table>
</div>
```

**Comment by MakerGYT** [comment]
@jin-yufeng 在不变动原html下，采取这样
```js
      var document = that.selectComponent("#article").document;
      document.getElementsByTagName('table').forEach(tableNode => {
        var div=document.createElement("div");
        div.setStyle("overflow", "scroll");
        div.appendChild(tableNode);
        div._path = tableNode._path;
        tableNode = div;
      });
```
达到了效果，但是可能还需要遍历子节点以适配`_path`属性层次关系
