### ISSUE TITLE
动画 怎么添加动画效果 @keyframes

### ISSUE THREAD

**Issue by WisBingo** [jin-yufeng/Parser#108]
动画效果  style里面的样式精准的匹配到元素上面 @keyframes丢失了

**Comment by jin-yufeng** [comment]
`@keyframes` 是写在哪里的？

**Comment by WisBingo** [comment]
> `@keyframes` 是写在哪里的？

style里面的  方便加微信说吗 liukim66

**Comment by jin-yufeng** [comment]
截图一下你的写法吧

**Comment by WisBingo** [comment]
是这样的 我们这边后台通过富文本编辑 需要在小程序实现一个轮播图 用的css3动画实现的 结果后台过来的数据keyFrames在style里面不生效



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jin-yufeng <notifications@github.com&gt;
发送时间: 2020年4月12日 18:01
收件人: jin-yufeng/Parser <Parser@noreply.github.com&gt;
抄送: WisBingo <1939500370@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jin-yufeng/Parser] 动画 怎么添加动画效果 @keyframes (#108)





 
截图一下你的写法吧

**Comment by jin-yufeng** [comment]
如果 `@keyframes` 是写在 `style` 标签里的话是没法生效的，因为小程序没法动态写入 `css`，匹配 `style` 标签的原理也只是匹配到各个标签的 `style` 属性里  
把 `@keyframes` 写到 `trees.wxss` 里试一下

**Comment by WisBingo** [comment]
写到tree.wxss是可以的 但是轮播图数量是不确定的自己动画效果也会不一样 写在tree.wxss 就是固定了，没那么灵活了，有什么其它办法吗，富文本实现一个轮播图



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jin-yufeng <notifications@github.com&gt;
发送时间: 2020年4月12日 22:49
收件人: jin-yufeng/Parser <Parser@noreply.github.com&gt;
抄送: WisBingo <1939500370@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jin-yufeng/Parser] 动画 怎么添加动画效果 @keyframes (#108)





 
如果 @keyframes 是写在 style 标签里的话是没法生效的，因为小程序没法动态写入 css，匹配 style 标签的原理也只是匹配到各个标签的 style 属性里
 把 @keyframes 写到 trees.wxss 里试一下

**Comment by jin-yufeng** [comment]
我暂时也没什么办法  
因为无法动态写入 `wxss`，而 `@keyframes` 也只有写在 `wxss` 里才能生效  
也许可以试试把 `swiper` 加进去：[添加一个自定义标签](https://jin-yufeng.github.io/Parser/#/instructions?id=%e6%b7%bb%e5%8a%a0%e4%b8%80%e4%b8%aa%e8%87%aa%e5%ae%9a%e4%b9%89%e6%a0%87%e7%ad%be)

**Comment by WisBingo** [comment]
用原生的swipper swipper样式 以及插入多条swipper-item应该会有问题的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jin-yufeng <notifications@github.com&gt;
发送时间: 2020年4月12日 23:03
收件人: jin-yufeng/Parser <Parser@noreply.github.com&gt;
抄送: WisBingo <1939500370@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jin-yufeng/Parser] 动画 怎么添加动画效果 @keyframes (#108)





 
我暂时也没什么办法
 因为无法动态写入 wxss，而 @keyframes 也只有写在 wxss 里才能生效
 也许可以试试把 swiper 加进去：添加一个自定义标签
