### ISSUE TITLE
表格怎么绑定事件啊 获取到点击的哪个控件

### ISSUE THREAD

**Issue by b1003572686** [jin-yufeng/Parser#109]
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div>Hello World!</div>
```

**Comment by b1003572686** [comment]
表格的html
<table class="roomLayout"><tbody><tr><td data-x="1" data-y="1" data-type="" class="gangway" colspan="1" rowspan="7" bindtap="tdTap">走廊</td><td data-x="2" data-y="1" data-type="" class="seat">A1</td><td data-x="3" data-y="1" data-type="" class="seat">A2</td><td data-x="4" data-y="1" data-type="" class="seat">A3</td><td data-x="5" data-y="1" data-type="" class="seat">A4</td><td data-x="6" data-y="1" data-type="" class=""></td><td data-x="7" data-y="1" data-type="" class="seat">A6</td><td data-x="8" data-y="1" data-type="" class="seat">A7</td><td data-x="9" data-y="1" data-type="" class="seat">A8</td><td data-x="10" data-y="1" data-type="" class="window" colspan="1" rowspan="2">窗户</td></tr><tr><td data-x="1" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="2" data-type="" class="gangway" colspan="8" rowspan="1">过道</td><td data-x="3" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="4" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="5" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="6" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="7" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="8" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="9" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="10" data-y="2" data-type="" class="" colspan="" rowspan="" style="display: none;"></td></tr><tr><td data-x="1" data-y="3" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="3" data-type="" class="seat">B1</td><td data-x="3" data-y="3" data-type="" class="seat">B2</td><td data-x="4" data-y="3" data-type="" class="seat">B3</td><td data-x="5" data-y="3" data-type="" class="seat">B4</td><td data-x="6" data-y="3" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td><td data-x="7" data-y="3" data-type="" class="seat">B6</td><td data-x="8" data-y="3" data-type="" class="seat">B7</td><td data-x="9" data-y="3" data-type="" class="seat">B8</td><td data-x="10" data-y="3" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td></tr><tr><td data-x="1" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="4" data-type="" class="gangway" colspan="8" rowspan="1">过道</td><td data-x="3" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="4" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="5" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="6" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="7" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="8" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="9" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="10" data-y="4" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td></tr><tr><td data-x="1" data-y="5" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="5" data-type="" class="seat">C1</td><td data-x="3" data-y="5" data-type="" class="seat">C2</td><td data-x="4" data-y="5" data-type="" class="seat">C3</td><td data-x="5" data-y="5" data-type="" class="seat">C4</td><td data-x="6" data-y="5" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td><td data-x="7" data-y="5" data-type="" class="seat">C6</td><td data-x="8" data-y="5" data-type="" class="seat">C7</td><td data-x="9" data-y="5" data-type="" class="seat">C8</td><td data-x="10" data-y="5" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td></tr><tr><td data-x="1" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="6" data-type="" class="gangway" colspan="8" rowspan="1">过道</td><td data-x="3" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="4" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="5" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="6" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="7" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="8" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="9" data-y="6" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="10" data-y="6" data-type="" class="window" colspan="1" rowspan="2" style="display: table-cell;">窗户</td></tr><tr><td data-x="1" data-y="7" data-type="" class="" colspan="" rowspan="" style="display: none;"></td><td data-x="2" data-y="7" data-type="" class="seat">D1</td><td data-x="3" data-y="7" data-type="" class="seat">D2</td><td data-x="4" data-y="7" data-type="" class="seat">D3</td><td data-x="5" data-y="7" data-type="" class="seat">D4</td><td data-x="6" data-y="7" data-type="" class="" colspan="" rowspan="" style="display: table-cell;"></td><td data-x="7" data-y="7" data-type="" class="seat">D6</td><td data-x="8" data-y="7" data-type="" class="seat">D7</td><td data-x="9" data-y="7" data-type="" class="seat">D8</td><td data-x="10" data-y="7" data-type="" class="" colspan="" rowspan="" style="display: none;"></td></tr></tbody></table>
想要获取到点击的是哪一个,获取到它的id

**Comment by jin-yufeng** [comment]
用了 `colspan` 和 `rowspan` 的表格会直接被 `rich-text` 显示（因为没法模拟），点击哪一个单元格是无法知晓的
