### ISSUE TITLE
项目一旦加上这个插件  打包就报node内存溢出

### ISSUE THREAD

**Issue by T-Macgrady** [jin-yufeng/Parser#11]
![image](https://user-images.githubusercontent.com/38933351/60430561-313dae80-9c30-11e9-9a0b-419ac4469992.png)
即使调整内存大小的使用限制node --max-old-space-size=8192 也不行

**Comment by jin-yufeng** [comment]
这是什么情况下出现的？

**Comment by T-Macgrady** [comment]
按你的步骤  只要在json文件添加这个插件  npm run watch就会报这个 去掉就正常  tree组件循环引用不会导致这内存溢出吧
![image](https://user-images.githubusercontent.com/38933351/60476497-5ec93d00-9cae-11e9-8f68-25dbbeda9262.png)
![image](https://user-images.githubusercontent.com/38933351/60476734-37bf3b00-9caf-11e9-98ea-186db1f04aad.png)

**Comment by jin-yufeng** [comment]
在开发者工具里编译试试？我还真没见过这种情况

**Comment by xcymo** [comment]
是的，我也遇到了这个情况

**Comment by xcymo** [comment]
我的webpack版本比较低，是3.11.0,，内存溢出的错误不知道怎么自己就消失了，但是出现了另一个错误
![0d309aca2f2fcb2aacc039cc93f29d2](https://user-images.githubusercontent.com/26536909/61943127-6342f600-afcd-11e9-9b9f-05a81062d551.png)

**Comment by jin-yufeng** [comment]
我没有用过webpack😂可能得你们再研究研究

**Comment by xcymo** [comment]
我发现差别了，当我引入插件时用/Parser/index就会报我说的那个错误，用../../Parser/index就会报另一个朋友说的错误。现在我是这么处理的，将打包好之后的文件夹里的Parser直接替换掉，试了，可以用，先暂时这么处理吧~ @T-Macgrady
