### ISSUE TITLE
getText()方法有误

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#110]
**问题描述**  
请详细描述遇到的问题（可附图）
问题1：
通过this.$refs.xxx.setContent(); 然后想获取文本内容时方法报错
应该是n.text误写为n.txt了
![企业微信截图_15867511916898](https://user-images.githubusercontent.com/15627064/79104200-ae41ab00-7da0-11ea-957d-25a80e8d4797.png)

**预期的表现**  
正常获取文本

**实际的表现**  
n.txt.replace报错

**html代码**  
请附上出现问题的html代码（或附件），例如：
jyf-parser.vue
```html
if (n.type == 'text') txt += n.txt.replace(/&nbsp;/g, '\u00A0').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
						.replace(/&amp;/g, '&');
```

问题2：
不通过setContent而通过以下方式：getText()方法报错：（可通过别的方式避免）

`<jyf-parser ref="textModule" :html="content.text"></jyf-parser>
let text = this.$refs.textModule.getText();`

报错截图：
![企业微信截图_15867656875138](https://user-images.githubusercontent.com/15627064/79104979-4a1fe680-7da2-11ea-8c48-b692572e7437.png)

**Comment by jin-yufeng** [comment]
第二个问题好像没有复现  
看一下报错的位置？

**Comment by macanfa108** [comment]
我这边是点击按钮想要获取文本内容，发现里面传入的ns是string来的（如图所示），而代码中期望是node数组，所以循环报错了

**Comment by jin-yufeng** [comment]
你那里 `getText` 的声明是不是还是 `getText(ns = this.html || this.nodes)` ?
是的话改成 `getText(ns = this.nodes)` 试试

**Comment by macanfa108** [comment]
是的，改为getText(ns = this.nodes)即可
谢谢

**Comment by jin-yufeng** [comment]
[已修复](https://github.com/jin-yufeng/Parser/commit/ba4ad21715c574406cee83edcbd32079cf4a4273#diff-62f77e779c9fe21e20334df73397fb54R555)
