### ISSUE TITLE
保留空白div作为换行符

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#111]
**新功能描述**  
拜读大概源码后，尝试以下方式：（有更合适的方式可替代）

可新增配置项（如：'lineWrap': Boolean）
有配置lineWrap为true的保留空白div作为换行符，否则过滤空白div（不影响其他场景）

业务处调用方式：
`<jyf-parser ref="textModule" :line-wrap="true"></jyf-parser>`

jyf-parser.vue：
`props: {
// 保留空div为换行符
'lineWrap': Boolean
}`

MpHtmlParser.js：
`constructor(data, options = {}) {
this.lineWrap = options.lineWrap;
}`

`// 自动压缩
		if (node.name == 'div' && !Object.keys(attrs).length) {
			var siblings = this.siblings();
			if (!(node.children || []).length && this.lineWrap) node.name = 'br';
			else if (!(node.children || []).length) siblings.pop();
			else if (node.children.length == 1 && node.children[0].name == 'div')
				siblings[siblings.length - 1] = node.children[0];
		}`

附图：
![企业微信截图_15867631745982](https://user-images.githubusercontent.com/15627064/79106832-d253bb00-7da5-11ea-8819-521ec70fd1cc.png)

![image](https://user-images.githubusercontent.com/15627064/79107354-d03e2c00-7da6-11ea-921f-f1715a6fd745.png)

**应用场景**  
场景：保留空白div作为换行符
之前应用的是wxParse，空白的div也会成为换行符来实现排版效果
但jyf-parser会直接过滤掉空白的div

排版源码：
`
<div>企业价值观
</div><div>
</div><div>
</div><div>企业宗旨
</div><div>
</div><div>
</div><div>企业精神
</div><div>
</div><div>
</div><div>企业管理方针</div>
`

**Comment by jin-yufeng** [comment]
之前没考虑到空 `div` 可以拿来换行，就直接去掉了，这样的话确实是有问题的

**Comment by jin-yufeng** [comment]
目前把自动去除空 `div` 的功能 [去掉了](https://github.com/jin-yufeng/Parser/commit/ba4ad21715c574406cee83edcbd32079cf4a4273#diff-8d079666e56132f8f257eb45c7d01dacL454)（感觉没必要为此加一个属性哈哈哈）
