### ISSUE TITLE
padding解析

### ISSUE THREAD

**Issue by WisBingo** [jin-yufeng/Parser#112]
style里面的padding:10px 20px 解析后会变成padding:10px20px 导致padding失效

**Comment by jin-yufeng** [comment]
最新版吗？

**Comment by WisBingo** [comment]
最新版版本号是多少 这个很好复现的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jin-yufeng <notifications@github.com&gt;
发送时间: 2020年4月13日 18:30
收件人: jin-yufeng/Parser <Parser@noreply.github.com&gt;
抄送: WisBingo <1939500370@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jin-yufeng/Parser] padding解析 (#112)





 
最新版吗？

**Comment by jin-yufeng** [comment]
我试了一下好像没问题（重新下载一下再试试？）  
![1](https://user-images.githubusercontent.com/48236054/79114254-65e0b800-7db5-11ea-8555-613d17f67fae.png)

**Comment by WisBingo** [comment]
> 我试了一下好像没问题（重新下载一下再试试？）
> ![1](https://user-images.githubusercontent.com/48236054/79114254-65e0b800-7db5-11ea-8555-613d17f67fae.png)

试了跟版本没啥关系 padding不能使用小程序的rpx 用px是可以的

**Comment by WisBingo** [comment]
rpx   value = value.replace(/[0-9.\s]*rpx/g, $ => parseFloat($) * screenWidth / 750 + 'px') 转换正则有点儿问题 空格合并了

**Comment by jin-yufeng** [comment]
[已修复](https://github.com/jin-yufeng/Parser/commit/ba4ad21715c574406cee83edcbd32079cf4a4273#diff-56c867f718c450e5fcef15a459253ebbR312)
