### ISSUE TITLE
在app中video不设置poster的情况默认不会取第一帧

### ISSUE THREAD

**Issue by syymo** [jin-yufeng/Parser#115]
在app中video不设置poster的情况默认不会取第一帧，手动加上preload也不会显示第一帧

**Comment by jin-yufeng** [comment]
`video` 组件好像本来就是这样，直接用一个 `video` 会显示第一帧？

**Comment by syymo** [comment]
> `video` 组件好像本来就是这样，直接用一个 `video` 会显示第一帧？

<img width="884" alt="image" src="https://user-images.githubusercontent.com/26571594/79356000-fdd6d100-7f70-11ea-9474-2094c38429ff.png">
<img width="997" alt="image" src="https://user-images.githubusercontent.com/26571594/79356075-17781880-7f71-11ea-903f-4f5ff431736e.png">

**Comment by jin-yufeng** [comment]
这是 `H5` 中 `video` 标签的表现吧  
照理说应该表现为这样，但在各平台都实现一下 `video` 的话会增加很大的复杂度，都是直接使用自带的 `video` 组件的，`app`  上 `uni-app` 的 `video` 的表现就是这样，没有设置 `poster` 就是黑的
