### ISSUE TITLE
图片首次加载问题

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/Parser#116]
**使用平台**
微信小程序原生框架中使用

**问题描述**  
循环渲染wx:for里面的字段，图片首次加载的时候，页面会一闪而过的出现没有排版的情况，然后变成正常的排版模式。

**预期的表现**  
如果页面有setData操作，则会再次乱套，再次恢复。

**实际的表现**  
请告知该怎么渲染呢？

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<block
        wx:for="{{pageData}}" 
        wx:for-item="item"
        wx:key="index">
       <parser-group>
            <parser html="{{item.indexstem}}" />
      </parser-group>
</block>
```

**Comment by jin-yufeng** [comment]
录个屏看看？

**Comment by 45221378** [comment]
[视频.zip](https://github.com/jin-yufeng/Parser/files/4491093/default.zip)

**Comment by jin-yufeng** [comment]
在 `trees.wxss` 里的 `._img` 里加一句 `width: 0;height:0` 试一下

**Comment by 45221378** [comment]
![img](https://user-images.githubusercontent.com/21222276/79537787-924a4c00-80b5-11ea-81fb-65528a981deb.gif)

图片从无到有，页面没有乱套了，但是操作就一闪闪的。
请问是否有优化的办法呢？

**Comment by jin-yufeng** [comment]
这里是怎么写的呢？点查看的时候是不是重新 `setData` 了题目数据导致题目重新渲染了一次  
点查看的时候就增加下面的答案应该就不会这样吧

**Comment by 45221378** [comment]
是的，点击查看，就setData了。
请问增加下面的答案是什么意思呢？因为其实数据全部存在，点击查看的时候，就是setData 对应的index里面的 flag的值在true与false中切换。然后没有用wx:if，我专门用的 display：none跟block控制的显示与隐藏。

**Comment by jin-yufeng** [comment]
可以放一下这块 `wxml` 的写法么

**Comment by 45221378** [comment]
`
 <block
        wx:for="{{pageData}}" 
        wx:for-item="item"
        wx:key="index">
        <parser-group>
          <view hidden="{{pageChecked!=item.question_num}}">
             
            <view wx:if="{{!item.childrenFlag}}">
              <parser html="{{item.indexstem}}" />
              <view wx:for="{{item.question_data.options}}" wx:for-item="it" wx:key="index">
                <parser html="{{it}}"  />
              </view>
              <view class="clearfix" wx:if="{{item.question_data.video!==''}}">
                <view class="video">视频讲解：</view>
                <video class="seeVideo" src="https://v.qq.com/x/page/y0647bdq0hl.html" ></video>
              </view>
              <view class="clearfix">
                <view class="myanswer">我的作答：<text class="error">X</text></view>
              </view>
              <view class="clearfix" >
                <view class="myanswer">答案解析：<text class="see" bindtap="seeAnswer" data-childrenFlag="{{item.childrenFlag}}" data-id="{{item.id}}" >查看</text></view>
                <view class="myanswer-check" style="display:{{itch.myanswerFlag?'block':'none'}}">
                  <block wx:for="{{item.question_data.answers[0]}}" wx:for-item="ans" wx:key="index">
                    <parser html="{{ans}}" />
                  </block>
                  <block wx:for="{{item.question_data.analysis}}" wx:for-item="ana" wx:key="index">
                    <parser html="{{ana}}" />
                  </block>
                </view>
              </view>
              <view class="clearfix changeAns">
                <view class="myanswer">我的反思：</view>
                <textarea class="textarea" bindinput='getTextareaValue' value="{{item.remarks}}" placeholder="最多可录入30个字" placeholder-class="black"></textarea>
                <button class="sub button" bindtap="changeAnswer" data-id="{{item.id}}">提交</button>
              </view>
            </view>
            
            <view wx:if="{{item.childrenFlag}}">
              <parser lazy-load="true" html="{{item.indexstem}}" />
               <block wx:for="{{item.question_data.children}}" wx:for-item="itch" wx:key="index">
                <view>
                  <view class="clearfix">
                    <view class="myanswer">{{itch.index}}.我的作答：<text class="error" wx:if="{{!itch.myanswerTrue}}">X</text><text class="noerror" wx:if="{{itch.myanswerTrue}}">√</text></view>
                  </view>
                  <view class="clearfix" >
                    <view class="myanswer">答案解析：<text class="see" bindtap="seeAnswer" data-childrenflag="{{item.childrenFlag}}" data-id="{{item.id}}" data-iid="{{itch.index}}">查看</text></view>
                    <view class="myanswer-check" style="display:{{itch.myanswerFlag?'block':'none'}}">
                      <view class="clearfix">
                        <view class="myanswer">
                          <view class="errorright">
                            <block wx:for="{{itch.answers[0]}}" wx:for-item="ans" wx:key="index">
                              <parser html="{{ans}}" />
                            </block>
                          </view>
                        </view>
                      </view>
                      <block wx:for="{{itch.analysis}}" wx:for-item="ana" wx:key="index">
                        <parser html="{{ana}}" />
                      </block>
                      
                    </view>
                  </view>
                </view>
              </block>
              
              <view class="clearfix" wx:if="{{item.question_data.video!==''}}">
                <view class="video">视频讲解：</view>
                <video class="seeVideo" src="https://v.qq.com/x/page/y0647bdq0hl.html" ></video>
              </view>
              
              <view class="clearfix changeAns">
                <view class="myanswer">我的反思：</view>
                <textarea class="textarea" bindinput='getTextareaValue' value="{{item.remarks}}" placeholder="最多可录入30个字" placeholder-class="black"></textarea>
                <button class="sub button" bindtap="changeAnswer" data-id="{{item.id}}">提交</button>
              </view>
            </view>
          </view>
        </parser-group>
        
      </block>


`
`

  seeAnswer(e){
    const {id,childrenflag,iid} = e.currentTarget.dataset;
    const {pageData} = this.data;
    if(childrenflag){
      pageData.map(item=>{
        if(item.id===id){
          item.question_data.children.map(itch=>{
            if(itch.index==iid){
              itch.myanswerFlag = !itch.myanswerFlag
            }
          })
        }
      })
    }else{
      pageData.map(item=>{
        if(item.id===id){
          item.myanswerFlag = !item.myanswerFlag;
        }
      })
    }
    this.setData({
      pageData:pageData
    })
  },


`

**Comment by 45221378** [comment]
```
 <block
        wx:for="{{pageData}}" 
        wx:for-item="item"
        wx:key="index">
        <parser-group>
          <view hidden="{{pageChecked!=item.question_num}}">
             <!-- 无小题的情况下 -->
            <view wx:if="{{!item.childrenFlag}}">
              <parser html="{{item.indexstem}}" />
              <view wx:for="{{item.question_data.options}}" wx:for-item="it" wx:key="index">
                <parser html="{{it}}"  />
              </view>
              <view class="clearfix" wx:if="{{item.question_data.video!==''}}">
                <view class="video">视频讲解：</view>
                <video class="seeVideo" src="https://v.qq.com/x/page/y0647bdq0hl.html" ></video>
              </view>
              <view class="clearfix">
                <view class="myanswer">我的作答：<text class="error">X</text></view>
              </view>
              <view class="clearfix" >
                <view class="myanswer">答案解析：<text class="see" bindtap="seeAnswer" data-childrenFlag="{{item.childrenFlag}}" data-id="{{item.id}}" >查看</text></view>
                <view class="myanswer-check" style="display:{{itch.myanswerFlag?'block':'none'}}">
                  <block wx:for="{{item.question_data.answers[0]}}" wx:for-item="ans" wx:key="index">
                    <parser html="{{ans}}" />
                  </block>
                  <block wx:for="{{item.question_data.analysis}}" wx:for-item="ana" wx:key="index">
                    <parser html="{{ana}}" />
                  </block>
                </view>
              </view>
              <view class="clearfix changeAns">
                <view class="myanswer">我的反思：</view>
                <textarea class="textarea" bindinput='getTextareaValue' value="{{item.remarks}}" placeholder="最多可录入30个字" placeholder-class="black"></textarea>
                <button class="sub button" bindtap="changeAnswer" data-id="{{item.id}}">提交</button>
              </view>
            </view>
            <!-- 有小题的情况下 -->
            <view wx:if="{{item.childrenFlag}}">
              <parser lazy-load="true" html="{{item.indexstem}}" />
               <block wx:for="{{item.question_data.children}}" wx:for-item="itch" wx:key="index">
                <view>
                  <view class="clearfix">
                    <view class="myanswer">{{itch.index}}.我的作答：<text class="error" wx:if="{{!itch.myanswerTrue}}">X</text><text class="noerror" wx:if="{{itch.myanswerTrue}}">√</text></view>
                  </view>
                  <view class="clearfix" >
                    <view class="myanswer">答案解析：<text class="see" bindtap="seeAnswer" data-childrenflag="{{item.childrenFlag}}" data-id="{{item.id}}" data-iid="{{itch.index}}">查看</text></view>
                    <view class="myanswer-check" style="display:{{itch.myanswerFlag?'block':'none'}}">
                      <view class="clearfix">
                        <view class="myanswer">
                          <view class="errorright">
                            <block wx:for="{{itch.answers[0]}}" wx:for-item="ans" wx:key="index">
                              <parser html="{{ans}}" />
                            </block>
                          </view>
                        </view>
                      </view>
                      <block wx:for="{{itch.analysis}}" wx:for-item="ana" wx:key="index">
                        <parser html="{{ana}}" />
                      </block>
                      <!-- <image class='login-logo' src='/images/logo.png' ></image> -->
                    </view>
                  </view>
                </view>
              </block>
              
              <view class="clearfix" wx:if="{{item.question_data.video!==''}}">
                <view class="video">视频讲解：</view>
                <video class="seeVideo" src="https://v.qq.com/x/page/y0647bdq0hl.html" ></video>
              </view>
              
              <view class="clearfix changeAns">
                <view class="myanswer">我的反思：</view>
                <textarea class="textarea" bindinput='getTextareaValue' value="{{item.remarks}}" placeholder="最多可录入30个字" placeholder-class="black"></textarea>
                <button class="sub button" bindtap="changeAnswer" data-id="{{item.id}}">提交</button>
              </view>
            </view>
          </view>
        </parser-group>
        
      </block>
```
```
  seeAnswer(e){
    const {id,childrenflag,iid} = e.currentTarget.dataset;
    const {pageData} = this.data;
    if(childrenflag){
      pageData.map(item=>{
        if(item.id===id){
          item.question_data.children.map(itch=>{
            if(itch.index==iid){
              itch.myanswerFlag = !itch.myanswerFlag
            }
          })
        }
      })
    }else{
      pageData.map(item=>{
        if(item.id===id){
          item.myanswerFlag = !item.myanswerFlag;
        }
      })
    }
    this.setData({
      pageData:pageData
    })
  },
```

**Comment by jin-yufeng** [comment]
这样 `setData` 会重设整个页面的数据导致整个页面重新渲染  
试试单独 `setData` 那个 `myanswerFlag`  
```javascript
this.setData({
  [`pageData[${i}]question_data.children[${j}].myanswerFlag`]: !myanswerFlag
})
```

**Comment by 45221378** [comment]
好了，不闪动了。万分感谢。
