### ISSUE TITLE
可以考虑发一个支持 miniprogram 的 npm package 。

### ISSUE THREAD

**Issue by NiLinli** [jin-yufeng/Parser#117]
**新功能描述**  
描述需要的功能或改进建议

**应用场景**  

可以通过 npm + 构建 npm 去引用改插件

**Comment by shiyuanjieyi** [comment]
同样觉得有必要搞一个npm包

**Comment by jin-yufeng** [comment]
微信端的 `npm` 包已经发布啦，使用方法见：[npm 引入](https://jin-yufeng.github.io/Parser/#/instructions?id=npm-%e5%bc%95%e5%85%a5%ef%bc%88%e4%bb%85%e9%99%90%e5%be%ae%e4%bf%a1%ef%bc%89)  
`npm` 地址：[parser-wx](https://www.npmjs.com/package/parser-wx)

**Comment by shiyuanjieyi** [comment]
👍
