### ISSUE TITLE
微信加载出来的image没有lazy-load

### ISSUE THREAD

**Issue by yy178** [jin-yufeng/Parser#118]
在uniapp使用发现支付宝现在是可以解析出image标签并有lazy-load,但在微信端解析出来的image并没有lazy-load属性，而且在微信端的图片是打开页面全部一起加载的。并没有懒加载

**Comment by jin-yufeng** [comment]
`wxml` 面板里确实没有显示 `lazy-load`（我试了直接写一个 `image` 也是没有的）  
![QQ截图20200417180733](https://user-images.githubusercontent.com/48236054/79558170-54115480-80d6-11ea-98dd-a9cde74ed18f.png)
可以看一下 `netWork` 面板，下滑过程中应该有动态的请求（我在示例项目里试了是有的）  
![QQ截图20200417180852](https://user-images.githubusercontent.com/48236054/79558316-83c05c80-80d6-11ea-9821-50c775561f55.png)
