### ISSUE TITLE
document.getElementById 获取的undefined，明确获取document无误

### ISSUE THREAD

**Issue by lsw1990** [jin-yufeng/Parser#119]
**使用平台**
[微信/头条/uni-app]
uni-app
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现
获取有值
**实际的表现**  
请描述实际的表现
无值
**html代码**  
请附上出现问题的html代码（或附件），例如：
```javascript
let document = this.$refs.article.document
document.getElementById("xxx")无所如何都是undefined
```

**Comment by jin-yufeng** [comment]
之前没注意，在 `uni-app` 里用 `document` 补丁包确实还有问题  
试一下这样  
把 `jyf-parser.vue` 里把这句话下移一点（到上面这个 `if else` 下面）  
![QQ截图20200418230040](https://user-images.githubusercontent.com/48236054/79641185-72f01380-81c8-11ea-8615-84c061f7eaba.png)
然后用这个 [document.js](https://github.com/jin-yufeng/Parser/files/4496838/document.zip)

**Comment by lsw1990** [comment]
@jin-yufeng 十分感谢，目前来看是可以正常取值

**Comment by lsw1990** [comment]
@jin-yufeng 还有一个问题，如果我修改里面内容，我最后要整体重新保存到db html时候，我如何获取整段修改过的html呢？

**Comment by jin-yufeng** [comment]
用这个包 [jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4498312/jyf-parser.zip)  
然后 `document.body.innerHTML` 应该就可以了

**Comment by lsw1990** [comment]
@jin-yufeng 貌似不太行
`let id = e.currentTarget.id,
	document = this.$refs.article.document,
	element = document.getElementById(id);
element.innerText = "hello jyf-parser"
console.log(document.body)`
document.body是undefined

**Comment by jin-yufeng** [comment]
整个插件包都替换了吗？  
试试这个示例项目 [Parser.zip](https://github.com/jin-yufeng/Parser/files/4498328/Parser.zip)

**Comment by lsw1990** [comment]
@jin-yufeng 可以了，刚才没有替换你给的整个，只是在我原基础测试的，多谢
