### ISSUE TITLE
关于 view 递归问题

### ISSUE THREAD

**Issue by 132yse** [jin-yufeng/Parser#12]
您好，是这样的，之前在官网论坛发了同样的帖子
是 view 递归问题

当时您回答说，自定义组件支持这种递归
请问可以给一个用例吗？

非常感谢！

**Comment by jin-yufeng** [comment]
这个组件里，Parser/trees就是一个递归定义的组件
这个代码片段提供了一个简单的实例[https://developers.weixin.qq.com/s/C8DJPEmT7j9Y](https://developers.weixin.qq.com/s/C8DJPEmT7j9Y)
