### ISSUE TITLE
更新04-19版本uni-app所出现的问题

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#121]
**使用平台**
uni-app

**问题描述**  
**问题1：**
虽然保留的div，但空div是没有高度的，不能达到预期的空div换行排版。

**预期的表现**  
空div类似br标签，可达到空行排版
之前的做法是多加一个配置项，将空div换成br来实现预期效果
https://github.com/jin-yufeng/Parser/issues/111
![image](https://user-images.githubusercontent.com/15627064/79734741-c9289800-8329-11ea-93f2-97e7c17231de.png)

**实际的表现**  
空div无高度，无法达到空行排版
![image](https://user-images.githubusercontent.com/15627064/79732652-90d38a80-8326-11ea-95ff-df609a0701c0.png)

**问题2：audio渲染问题**
微信小程序上：有渲染；字节小程序：未渲染；
音频链接demo：http://qz.faisys.com/image/default_audio.mp3

**问题3：video点击播放不了**
微信和字节都点击后无反应
视频链接demo：http://21.s80i.faiusr.com/58/101/AFAIABA6GAAg39rc8gUov-DP1gI.mp4

**问题2、问题3截图表现**  
字节小程序audio未渲染；微信和字节video点击不播放；

![image](https://user-images.githubusercontent.com/15627064/79733441-b6ad5f00-8327-11ea-935d-7e3ba8c2383d.png)

**Comment by macanfa108** [comment]
字节不支持audio：
https://microapp.bytedance.com/dev/cn/mini-app/develop/component/introduction/basic-component
看来要写一个uni-app版本audio组件，能让各端通用了

**Comment by jin-yufeng** [comment]
第一个问题  
我试了一下，一个换行是没有问题的  
![微信截图_20200420180609](https://user-images.githubusercontent.com/48236054/79740076-aa2e0400-8331-11ea-9663-9c439c68393b.png)
![微信截图_20200420180619](https://user-images.githubusercontent.com/48236054/79740086-ae5a2180-8331-11ea-913a-cf5e891a37d9.png)
只不过 `<div></div>` 这种多个换行还是相当于一个换行（在浏览器里也是如此），实在不行就在 `config.js` 中的 [filter](https://jin-yufeng.github.io/Parser/#/instructions?id=filter) 里转为 `br` 吧  
```javascript
filter(node) {
	if(node.name == 'div' && !node.children.length)
		node.name = 'br';
}
```

第二个问题  
就是你说的，头条不支持 `audio`，这个我在原生包里写了一个 [audio](https://jin-yufeng.github.io/Parser/#/instructions?id=audio)，本来打算在 `uni-app` 里也写一个的，然而支付宝里既不支持 `audio` 也不支持 `innerAudioContext`，就搁置了，我再考虑考虑  

第三个问题  
用你这个 `demo` 是可以播放的  
![演示](https://user-images.githubusercontent.com/48236054/79742169-021a3a00-8335-11ea-9455-60b40aa15338.gif)

**Comment by jin-yufeng** [comment]
已经有 `uni-app` 里用的 [audio](https://jin-yufeng.github.io/Parser/#/instructions?id=audio) 啦
