### ISSUE TITLE
微信音频真机不能播放，点击无反应

### ISSUE THREAD

**Issue by lsw1990** [jin-yufeng/Parser#123]
**使用平台**
[微信/头条/uni-app]
uni-app

**问题描述**  
请详细描述遇到的问题（可附图）
真机上音频不能播放，点击无反应，在调试器上能点击播放

**预期的表现**  
请描述预期的表现
真机音频能正常播放

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html

```

**Comment by jin-yufeng** [comment]
音频链接呢？

**Comment by lsw1990** [comment]
@jin-yufeng <audio controls="true" author=" " name="第六课1.m4a" src="http://image.gohuinuo.com/9f09dd56-f4a3-4860-b074-ee70b1719f3d"></audio>

**Comment by jin-yufeng** [comment]
有没有触发 `error` 事件？

**Comment by lsw1990** [comment]
@jin-yufeng 没有，模拟器上是能点击播放，到了真机这个点击播放也没反应，微信小程序

**Comment by jin-yufeng** [comment]
我在安卓真机上是可以的，另外你可以直接放在一个 `audio` 标签上试一下

**Comment by lsw1990** [comment]
@jin-yufeng 我是直接放了一个audio就不行，在真机上，我的是ios的，还能是和audio微信不推荐用了有关吗

**Comment by jin-yufeng** [comment]
是不是格式问题，换一个 `mp3` 试试？

**Comment by macanfa108** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/audio.html
ios上官方音频已废弃，无法播放，可改用InnerAudioContext实现播放，但注意ios上可能需要设置obeyMuteSwitch:false（仅在 iOS 生效）是否遵循静音开关，默认遵循静音

另一种情况是：开发工具上正常播放，但到ios真机上触发了error事件，用格式化工厂转码mp3就可以了，可能是媒体文件内部编码问题

**Comment by lsw1990** [comment]
@macanfa108 在富文本解析的什么时机用InnerAudioContext创建呢？

**Comment by macanfa108** [comment]
@lsw1990 建议先试下转码，看看是否是编码问题
你可以试下jin-yufeng提供的组件：parser-master/pathes/audio（目前是微信端版本,可先改写为vue），引入到trees.vue中使用

**Comment by lsw1990** [comment]
@macanfa108 好的，十分感谢，作者写的audio有个uni-app就好了 @jin-yufeng

**Comment by jin-yufeng** [comment]
已经有 `uni-app` 里用的 [audio](https://jin-yufeng.github.io/Parser/#/instructions?id=audio) 啦

**Comment by lsw1990** [comment]
@jin-yufeng 好的，十分感谢，测试一下
