### ISSUE TITLE
ol标签在android和ios上的表现不一致

### ISSUE THREAD

**Issue by slimvan** [jin-yufeng/Parser#124]
![image](https://user-images.githubusercontent.com/17959299/80077536-3170b700-8580-11ea-8742-2dd0a1f8a566.png)

**Comment by jin-yufeng** [comment]
`ios` 上真机调试一下看看？

**Comment by slimvan** [comment]
> `ios` 上真机调试一下看看？

真机调试也是和上图一样，IOS上显示的是点，但是微信开发工具上选择设备为iPhone时，效果和android设备一致，显示数字。

**Comment by jin-yufeng** [comment]
真机调试 `wxml` 面板里看一下这里是不是被 `rich-text` 显示的，是的话应该是 `rich-text` 的表现差别，就没办法了

**Comment by slimvan** [comment]
![image](https://user-images.githubusercontent.com/17959299/80295869-0321f000-87a9-11ea-8f99-160997974012.png)
确实都是被rick-text显示的，那应该是微信做的差异化处理咯
