### ISSUE TITLE
小程序列表标签显示错位

### ISSUE THREAD

**Issue by sknosh** [jin-yufeng/Parser#125]
**使用平台**
[微信/头条/uni-app]
微信小程序
**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/36500982/80166258-15b4f180-8610-11ea-9c07-abe9ff4b5ff0.png)
**预期的表现**  
请描述预期的表现
![image](https://user-images.githubusercontent.com/36500982/80166298-2b2a1b80-8610-11ea-921d-2c2020828596.png)
**实际的表现**  
请描述实际的表现

**html代码**  
https://github.com/sknosh/parser-issues/blob/master/issue.html

**Comment by jin-yufeng** [comment]
目前最新版的效果：[代码片段](https://developers.weixin.qq.com/s/7asqISmA7Rgr)

**Comment by sknosh** [comment]
ok了，谢谢

**Comment by sknosh** [comment]
![image](https://user-images.githubusercontent.com/36500982/81149275-79e09980-8fb0-11ea-9b5a-3f48fb071869.png)
预期并排显示，实际分行显示

**Comment by jin-yufeng** [comment]
现在这个可以啦 [代码片段](https://developers.weixin.qq.com/s/0seYm9ma7lhz)

**Comment by sknosh** [comment]
可以了，谢谢
