### ISSUE TITLE
在mpvue中使用的时候，图片存在不可避免的闪动问题

### ISSUE THREAD

**Issue by Jieyuhua9193** [jin-yufeng/Parser#126]
**使用平台**
微信

**问题描述**  
在mpvue中使用的时候，图片首次加载的时候回出现严重的闪动问题，根据官网提供的方法修复了之后，虽然没有了很严重的闪动，但是在滑动过程中，图片还是会有一些细微的抖动，影响体验，另外，mpvue在图片预览返回之后，有不可避免的setData行为，所以只能暂时组织预览的操作，希望后面可以优化一下。

**预期的表现**  
图片加载和预览过程中不再闪动

**实际的表现**  
![Uploading image.png…]()
类似于这种图片，在滑动过程中也有闪动的情况。
**html代码**  
```html
<div class="content">
      <div class="details" v-if="tabV === 0">
        <parser
          ref="preLoad"
          :html="detail"
          :show-with-animation="true"
          :use-cache="true"
          :lazy-load="true"
          @imgtap="onImageClick"/>
      </div>
      <div class="evaluation" v-if="tabV === 1">
        <div
          class="evaluation-wrap"
          v-if="evaluationCount && evaluationCount > 0">
          <Evaluation :id="id"/>
        </div>
        <div class="empty" v-else>
          暂无内容
        </div>
      </div>
    </div>
```
备注：代码中的detail为富文本内容，接口请求后父组件通过props传递而来

**Comment by jin-yufeng** [comment]
图片加载完后闪动的问题正在解决

**Comment by Jieyuhua9193** [comment]
我发现问题了，我这里滑动闪动的原因是，因为我监听滚动的时候，执行了一个页面元素的setData的操作，所以才会有抖动问题，去掉这个setData的操作，就没问题了

**Comment by AdminChenLY** [comment]
mpvue中使用   图片预览返回后    直接回到页面顶部了  期待解决

**Comment by jin-yufeng** [comment]
@AdminChenLY 上传一个能复现的示例项目？

**Comment by jin-yufeng** [comment]
@Jieyuhua9193 图片首次加载完闪动的问题可以现在再试试

**Comment by AdminChenLY** [comment]
额  用了  新的后  没问题了   谢谢
