### ISSUE TITLE
抱歉，没看懂怎么在 支付宝小程序 或者 钉钉小程序 中使用

### ISSUE THREAD

**Issue by zcdll** [jin-yufeng/Parser#127]
**使用平台**
钉钉小程序（支付宝小程序）

**问题描述**  
抱歉，没看懂怎么在 支付宝小程序 或者 钉钉小程序 中使用

看到更新记录中有提到 支付宝小程序，但是没发现怎么用。。。

**Comment by zcdll** [comment]
貌似是只有用了 uni-app 才能在支付宝小程序中使用么。。。

我在用 Taro 开发，有办法使用吗？

谢谢

**Comment by jin-yufeng** [comment]
目前只有 `uni-app` 包能编译到支付宝小程序

**Comment by zcdll** [comment]
> 目前只有 `uni-app` 包能编译到支付宝小程序

嗯嗯，谢谢
