### ISSUE TITLE
ios真机上外层容器text-decoration: underline;无法继承到子级容器

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#128]
**使用平台**
uni-app

**问题描述**  
外部容器含有text-decoration: underline;在ios真机上无法继承
![image](https://user-images.githubusercontent.com/15627064/80194171-91349400-864c-11ea-9844-8488a2e4876d.png)

**预期的表现**  
ios真机上出现下划线样式
![image](https://user-images.githubusercontent.com/15627064/80194281-b88b6100-864c-11ea-92e3-621b484477ae.png)

**实际的表现**  
ios真机上无法显示下划线样式
![image](https://user-images.githubusercontent.com/15627064/80194290-bd501500-864c-11ea-9902-21b16ccecb39.png)

**Comment by jin-yufeng** [comment]
这我好像也没有办法
