### ISSUE TITLE
一个牛逼的需求，让我人生进入了不牛逼的时代，何去何从？

### ISSUE THREAD

**Issue by lsw1990** [jin-yufeng/Parser#129]
**新功能描述**  
描述需要的功能或改进建议
现在有这么一个需求，文章需要点击段落修改，针对点击的这个段落内容修改，目前我的解决方案就是绑定rich-text上绑定一个点击事件,然后再去操作一系列dom。但是整个文章中还有video,audio,img,a这些特殊标签，本身有绑定点击事件，我脑瓜子快拍碎了，没想出来针对这样子的需求一个比较优雅的解决方案，故此请教博主有何优雅的方案实现这种灰暗的需求，让我多活几年^_^

**应用场景**  
描述该新功能的应用场景

**Comment by jin-yufeng** [comment]
这可能需要一个编辑器😂
