### ISSUE TITLE
3Dtouch后页面挂了

### ISSUE THREAD

**Issue by Grace-ZJH** [jin-yufeng/Parser#130]
**使用平台**
微信
**问题描述**  
微信小程序 图片触发3Dtouch 后页面挂了

![758374256049548538](https://user-images.githubusercontent.com/50861015/80297005-eb9b3500-87b1-11ea-80c1-2754c9c7f7f7.jpg)

**Comment by jin-yufeng** [comment]
这是怎么触发的
什么样的挂了

**Comment by Grace-ZJH** [comment]
然后页面就挂了，无法触发放大图片等操作了




| |
hh
|
|
邮箱：zhangjiahdyx@163.com
|

Signature is customized by Netease Mail Master

在2020年04月26日 11:40，jin-yufeng 写道：

这是怎么触发的
什么样的挂了

**Comment by jin-yufeng** [comment]
似乎和 [这个问题](https://developers.weixin.qq.com/community/develop/doc/00062821e98ea087fe5ad305254c00) 有关

**Comment by jin-yufeng** [comment]
找到 [解决方案](https://developers.weixin.qq.com/community/develop/doc/0008a450c4cfe858f21ab894156800?highLine=rich-text%2520%25E5%259B%25BE%25E7%2589%2587%25E9%2595%25BF%25E6%258C%2589) 了，我来给图片加上 `-webkit-touch-callout:none;` 应该就可以了

**Comment by jin-yufeng** [comment]
现在应该不会了
