### ISSUE TITLE
编译失败 Can't resolve './cssHandler.wxs'

### ISSUE THREAD

**Issue by Jennytuz** [jin-yufeng/Parser#131]
**使用平台**
[微信]

**问题描述**  
编译失败

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html

./src/components/ParserRichText/Parser/trees/trees.wxml
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/miniTemplateLoader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './cssHandler.wxs' in '/Users/*******/src/components/ParserRichText/Parser/trees'

```

**Comment by jin-yufeng** [comment]
看 [用法](https://github.com/xPixv/Taro-ParserRichText#%E7%94%A8%E6%B3%95) 第 4 条

**Comment by jin-yufeng** [comment]
可以参考 [在 taro 中使用](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9c%a8-taro-%e4%b8%ad%e4%bd%bf%e7%94%a8)，引入最新版的插件包
