### ISSUE TITLE
头条小程序真机不显示图片

### ISSUE THREAD

**Issue by yeojongki** [jin-yufeng/Parser#133]
**使用平台**
头条 IOS

**问题描述**  
1. 富文本中的图片在真机下不显示
2. 使用原生的 rich-text 是可以在真机下显示的
3. 查了相关 ` issue`: https://github.com/jin-yufeng/Parser/issues/69 不是该 issue 中的问题

**预期的表现**  
图片正常显示

**实际的表现**  
图片不显示

**html代码**  
```js
// index.js
Page({
  data: {
    html: "<img src='https://www.baidu.com/img/bd_logo1.png'/>",
    nodes: [
      {
        name: "img",
        attrs: {
          src: 'https://www.baidu.com/img/bd_logo1.png'
        }
      }
    ]
  }
});

// index.json
{
  "usingComponents": {
    "parser": "../../parser.tt/parser"
  }
}

// index.ttml
<rich-text nodes="{{nodes}}"></rich-text>
<parser html="{{html}}"></parser>
```

补充：用的是 4.26 更新的版本，之前 4.25也不行
另外发现个 `bug`：头条小程序用的是 `.ttss` 下载后文件夹中的是 `.wxss`

**Comment by jin-yufeng** [comment]
模拟器上能显示吗？

**Comment by yeojongki** [comment]
@jin-yufeng 
模拟器：都能显示
真机：只有原生的 `rich-text` 能显示

**Comment by yeojongki** [comment]
补充一张在真机下的显示情况：
![image](https://user-images.githubusercontent.com/21023676/80687421-d8170380-8afc-11ea-8a69-eba91c9cc90e.png)

**Comment by jin-yufeng** [comment]
我没有头条账号没法真机测试，麻烦帮忙测试一下以下几种方案能不能显示  
把 `trees.ttml` 中 `tt:if="{{n.name=='img'}}"` 的 `view` 替换为以下几个内容  
- 第一种  
```html
<view tt:if="{{n.name=='img'}}" id="{{n.attrs.id}}" class="_img {{n.attrs.class}}" style="{{n.attrs.style}}" data-attrs="{{n.attrs}}" bindtap="imgtap">
  <rich-text nodes="<img src='{{lazyLoad&&!n.load?placeholder:n.attrs.src}}' alt='{{n.attrs.alt}}' width='{{n.attrs.width}}' style='max-width:100%;display:inherit{{n.attrs.height?';height:'+n.attrs.height:''}}'>" style="display:inherit" />
  <image class="_image" src="{{lazyLoad&&!n.load?placeholder:n.attrs.src}}" lazy-load="{{lazyLoad}}" data-i="{{index}}" data-source="img" bindload="loadImg" binderror="error" />
</view>
```
- 第二种  
```html
<rich-text tt:if="{{n.name=='img'}}" class="_img {{n.attrs.class}}" nodes="{{[n]}}" style="{{n.attrs.style}}" data-attrs="{{n.attrs}}" bindtap="imgtap" />
```

**Comment by yeojongki** [comment]
第一种不行，
第二种可以，但是样式没了

**Comment by jin-yufeng** [comment]
真机调试一下看看不显示的时候 `Bxml` 面板里这里的情况？

**Comment by yeojongki** [comment]
> 真机调试一下看看不显示的时候 `Bxml` 面板里这里的情况？

头条小程序只有安卓才能真机调试，我没有安卓设备

**Comment by jin-yufeng** [comment]
有空再试一下这样能不能显示
```html
<view tt:if="{{n.name=='img'}}" id="{{n.attrs.id}}" class="_img {{n.attrs.class}}" style="{{n.attrs.style}}" data-attrs="{{n.attrs}}" bindtap="imgtap">
  <rich-text tt:if="{{!lazyLoad||n.load}}" nodes="{{[n]}}" style="display:inherit" />
  <image class="_image" src="{{lazyLoad&&!n.load?placeholder:n.attrs.src}}" lazy-load="{{lazyLoad}}" data-i="{{index}}" data-source="img" bindload="loadImg" binderror="error" />
</view>
```

**Comment by qwertyahaha** [comment]
> 有空再试一下这样能不能显示
> 
> ```
> <view tt:if="{{n.name=='img'}}" id="{{n.attrs.id}}" class="_img {{n.attrs.class}}" style="{{n.attrs.style}}" data-attrs="{{n.attrs}}" bindtap="imgtap">
>   <rich-text tt:if="{{!lazyLoad||n.load}}" nodes="{{[n]}}" style="display:inherit" />
>   <image class="_image" src="{{lazyLoad&&!n.load?placeholder:n.attrs.src}}" lazy-load="{{lazyLoad}}" data-i="{{index}}" data-source="img" bindload="loadImg" binderror="error" />
> </view>
> ```

这样真机上能显示 可是样式都不生效了

**Comment by yeojongki** [comment]
@jin-yufeng 方便的话可以申请个头条号调试下，现在应该是可以申请的

**Comment by jin-yufeng** [comment]
所有样式都不生效吗？（模拟器上呢）

**Comment by qwertyahaha** [comment]
> 所有样式都不生效吗？（模拟器上呢）

图片大小全都乱了 模拟器上也是

**Comment by jin-yufeng** [comment]
换上这个包试一下
[parser.zip](https://github.com/jin-yufeng/Parser/files/4578797/parser.zip)

**Comment by qwertyahaha** [comment]
> 换上这个包试一下
> [parser.zip](https://github.com/jin-yufeng/Parser/files/4578797/parser.zip)

模拟器正常显示了 真机直接不显示

**Comment by jin-yufeng** [comment]
试一下这几个 `rich-text` 在真机上能不能显示
```html
<rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='display:inherit'>" />
<rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='max-width:100%'>" />
<rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='max-width:100%;display:inherit'>" />
```

**Comment by jin-yufeng** [comment]
或者再用这个包试试
[parser.zip](https://github.com/jin-yufeng/Parser/files/4585074/parser.zip)

**Comment by yeojongki** [comment]
> 试一下这几个 `rich-text` 在真机上能不能显示
> 
> ```
> <rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='display:inherit'>" />
> <rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='max-width:100%'>" />
> <rich-text nodes="<img src='https://www.baidu.com/img/bd_logo1.png' style='max-width:100%;display:inherit'>" />
> ```

这个可以，第二 三个样式正常

**Comment by yeojongki** [comment]
> 或者再用这个包试试
> [parser.zip](https://github.com/jin-yufeng/Parser/files/4585074/parser.zip)

这个也可以 @jin-yufeng

**Comment by jin-yufeng** [comment]
好的，那就先用这个包，辛苦啦

**Comment by yeojongki** [comment]
好的 感谢哈 那我先关了这个 issue 了

**Comment by yeojongki** [comment]
> 好的，那就先用这个包，辛苦啦

感谢哈 那我先关了这个 issue 了
