### ISSUE TITLE
富文本里面的空格自动被屏蔽掉了

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/Parser#135]
**使用平台**
[微信/头条/uni-app]

**问题描述**  
![image](https://user-images.githubusercontent.com/21222276/81373544-8b9c7b00-912f-11ea-8991-49e91c9aa254.png)
富文本的字段为
```
<span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2img/7d989cdd4afcab94632d68868f0719e9.png'/></span>   <span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2img/79ad5f4eb1cbeb4a64d109bd1ec42d76.png'/></span>   <span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2img/e33252134fca3181f15454bdedb9c6e9.png'/></span>  <br> <span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2img/a8746f029c0e7ff98d2ac65ea9f31703.png'/></span>   <span class='math-tex'><img src='http://qp-tiku.oss-cn-beijing.aliyuncs.com/latex2img/7227cc613cc759d79e3477f4c7000e79.png'/></span>
```
**预期的表现**  
与网页显示的一样

**实际的表现**  

![image](https://user-images.githubusercontent.com/21222276/81373756-0ebdd100-9130-11ea-888d-33de772c6605.png)

**Comment by jin-yufeng** [comment]
[已修复](https://github.com/jin-yufeng/Parser/commit/2bbf84e4cb04ae6577078ea14d8004f0746d2fee#diff-56c867f718c450e5fcef15a459253ebbL78)

**Comment by 45221378** [comment]
谢谢，经测试，已经修复好。
大神，还有一个小小的提议，就是 trees.wxss里面的 ._img 添加vertical-align:middle，否则，图片跟文字合在一起排版，图片居上，没有对齐。 
![image](https://user-images.githubusercontent.com/21222276/81469606-67689900-9218-11ea-90fb-f411c4b76dc3.png)
