### ISSUE TITLE
image宽度不生效

### ISSUE THREAD

**Issue by ilp64** [jin-yufeng/Parser#137]
**使用平台**
微信

**问题描述**  
我使用ckeditor的[imageResize](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#resizing-images)插件设置了image的宽度，但是在微信小程序里面解析出来的时候width样式不起作用。

**预期的表现**  
在微信小程序中width样式生效

**实际的表现**  
微信小程序里面解析出来的时候width样式加到了`trees`上，但是实际上里面image的宽度还是100%的

**html代码**  
ckeditor中的width是加在外层的`figure`上的，dom结构是这样的：
```html
<figure class="image ck-widget ck-widget_with-resizer image_resized" contenteditable="false" style="width:59.74%;">
  <img src="../assets/img/fields.jpg" alt="Autumn fields">
  ......
</figure>
```
小程序中解析出来是这样的：
![](https://imgs.aixifan.com/FuL59nk-hph-PQx60hUHsg1Bm1xb)

**Comment by jin-yufeng** [comment]
把 `figure` 加到 `config.js` 的 `blockTags` 里试一下吧

**Comment by ilp64** [comment]
@jin-yufeng 好使，多谢大佬😄
