### ISSUE TITLE
在uni-app  安卓版  百度小程序上使用无效

### ISSUE THREAD

**Issue by dlg611263504** [jin-yufeng/Parser#139]
**使用平台**
uni-app  安卓版  百度小程序

**问题描述**  
渲染富文本失效，无任何内容显示
真机调试无报错

渲染任何内容都无效即使只是简单的如"<div>123</div>"

**Comment by jin-yufeng** [comment]
只有真机空白还是模拟器上也是空白？

**Comment by dlg611263504** [comment]
只有真机上空白   模拟器上正常

**Comment by dlg611263504** [comment]
> 只有真机空白还是模拟器上也是空白？

模拟器上正常，ios真机正常，安卓真机上空白

**Comment by jin-yufeng** [comment]
真机基础库版本是多少

**Comment by dlg611263504** [comment]
> 真机基础库版本是多少

模拟器设置的调试库是最新的3.170.14，真机百度app基础库版本也是最新的3.180.4

**Comment by jin-yufeng** [comment]
这就神奇了啊，真机调试看看 `Elements` 面板里有没有东西？

**Comment by dlg611263504** [comment]
> 这就神奇了啊，真机调试看看 `Elements` 面板里有没有东西？

富文本内容我放了
`<div>123</div>`
真机调试里elememts面板内容是
`<swan-jyf-parser class=" vue-ref   sw-0__vue-ref " id="_7c267"><swan-view><!--_7c268--><swan-view id="top"><!--_7c272--><swan-trees id="_7c273"><swan-view class=" interlayer   sw-6__interlayer "><!--_7c274--></swan-view></swan-trees><!--_7c272--></swan-view></swan-view></swan-jyf-parser>`

**Comment by jin-yufeng** [comment]
`parse` 事件有触发吗

**Comment by dlg611263504** [comment]
> `parse` 事件有触发吗

试了一下  触发了

**Comment by jin-yufeng** [comment]
在 `jyf-parser.vue` 里加一个 `{{JSON.stringify(nodes)}}` 看看有没有内容吧  
![微信截图_20200514181246](https://user-images.githubusercontent.com/48236054/81922331-88612d80-960e-11ea-91b8-a5fddfd66144.png)

**Comment by dlg611263504** [comment]
> 在 `jyf-parser.vue` 里加一个 `{{JSON.stringify(nodes)}}` 看看有没有内容吧
> ![微信截图_20200514181246](https://user-images.githubusercontent.com/48236054/81922331-88612d80-960e-11ea-91b8-a5fddfd66144.png)

试了  结果是
`[{"name":"div","attrs":{},"children":[{"type":"text","text":"123"}],"PoweredBy":"Parser"}]`
但是页面上并没有123渲染出来

**Comment by jin-yufeng** [comment]
那再在 `trees.vue` 里看一下
![微信截图_20200514210217](https://user-images.githubusercontent.com/48236054/81937510-4b089a00-9626-11ea-91a1-f6bcad53f872.png)

**Comment by dlg611263504** [comment]
> 那再在 `trees.vue` 里看一下
> ![微信截图_20200514210217](https://user-images.githubusercontent.com/48236054/81937510-4b089a00-9626-11ea-91a1-f6bcad53f872.png)

只渲染了一个空数组
`[]`

**Comment by jin-yufeng** [comment]
那把这个 `ns` 改成 `nodes` 试一下
![微信截图_20200515104532](https://user-images.githubusercontent.com/48236054/82005914-39aca580-9699-11ea-8d8d-2ef02faa8c38.png)

**Comment by dlg611263504** [comment]
> 那把这个 `ns` 改成 `nodes` 试一下
> ![微信截图_20200515104532](https://user-images.githubusercontent.com/48236054/82005914-39aca580-9699-11ea-8d8d-2ef02faa8c38.png)

改成这样后，文字能渲染出来了，图片的位置占着但是显示不出来了，为空白

**Comment by jin-yufeng** [comment]
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4632471/jyf-parser.zip)
换上这个包试试

**Comment by dlg611263504** [comment]
> [jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4632471/jyf-parser.zip)
> 换上这个包试试

不行，全为空

**Comment by jin-yufeng** [comment]
那打印一下看看 `trees.vue` 里的 `mounted` 有没有触发？
![微信截图_20200515135252](https://user-images.githubusercontent.com/48236054/82016400-89986600-96b3-11ea-8110-94c9948f4363.png)

**Comment by dlg611263504** [comment]
> 那打印一下看看 `trees.vue` 里的 `mounted` 有没有触发？
> ![微信截图_20200515135252](https://user-images.githubusercontent.com/48236054/82016400-89986600-96b3-11ea-8110-94c9948f4363.png)

触发了！

**Comment by jin-yufeng** [comment]
这里打印一下 `this.ns` 看看有没有值
![微信截图_20200515140246](https://user-images.githubusercontent.com/48236054/82017107-fceea780-96b4-11ea-9d1c-b139ad59820f.png)

**Comment by dlg611263504** [comment]
> 这里打印一下 `this.ns` 看看有没有值
> ![微信截图_20200515140246](https://user-images.githubusercontent.com/48236054/82017107-fceea780-96b4-11ea-9d1c-b139ad59820f.png)

打印出来是空白

**Comment by jin-yufeng** [comment]
那就是 `mounted` 时没有值，`watch` 又没有触发，这可太难了

**Comment by jin-yufeng** [comment]
麻烦再试一下这样可不可以
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4634595/jyf-parser.zip)

**Comment by dlg611263504** [comment]
> 麻烦再试一下这样可不可以
> [jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4634595/jyf-parser.zip)

不好意思回复晚了，经测试，这个包可以正常渲染了，图片文字表格都没问题，点赞
