### ISSUE TITLE
uni在H5与APP端a标签无法阻止跳转

### ISSUE THREAD

**Issue by shy1118999** [jin-yufeng/Parser#140]
uni版本在APP端与H5端使用ignore() 无法阻止跳转链接

**Comment by jin-yufeng** [comment]
用示例项目试过吗？
我试了一下  
```javascript
linkpress(e) {
	e.ignore();
},
```
在 `H5` 和 `App` 是可以阻止跳转的

**Comment by shy1118999** [comment]
![图片](https://s17.aconvert.com/convert/p3r68-cdx67/a2klo-l380f.gif)

**Comment by shy1118999** [comment]
![image](https://user-images.githubusercontent.com/38638186/82006365-349c2600-969a-11ea-8ca6-048cad61b244.png)

**Comment by jin-yufeng** [comment]
给我个能复现的 `demo`？或者把这段 `html` 给我试一下

**Comment by shy1118999** [comment]
嗯嗯  可以是我的问题  谢谢了
