### ISSUE TITLE
h5下 不进入filter方法

### ISSUE THREAD

**Issue by Estelle00** [jin-yufeng/Parser#144]
**使用平台**
h5

**问题描述**  
不进入filter方法

**预期的表现**  
进入filter方法

**Comment by jin-yufeng** [comment]
`H5` 不进行解析，直接通过 `dom` 显示，所以不会调用 `filter`  
需要的话可以直接操作 `dom`

**Comment by Estelle00** [comment]
个人希望对外API在每一端都能表现一直

**Comment by jin-yufeng** [comment]
我也希望能够表现一致的，这个问题主要是这样，在小程序上，因为不支持操作 `dom` 且不支持 `html` 标签，只能先进行解析（这时调用了 `filter`），然后通过小程序的标签来模拟 `html` 的效果  

但 `H5` 本身就支持 `html`，也可以通过 `dom` 直接设置，如果还是采用和小程序相同的方式，通过小程序标签来模拟 `html` 的效果，而这些小程序标签又是通过 `html` 标签实现的，这样绕来绕去不仅损耗了性能，能力也受到限制，个别情况下还会出现样式错误（现在就是一些小程序上无法正常显示的内容在 `H5` 上就可以），所以目前 `H5` 是通过 `innerHTML` 的方式设置的  

这样 `H5` 没有将字符串解析为 `node` 数组，即使是设置完后遍历所有标签调用 `filter` 输入的格式也不相同；相似的问题还有 `H5` 通过这样的方式也不需要用到递归组件 `trees`（用于模拟 `dom` 树），其他端写在 `trees.vue` 里的样式能生效，`H5` 就不行（只能用 `style` 标签），这些地方统一起来还比较困难
