### ISSUE TITLE
小程序报错 null is not an object (evaluating 't.height')

### ISSUE THREAD

**Issue by alvinfang27** [jin-yufeng/Parser#146]
null is not an object (evaluating 't.height');at SelectorQuery callback function
https://miniprogram:///parser/parser.js:225:15
报错率不高，但是这几天都能看到

**Comment by jin-yufeng** [comment]
那可能是 `SelectorQuery` 偶尔不稳定没选取到？我在这里加个判断好了

**Comment by jin-yufeng** [comment]
新版在 [这里](https://github.com/jin-yufeng/Parser/commit/96f76b8758395f7a2090713a0fd45332e0dd4217#diff-19963bcd242449d301a8da34fcdfcfd1R222) 加了个判断，应该不会了
