### ISSUE TITLE
在nvue中使用v-if切换外层容器的显示状态后，渲染空白

### ISSUE THREAD

**Issue by siyukok** [jin-yufeng/Parser#147]
**使用平台**
uniapp

**问题描述**  
页面中包含了几个tab，切换的时候简单的使用了v-if的方式来显示不同的内容，刚一进来的时候，jyf-parser可以正常显示，但是切换到别的tab，即jyf-parser外层容器的v-if值变为了false后，再切换回初始的tab，即此时jyf-parser的外层容器v-if值又变为了true，但是jyf-parser并没有正常渲染，而且一片空白

**预期的表现**  
希望切换tab回来后，能正常渲染富文本

**实际的表现**  
切换回来后，渲染的是一片空白

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<template>
	<div class="container">
		<list style="flex: 1;">
			<nav-bar :transparent="transparentNavBar" @height="onBarHeight"></nav-bar>
			<cell :key="`0`">
				<image class="poster" src="/static/img/bg_poster_test.png" @appear="onPosterAppear" @disappear="onPosterDisappear"></image>
			</cell>
			<header :key="`0-header`">
				<div class="tab-bar" :style="{top:tabBarStickyTop}">
					<div class="tab" v-for="(tab ,index) in tabs" :key="index" @click="onTabChanged(index)">
						<text class="tab-title" :class="{'tab-title-select':currentSelect===index}">{{tab}}</text>
						<div class="tab-indicator" v-if="currentSelect===index"></div>
					</div>
				</div>
			</header>

			<cell key="1">
				<jyf-parser v-if="currentSelect===0" :html="courseDetail.description" @imgtap="onImageTap"></jyf-parser>
			</cell>
		</list>
		<div class="bottom-content">
			<div class="free-try">
				<text class="free-try-text">免费试听</text>
			</div>
			<!-- 			<div class="positive-button">
					<text class="positive-button-text" style="font-size: 32rpx;">购买</text>
					<text class="positive-button-text" style="font-size: 28rpx;margin-left: 23rpx;">99幸福力</text>
			</div> -->
			<div class="positive-button">
				<image style="width: 35rpx;height: 33rpx;" src="/static/img/course/icon_course_vip_white.png"></image>
				<text class="positive-button-text" style="font-size: 32rpx;margin-left: 13rpx;">开通VIP</text>
			</div>
		</div>
	</div>
</template>

<script>
</script>

<style scoped>
	.container {
		flex: 1;
	}

	.poster {
		width: 750rpx;
		height: 500rpx;
	}

	.brief {
		width: 750rpx;
		height: 80rpx;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
		padding-left: 38rpx;
		padding-right: 38rpx;
	}

	.brief-title {
		flex: 1;
		font-size: 28rpx;
		color: #333333;
		lines: 1;
		text-overflow: ellipsis;
	}

	.brief-times {
		font-size: 22rpx;
		color: #999999;
	}

	.tab-bar {
		width: 750rpx;
		height: 100rpx;
		background-color: #FFFFFF;
		padding-left: 7.5rpx;
		padding-right: 7.5rpx;
		flex-direction: row;
	}

	.tab {
		flex: 1;
		align-items: center;
		padding-top: 40rpx;
	}

	.tab-title {
		font-size: 30rpx;
		color: #999999;
		line-height: 42rpx;
	}

	.tab-title-select {
		color: #333333;
		font-weight: bold;
	}

	.tab-indicator {
		width: 26rpx;
		height: 5rpx;
		margin-top: 7rpx;
		border-radius: 5.5rpx;
		background-color: #FF5551;
	}

	.bottom-content {
		flex-direction: row;
		width: 750rpx;
		height: 110rpx;
	}

	.free-try {
		width: 320rpx;
		height: 110rpx;
		justify-content: center;
		align-items: center;
		background-color: #FFFFFF;
	}

	.free-try-text {
		font-size: 32rpx;
		color: #333333;
		font-weight: bold;
	}

	.positive-button {
		flex-direction: row;
		flex: 1;
		justify-content: center;
		align-items: center;
		background-image: linear-gradient(to right, #FF6D69, #FF5551);
	}

	.positive-button-text {
		color: #FFFFFF;
		font-weight: bold;
	}
</style>
```

非常感谢作者开发的这个库，比uniapp官方的rich-text强大很多，唯一困扰我的就是现在这个问题，期望得到您的回复，谢谢

**Comment by jin-yufeng** [comment]
是最新版吗？

**Comment by siyukok** [comment]
在uniapp插件商城使用HBuidlerX直接导入的，我也不确定版本是不是最新的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jin-yufeng<mailto:notifications@github.com>
发送时间: 2020年5月21日 20:59
收件人: jin-yufeng/Parser<mailto:Parser@noreply.github.com>
抄送: AliasWang<mailto:devilkeven@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jin-yufeng/Parser] 在nvue中使用v-if切换外层容器的显示状态后，渲染空白 (#147)


是最新版吗？

―

**Comment by siyukok** [comment]
等明天我到公司用GitHub主分支的代码试一下，感谢回复

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: jin-yufeng<mailto:notifications@github.com>
发送时间: 2020年5月21日 20:59
收件人: jin-yufeng/Parser<mailto:Parser@noreply.github.com>
抄送: AliasWang<mailto:devilkeven@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jin-yufeng/Parser] 在nvue中使用v-if切换外层容器的显示状态后，渲染空白 (#147)


是最新版吗？

―

**Comment by jin-yufeng** [comment]
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4663288/jyf-parser.zip)
换上这个包试试行不行

**Comment by siyukok** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    jin-yufeng/Parser       好的，我试一下，非常感谢2020-05-22
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                devilkeven
                            
                    
                        
                            
                                    devilkeven@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    在2020年05月21日 23:37，jin-yufeng<notifications@github.com> 写道： 




jyf-parser.zip

换上这个包试试行不行



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by siyukok** [comment]
@jin-yufeng 完美解决问题，感谢🙏
