### ISSUE TITLE
排版问题：每行空格未保留

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#148]
**使用平台**
uni-app

**问题描述**  
富文本中每行文本前都有空格来达到希望的排版效果，但parser转换出来的文本没有保留原有的空格，排版效果差异较大

**预期的表现**  
都保留各行空格
![image](https://user-images.githubusercontent.com/15627064/82643604-5f5e1f80-9c42-11ea-9e17-5062952df43d.png)

**实际的表现**  
parser转换出来的每行文本前没有保存空格
![image](https://user-images.githubusercontent.com/15627064/82643266-ccbd8080-9c41-11ea-9070-144ec9db79e1.png)

**html代码**  
请附上出现问题的html代码（或附件），例如：
text: "<div>『居佳易』预约看房服务：</div><div>      ●24小时免费接机</div><div>          ●24小时免费咨询</div><div>              ●免费接送带看</div><div>              ●团购优惠<br></div>"

```html
<div>『居佳易』预约看房服务：</div><div>      ●24小时免费接机</div><div>          ●24小时免费咨询</div><div>              ●免费接送带看</div><div>              ●团购优惠<br></div>
```

**Comment by jin-yufeng** [comment]
`html` 本来就是合并空白符的，在浏览器里也是这样  
![QQ截图20200522154639](https://user-images.githubusercontent.com/48236054/82644170-73565100-9c43-11ea-9ba7-401c49e33717.png)
要使用连续的空格要么用实体空格（`&nbsp;` 等），要么设置 `white-space:pre`（至于加上样式还是存在差异应该是因为这是在调试器里才加上的吧；在解析的时候，如果没有设置 `white-space:pre`，就会直接把空白符合并掉来减小解析结果的大小，加快渲染速度）
![QQ截图20200522155242](https://user-images.githubusercontent.com/48236054/82644692-51110300-9c44-11ea-8844-2dbc1379f0b6.png)

**Comment by macanfa108** [comment]
按照你所提出的两种方式，采用的是第二种配合样式去排版
尝试了下，确实是需要在解析的时候加上才能渲染出来效果（外层容器加类名渲染不到）
![image](https://user-images.githubusercontent.com/15627064/82646738-b31f3780-9c47-11ea-8f51-21c96c809bf3.png)

已解决！感谢提示

这种情况（https://github.com/jin-yufeng/Parser/issues/128）
应该也是同样的道理，我是将需要渲染的富文本内容多包裹一层u标签再进去解析的
