### ISSUE TITLE
请问在taro中如何使用，能否给个例子

### ISSUE THREAD

**Issue by wjj5728** [jin-yufeng/Parser#15]

**Comment by jin-yufeng** [comment]
目前只用于原生的框架，对于其他框架还没有适配

**Comment by xPixv** [comment]
@jin-yufeng @wjj5728

Taro 的封装的组件：https://github.com/xPixv/Taro-ParserRichText

只适用于微信小程序

**Comment by jin-yufeng** [comment]
@xPixv 优秀！加到介绍里啦
