### ISSUE TITLE
怎么让它不能左右滚动呢

### ISSUE THREAD

**Issue by bby0856** [jin-yufeng/Parser#150]
**使用平台**
[微信]

**问题描述**  
怎么让它不能左右滚动呢

![image](https://user-images.githubusercontent.com/23429615/82776157-8e5fd580-9e7c-11ea-8870-b1f02ba03118.png)

**Comment by jin-yufeng** [comment]
`parser` 标签的 `style` 里加个 `overflow:hidden` 应该就可以了，更多参考 [出现横向滚动条](https://jin-yufeng.github.io/Parser/#/question?id=%e5%87%ba%e7%8e%b0%e6%a8%aa%e5%90%91%e6%bb%9a%e5%8a%a8%e6%9d%a1)

**Comment by bby0856** [comment]
嗯 非常感谢
