### ISSUE TITLE
Chameleon 变色龙 框架支持

### ISSUE THREAD

**Issue by wuyansongs** [jin-yufeng/Parser#151]
**新功能描述**  
支持一下Chameleon框架

**应用场景**  
https://github.com/didi/chameleon

**Comment by jin-yufeng** [comment]
目前可以引入原生包使用，具体参考 [在 chameleon 中使用](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9c%a8-chameleon-%e4%b8%ad%e4%bd%bf%e7%94%a8)  
专用包目前没有（精力有限）
