### ISSUE TITLE
识别不出来后端返回的富文本编辑器里面的class类名

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/Parser#152]
**使用平台**
[微信/qq/百度/头条/uni-app]

**问题描述**  
识别不出来后端返回的富文本编辑器里面的class类名

**html代码**  
请附上出现问题的html代码（或附件），例如：
```
  testClass1:"<span class ='underline'> (1) </span> your best to speak． Don't be<span class ='underline'> (2) </span> of making mistakes．But be careful not to let them stop you from improving your <span class ='underline'> (3) </span>．A good <span class ='underline'> (4) </span> to ",
    testClass2:"<span class='point2'>分</span>外/满<span class='point2'>分</span> 分<span class='point2'>泌</span>/<span class='point2'>沁</span>人心脾 呜<span class='point2'>咽</span>/狼吞虎<span class='point2'>咽</span>"
 
```
testClass1不能识别出underline，testClass2可以识别point。因为后端返回的字符串里面多了一个空格，是否可以给出一个解决方案呢？否则这边样式就设置不了了。浏览器显示没有问题。

**Comment by 45221378** [comment]
目前我想到了一种很解决方案。
testClass1.indexOf('class =')>=0然后强制性replace掉空格。

**Comment by 45221378** [comment]
目前我想到了一种解决方案。
testClass1.indexOf('class =')>=0然后强制性replace为 class= 
请问是否有更加优雅的方式呢？

**Comment by jin-yufeng** [comment]
确实属性名后有个空格就识别不出来了，我修复一下

**Comment by jin-yufeng** [comment]
[已修复](https://github.com/jin-yufeng/Parser/commit/b62568ec253d32fcc42101bc59478b8c1512fa35#diff-56c867f718c450e5fcef15a459253ebbR490)，可以重试一下

**Comment by 45221378** [comment]
看到了，已经修复。谢谢。
