### ISSUE TITLE
特殊字符无法识别

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/Parser#154]
**使用平台**
[微信/qq/百度/头条/uni-app]

**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/21222276/83994301-86c62380-a988-11ea-92fa-b4281ea0c6b1.png)

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
父亲fēn f&ugrave;（<span class='brack'></span>）我们在t&iacute;ng（<span class='brack'></span>）子旁择菜。</br>

母亲在她那半mǔ（<brack>&nbsp;</brack>）地里bō（<brack>&nbsp;</brack>）下了葵花的种子，jiāo（<brack>&nbsp;</brack>）水、锄草。到了收获的季节，看到那圆圆的向日葵花盘，别人都很羡m&ugrave;（<brack>&nbsp;</brack>）。
```

**Comment by jin-yufeng** [comment]
暂时有两个办法
一个是在外面套一个 `div`，这样会直接通过 `rich-text` 显示，应该可以支持这些实体
![微信截图_20200608134225](https://user-images.githubusercontent.com/48236054/83996448-c8f26380-a98e-11ea-835a-ec55ffddbf90.png)

另一个就是把这些实体加到 `config.js` 里的 `entities` 中
![微信截图_20200608134836](https://user-images.githubusercontent.com/48236054/83996451-ce4fae00-a98e-11ea-85d2-65844a1ff720.png)

**Comment by 45221378** [comment]
好的，处理好了，谢谢。
