### ISSUE TITLE
span标签设置字体大小小于12px的,父级不给字体大小的时候,会有很大的行距

### ISSUE THREAD

**Issue by 876858394** [jin-yufeng/Parser#155]
**使用平台**
微信小程序
[微信/qq/百度/头条/uni-app]

**问题描述**  
span标签设置字体大小小于12px的,父级不给字体大小或者没有父级的时候,会有很大的行距
请详细描述遇到的问题（可附图）
![ea8cd296c8d56e2f90cea24d98fd076](https://user-images.githubusercontent.com/65991349/84006620-a1f15d00-a9a1-11ea-927e-09bcd684cca6.png)
![1bf5faeea610c7dad8c17d7a55f32de](https://user-images.githubusercontent.com/65991349/84006604-9b62e580-a9a1-11ea-864a-b0cbaaf8b7c4.png)
![50696de044e663bb13c4452fb6dbb51](https://user-images.githubusercontent.com/65991349/84006630-a6b61100-a9a1-11ea-805b-cc856d8efd5c.png)
![558c122b7601adc24e91d1f0b7e3cab](https://user-images.githubusercontent.com/65991349/84006637-ab7ac500-a9a1-11ea-90c3-1ce458c9b8c7.png)

**预期的表现**  
请描述预期的表现
希望行高能自适应

**Comment by jin-yufeng** [comment]
是有这个问题，但是小程序中的表现好像就是这样，暂时没什么办法
![1](https://user-images.githubusercontent.com/48236054/84358937-7a490180-abfa-11ea-9790-7ab1651b6106.png)

**Comment by 876858394** [comment]
好吧,我通过您的过滤器检测子集的字体大小和行距倍率,强行给父级加了行高,暂时是可以了。
