### ISSUE TITLE
小程序嵌套的iframe腾讯视频可以播放吗

### ISSUE THREAD

**Issue by Lich3nbo** [jin-yufeng/Parser#156]
**新功能描述**  
小程序中嵌套iframe腾讯视频

**应用场景**  
小程序中嵌套iframe腾讯视频

**Comment by jin-yufeng** [comment]
需要用腾讯视频插件，参考 [使用 iframe 视频](https://jin-yufeng.github.io/Parser/#/question?id=%e6%97%a0%e6%b3%95%e4%bd%bf%e7%94%a8-iframe-%e8%a7%86%e9%a2%91)

**Comment by Lich3nbo** [comment]
嗯嗯 我现在是截取腾讯视频 vid 然后 video标签头部。

**Comment by songStar0904** [comment]
模拟器没问题，真机报错：
```js
Component is not found in path "plugin://tencentvideo/video"
```
有遇到过这个问题么  咋解决
