### ISSUE TITLE
富文本里面有大段连续空格，不显示

### ISSUE THREAD

**Issue by 45221378** [jin-yufeng/Parser#157]
**新功能描述**  

![image](https://user-images.githubusercontent.com/21222276/84215574-44702400-aaf9-11ea-91bf-e7b58d23917c.png)

**应用场景**  
请问下，富文本的大段连续空格，可以设置<rich-text type = "node*" space="ensp" nodes="{{text}}"></rich-text>就会显示，请问插件里面，怎么可以把这个连续空格属性加上去？

**Comment by 45221378** [comment]
大部分场景下，需要打开这个属性，否则字体都会上下挤在一起。
space="ensp"

**Comment by jin-yufeng** [comment]
目前可以这样
1. 把空格替换为实体 `&ensp;`  

   ```javascript
   html = html.replace(/ /g, '&ensp;');
   ```
2. 最外层套一个 `div`，然后设置 `white-space:pre`  

   ```javascript
   html = '<div style="white-space:pre">' + html + '</div>
   ```

**Comment by 45221378** [comment]
![image](https://user-images.githubusercontent.com/21222276/84219121-63bf7f00-ab02-11ea-9ed9-caf5e04cd407.png)
还有一个问题就是overflow: scroll;这个属性，超过一屏幕的文章。如果是多个parser组合在一起，手指就会在第一个parse里面滑动，要手指划几下，才会滑动屏幕。这个直接去掉，会有副作用吗？

**Comment by 45221378** [comment]
white-space:pre不行，强制性一行显示了。要用white-space:pre-wrap

**Comment by jin-yufeng** [comment]
> ![image](https://user-images.githubusercontent.com/21222276/84219121-63bf7f00-ab02-11ea-9ed9-caf5e04cd407.png)
> 还有一个问题就是overflow: scroll;这个属性，超过一屏幕的文章。如果是多个parser组合在一起，手指就会在第一个parse里面滑动，要手指划几下，才会滑动屏幕。这个直接去掉，会有副作用吗？

去掉就内部无法横向滚动

**Comment by 45221378** [comment]
![image](https://user-images.githubusercontent.com/21222276/84223384-645d1300-ab0c-11ea-9e81-07c1b35929fc.png)
手指滑动的时候，是文章的区域在滚动，不是屏幕。

**Comment by 45221378** [comment]
```
<!-- <parser lazy-load="true" html="{{pageData.indexstem}}" /> -->
<rich-text type = "node*" space="ensp" nodes="{{pageData.indexstem}}"></rich-text>
```
换成rich-text就没有问题了。
```
html = "快乐阅读。 <div style='text-align: center;'><longfill> </longfill>​</div><p class='text-indent'><span style='font-family:KaiTi;'>人有时会莫名烦闷，我便时时站到阳台上，看看鸟儿。鸟儿或是三五成群地集在树丛叽叽喳喳；或是一个两个停在对面的楼上，俯瞰着地面。时时也有觅食归来的鸟儿，它们嘴里叼着食物。我能想象得到幼鸟迫不及待地探出身子，夸张地张着小嘴儿。 </span></p><tab> </tab>​<span style='font-family: KaiTi;'>更多的时候我是在看鸟儿在空中飞翔。空中是鸟儿们行走的大道。鸟儿们在空中的姿势总是很美的，有时翅膀扇动，身子便箭似的射了出去，有时只是翅膀张着，任身子在空中滑过，滑动中有时也会蓦地来个弧形或是90度的折转，身态灵动，姿态优美，绝对堪比最好的飞机特技表演。我似乎便附体了鸟儿，我感觉我也在飞，心中哪里还有郁闷？</span><span style='font-family: KaiTi;'><br><tab> </tab>​心情好时也可以看鸟啊。傍晚，太阳西下，我也会时时站在阳台上，看着太阳一点一点地沉下，看着远处的鸟儿匆匆地往家的方向飞。眼睛远眺之处是由远及近的鸟儿。晚上树林中是喧闹的鸟的世界。鸟语啁啾，我也能听出它们的喜悦。</span><p class='text-indent'><span style='font-family:KaiTi;'> 暮鸟归，目所尽收，远处的鸟儿扇动着双翼，近了，鸟儿便张大双翼，任身子在气流中滑行，再近了，便是个优雅的弧形身影，翼微微地收缩，又近了，蓦地收起羽翼，戛然而止的身子已稳稳地站在了枝头上或是巢沿上。<span style='border-bottom:1px solid black;'><span class='underline'>拍上几下双翼，有时还侧头与林中的鸟儿们言语起来，似乎交流着一天的旅游心得。</span></span></span></p>"
```

**Comment by 45221378** [comment]
好的，感谢，找到原因了，关于overflow: scroll滑动问题是后端返回的富文本里面出现了style导致的问题。不是前端的问题。
