### ISSUE TITLE
table 中有 colspan 则 a 链接的 点击效果失效

### ISSUE THREAD

**Issue by tujw2010** [jin-yufeng/Parser#159]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信小程序

**问题描述**  
table 中有 colspan 则 a 链接的 点击效果失效

**html 代码**  
```html
<table><thead><tr><td class="title" colspan="5" style="font-size: 1.05rem;">abc</td></tr><tr class="header"><td>品牌</td><td>功能</td><td>路数</td><td>大小</td><td>总针数</td></tr></thead><tbody><tfoot><tr><td colspan="4" style="text-align: right; padding-top: 0.5rem; padding-right: 0.5rem;"><a ignore href="12345678901" class="contact">立即咨询</a></td></tr></tfoot></table>
```

**Comment by jin-yufeng** [comment]
[表格中的链接无法点击问题](https://jin-yufeng.github.io/Parser/#/question?id=%e8%a1%a8%e6%a0%bc%e4%b8%ad%e7%9a%84%e9%93%be%e6%8e%a5%e6%97%a0%e6%b3%95%e7%82%b9%e5%87%bb)
