### ISSUE TITLE
图片撑开了页面可以左右滑动，有什么办法吗

### ISSUE THREAD

**Issue by bby0856** [jin-yufeng/Parser#16]
<Parser html="{{html}}" tag-style="{{tagStyle}}" />
data:{ tagStyle:{ img:"height:auto !important" } }
请教一下就是我设置上面这个，仍旧有一些`图片撑开了页面可以左右滑动，有什么办法吗`

![image](https://user-images.githubusercontent.com/23429615/62764655-fea19400-bac0-11e9-9ba4-f4e59f476015.png)

![image](https://user-images.githubusercontent.com/23429615/62764724-22fd7080-bac1-11e9-865f-ea07013906f1.png)

**Comment by jin-yufeng** [comment]
可以提供一下html吗？

**Comment by bby0856** [comment]
嗯，谢谢啊 下面链接里
http://note.youdao.com/noteshare?id=0a12d12aa43c180b2af1e5c805a0772e

**Comment by bby0856** [comment]
我们h5端那边也是加载的富文本在手机上看正常：http://m.qizhigo.com/shops/146178/articles/5d39093ad988be3f87ae9eb5

**Comment by jin-yufeng** [comment]
应该有bug，我检查一下😂

**Comment by bby0856** [comment]
嗯，辛苦啦

**Comment by jin-yufeng** [comment]
这里主要有两个问题，一个是这几张图的宽度超出了100%
![1](https://user-images.githubusercontent.com/48236054/62784054-2cea9800-baf0-11e9-9991-269b51ae37a0.png)
这个问题很神奇，主要是父级标签设置了`display:inline-block`导致的
在小程序里
`<view style="display:inline-block">`
`  <image style="width:700px;height:500px;max-width:100%" src="http://resource.vjuzhen.com/group1/M00/00/B9/rBAAMV05DMGAK18nAAH5OE0fmVA804.jpg" />`
`</view>`
这个片段图片还是会超出屏幕宽度，但是浏览器中不会
不过这个问题可以在tagStyle中加一行`section:"max-width:100%"`就可以解决

还有一个问题是这张图片被错误的缩进了
![2](https://user-images.githubusercontent.com/48236054/62784367-e5184080-baf0-11e9-8ed1-747a38067ecb.png)
这个问题就更神奇了，这里的html代码大概是这样的
`<span style="text-indent:2em">`
`  <img src="http://resource.vjuzhen.com/group1/M00/00/B9/rBAAMV05DMGAK18nAAH5OE0fmVA804.jpg">`
`</span>`
理论上在行内标签`span`中设置`text-indent`是不生效的，但是里面的标签如果是一个块级标签，该标签还是会缩进的，浏览器中的`img`标签应该是行内标签，所以不会缩进，但是img组件还可以设置宽高，在插件中是设置为`display:inline-block`的，所以还是被缩进了，这个问题，暂时好像无法解决
![3](https://user-images.githubusercontent.com/48236054/62784834-f6158180-baf1-11e9-9510-63f4851c7b95.png)

**Comment by bby0856** [comment]
嗯，谢谢您啦
