### ISSUE TITLE
uni-app 百度小程序安卓真机上循环富文本只显示第一个

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#160]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

不同于该issue：
在uni-app 安卓版 百度小程序上使用无效https://github.com/jin-yufeng/Parser/issues/139

**使用平台**  

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

uni-app 安卓真机上出现问题

**问题描述**  

[提示]: <> (请详细描述遇到的问题，最好附上截图)  
uni-app 百度小程序安卓真机上循环富文本只显示第一个
![image](https://user-images.githubusercontent.com/15627064/84748242-ef497c00-afea-11ea-8dba-76686940a8cc.png)

![image](https://user-images.githubusercontent.com/15627064/84748277-fcff0180-afea-11ea-99aa-aad14fb3793f.png)

![image](https://user-images.githubusercontent.com/15627064/84748410-30da2700-afeb-11ea-8eee-0b1dd9d99f69.png)

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码或附件)  

```html
<view class="text_list" v-for="(item, index) in textList">
			<jyf-parser :ref="'textModule'+item.id" :html="item.des"></jyf-parser>
		</view>

textList: [
					{
						id:1,
						des:"循环文本1"
					},
					{
						id:2,
						des:"循环文本2"
					},
					{
						id:3,
						des:"循环文本3"
					}
				]
```

**Comment by jin-yufeng** [comment]
百度真机为什么有这么多奇奇怪怪的问题😂

**Comment by macanfa108** [comment]
同感，百度本身就很坑，经常开发工具和真机效果差异很大，还没有报错
这个问题比较紧急，但难以排查到中间是哪里出问题了

**Comment by jin-yufeng** [comment]
加我 qq 吧，2247603352，我没有百度账号需要你帮忙调试一下

**Comment by macanfa108** [comment]
情况1：如果是单纯纯文本循环渲染，在安卓真机上传入trees.vue的数据会缺失部分key导致渲染失效
![~HG SFHP8L7XJ008RKD J0Y](https://user-images.githubusercontent.com/15627064/84885348-7ec35d80-b0c5-11ea-9612-7a05478abfbc.png)

处理方案：
![~3TSHTYL}6~3Y)RDG7V Z6J](https://user-images.githubusercontent.com/15627064/84884590-86363700-b0c4-11ea-8529-52275e2e88d1.png)



情况2：循环渲染的不止是纯文本，可能是以下这类的文本，会出现以上同样的问题导致渲染失效:
`"<div>循环文本1</div>"`
问题原因：
安卓真机和开发工具调试数据对比：发现真机上数据部分属性缺失
![CP5%QYL9%P8 UUA{HO%KN66(1)](https://user-images.githubusercontent.com/15627064/84884287-1aec6500-b0c4-11ea-8e3f-ad3016b321ce.jpg)

处理方案：
只在这层深拷贝即可处理问题，对于每个富文本模块只拷贝一次，这种开销相对比较小点
微信端、百度端、字节端 （ios和安卓）真机测试都通过
![T{LMHV{TW66 HX% N$XCBUV](https://user-images.githubusercontent.com/15627064/84885404-96024b00-b0c5-11ea-9fd3-2eab001c9a40.png)


猜想原因：
uniapp在setData的时候会做diff，仅设置更新了的数据，因为某种bug（没有隔离），后面设置nodes的时候会和前一个组件的nodes进行diff，然后相同的部分就不进行设置，所以会出现一开始那个type没了（两个type是一样的，但text是不一样的），然后后面加上div后name没了（name是一样的，都是div）
 那个数组变成对象可能也是因为diff的时候发现第0项type是一样的，text是不一样的，所以把0的text进行设置，然后就变成了的这样

**Comment by chenzefeng09** [comment]
同进这个坑了，感谢  @macanfa108
