### ISSUE TITLE
小程序table标签中的图片不显示

### ISSUE THREAD

**Issue by sknosh** [jin-yufeng/Parser#162]
**使用平台**  

微信小程序

**问题描述**  
预期显示table标签里的图片，实际没有
预期：
![image](https://user-images.githubusercontent.com/36500982/84970856-19677f00-b14e-11ea-8aa9-8e8ad623a091.png)
实际|：
![image](https://user-images.githubusercontent.com/36500982/84970894-297f5e80-b14e-11ea-8c57-6452a397aee1.png)

**html 代码**  

https://github.com/sknosh/parser/blob/master/parser.html

**Comment by jin-yufeng** [comment]
这个 `background` 属性还不支持的，可以先在 `config.js` 里的 `filter` 中自行处理一下  
![微信截图_20200618104651](https://user-images.githubusercontent.com/48236054/84972409-5ed97b80-b151-11ea-8b11-4d0b70088039.png)

```javascript
filter(node) {
  if (node.attrs.background)
    node.attrs.style += ';background-image:url(' + node.attrs.background + ')'
}
```

**Comment by sknosh** [comment]
background好像没有在node.attrs里：
![image](https://user-images.githubusercontent.com/36500982/84973774-7b2ae780-b154-11ea-94dc-45578aac0adc.png)

**Comment by sknosh** [comment]
原本属性是这样的：
![image](https://user-images.githubusercontent.com/36500982/84973858-ae6d7680-b154-11ea-8099-10fc4fa2278f.png)

**Comment by jin-yufeng** [comment]
是不是不是最新版，那还要把 `background` 加到 `config.js` 的 `trustAttrs` 里

**Comment by sknosh** [comment]
可以了，谢谢
