### ISSUE TITLE
现在编译会出现bug了

### ISSUE THREAD

**Issue by a822193948** [jin-yufeng/Parser#165]
在APP平台上现在会出现 TypeError: Invalid attempt to destructure non-iterable instance.In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

**Comment by a822193948** [comment]
在APP平台上现在会出现 TypeError: Invalid attempt to destructure non-iterable instance.In order to be iterable, non-array objects must have a Symbol.iterator method.然后图片无法显示

**Comment by jin-yufeng** [comment]
`HBuilder X` 版本？
用示例项目试过吗
