### ISSUE TITLE
全局图片禁用点击放大及gallery浏览

### ISSUE THREAD

**Issue by tausi0661** [jin-yufeng/Parser#166]
默认的解析是图片等资源可以点击放大, 可以滑动浏览. 可否设置全局变量禁用此功能? 一方面是现实需求. 另外如果禁用此表现是否可以一定程度上减少生成的节点数从而提高性能?

(看到可以在图片上设置ignore标签来实现, 但一方面图片很多的话需要逐个设置. 另一方面html文本是由不懂代码的人员通过富文本编辑器生成, 这部分人肯定也不太会直接编辑html)

**Comment by jin-yufeng** [comment]
如果只是需要在功能上禁止预览的话，在 `imgtap` 事件里调用 `ignore` 方法也可以实现的，不过这种方法图片还是都暴露出来了，没有减少节点数，从提升性能的角度来说，确实需要这样一个配置

**Comment by jin-yufeng** [comment]
不过如果不把图片暴露出来，懒加载、加载和出错时的占位图全都会失效，会带来一些额外的问题
所以还是通过 `ignore` 方法来禁用预览吧（详见 [禁用自动预览](https://jin-yufeng.github.io/Parser/#/question?id=%e6%97%a0%e6%b3%95%e7%a6%81%e7%94%a8%e8%87%aa%e5%8a%a8%e9%a2%84%e8%a7%88-%e8%b7%b3%e8%bd%ac)）
