### ISSUE TITLE
大佬为啥在h5端不能双指缩放图片，app和小程序就可以

### ISSUE THREAD

**Issue by zyellen** [jin-yufeng/Parser#167]
为啥在h5端不能双指缩放图片，app和小程序就可以啊，自己捣鼓了好久没搞明白

**Comment by jin-yufeng** [comment]
这个是 `uni.previewImage` 不同平台的表现差异，`H5` 要用双指缩放的话要自己通过别的方式实现，比如调用微信 `jssdk` 的 `previewImage` 之类的  
![微信截图_20200701164615](https://user-images.githubusercontent.com/48236054/86223663-6883ca00-bbba-11ea-9602-d2ea35ef6142.png)

**Comment by zyellen** [comment]
谢谢大佬，用wx的确实可以
