### ISSUE TITLE
imgtap 事件返回值有问题，只返回了一个图片地址，没有object其他属性

### ISSUE THREAD

**Issue by linfei721** [jin-yufeng/Parser#169]
![image](https://user-images.githubusercontent.com/4755456/86898080-d12ef180-c13a-11ea-93e5-e3e177afc124.png)

**Comment by jin-yufeng** [comment]
这是 `H5` 么？`console.log` 一下 `e.src` 和 `e.ignore` 应该都是有的吧

**Comment by linfei721** [comment]
> 这是`H5`么？`console.log`一下`e.src`和`e.ignore`应该都是有的吧

嗯，h5的，没有src和ignore，那个对象就返回一个字符串，e.src会报错

**Comment by jin-yufeng** [comment]
什么浏览器？我这里有的  
![微信截图_20200709001313](https://user-images.githubusercontent.com/48236054/86943440-0a865200-c179-11ea-809f-db545d387636.png)
![微信截图_20200709001326](https://user-images.githubusercontent.com/48236054/86943474-13772380-c179-11ea-8d8e-3826c4d36a1b.png)

**Comment by linfei721** [comment]
> 什么浏览器？我这里有的
> ![微信截图_20200709001313](https://user-images.githubusercontent.com/48236054/86943440-0a865200-c179-11ea-809f-db545d387636.png)
> ![微信截图_20200709001326](https://user-images.githubusercontent.com/48236054/86943474-13772380-c179-11ea-8d8e-3826c4d36a1b.png)

确实有，我之前可能看错了，不好意思
