### ISSUE TITLE
请问在 Mpvue 中如何使用，能否给个例子？

### ISSUE THREAD

**Issue by zaxlct** [jin-yufeng/Parser#17]
**问题描述**
Taro 都有 demo了，MPVUE 没有吗   = =!
**预期的表现**
请描述预期的表现

**实际的表现**
请描述实际的表现

**html代码**
请附上出现问题的html代码，例如：
`<div>Hello World!</div>`

**Comment by zaxlct** [comment]
尝试直接在 mpvue 中引用，结果报错 
`Component is not found in path "static/Parse/index"`

**Comment by jin-yufeng** [comment]
好像还真没有😂你先研究研究，适配成功了的话就有了

**Comment by jin-yufeng** [comment]
mpVue有demo了哦，参考[https://github.com/jin-yufeng/Parser_mpVue](https://github.com/jin-yufeng/Parser_mpVue)  
这里是不是文件没引入

**Comment by wlor0623** [comment]
你好 遇到了同样的问题 请问怎么解决的?

**Comment by jin-yufeng** [comment]
@wlor0623 参考 [在 mpVue 中使用](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9c%a8-mpvue-%e4%b8%ad%e4%bd%bf%e7%94%a8) 无法解决吗？
