### ISSUE TITLE
渲染富文本图片时出现异常  每张图片后面都有一张空白图片

### ISSUE THREAD

**Issue by MrSupW** [jin-yufeng/Parser#170]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信

**问题描述**

*渲染富文本图片时出现异常  一张图片后面都有一张空白图片*

**Comment by jin-yufeng** [comment]
截个图看看？

**Comment by MrSupW** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jin-yufeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月9日(星期四) 晚上6:32
收件人:&nbsp;"jin-yufeng/Parser"<Parser@noreply.github.com&gt;;
抄送:&nbsp;"HalfDay"<1402036111@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jin-yufeng/Parser] 渲染富文本图片时出现异常  每张图片后面都有一张空白图片 (#170)





 
截个图看看？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


比如上图中 其实是应该只有一张图片的 但是多出现了一张空白图像



这个我代码标注的图片有没有办法去掉呢？&nbsp; 因为它加载不出来 只会占位置&nbsp;

我尝试过用 wxss将其display置为none&nbsp; 但是这样设置任然不行&nbsp;

**Comment by jin-yufeng** [comment]
没有看到图，传入的 `html` 是什么？

**Comment by Ys365** [comment]
nvue 图片一直闪加载完成后就空白了

**Comment by jin-yufeng** [comment]
> nvue 图片一直闪加载完成后就空白了

如何复现，用示例项目有这个问题吗？

**Comment by Ys365** [comment]
偶尔会出现，多图的时候或者一张图偶尔就会闪，闪完了就什么内容都没有了，应该还是哪里有Bug，可以排查一下，插件非常好用。

**Comment by jin-yufeng** [comment]
> 偶尔会出现，多图的时候或者一张图偶尔就会闪，闪完了就什么内容都没有了，应该还是哪里有Bug，可以排查一下，插件非常好用。

是不是多次设置数据的时候会出现闪烁？是的话换上这个 [jyf-parser.vue](https://github.com/jin-yufeng/Parser/blob/develop/parser.uni/jyf-parser.vue) 试一下
