### ISSUE TITLE
针对自定义组件是否可以设置信任之后原封不动的渲染出来

### ISSUE THREAD

**Issue by zhangyq233** [jin-yufeng/Parser#173]
**新功能描述**  

[提示]: <> (描述需要的功能或改进建议)  

针对自定义组件是否可以设置信任之后原封不动的渲染出来，现有这种模式因为还要涉及到取attr的值等麻烦的操作，所以想说可不可以直接原封不动的渲染出来，类似插槽那种，谢谢。

**应用场景**  

[提示]: <> (描述该新功能的应用场景)

**Comment by jin-yufeng** [comment]
原封不动的渲染出来指的是什么？像 `H5` 里那样？但是小程序里不支持 `html` 的标签，必须要先进行解析，进行适当转换后用小程序的标签进行模拟
