### ISSUE TITLE
微信小程序中通过 npm 引入 parser-wx，页面使用时报错

### ISSUE THREAD

**Issue by fanxiaocong** [jin-yufeng/Parser#174]
### 通过 npm 引入 parser-wx 后，按照文档上提供的方式在页面上使用 parser 是报错：

<img width="910" alt="image" src="https://user-images.githubusercontent.com/17899215/88000832-3f0eec00-cb31-11ea-8055-7dece7500bfb.png">

wxml 文件内容：
```
<view class="container">
    <parser html="{{html}}" />
</view>
```

js文件内容：
```js
  data: {
    html: '<div>Hello World!</div>'
  },
```

json文件内容：
```json
{
  "usingComponents": {
    "parser": "parser-wx"
  }
}
```

项目工程目录：
<img width="214" alt="image" src="https://user-images.githubusercontent.com/17899215/88001104-e724b500-cb31-11ea-8bb5-f58c51d7e860.png">

**Comment by fanxiaocong** [comment]
问题已经解决，需要将 json 文件中的组件路径地址修改一下：

json文件内容：
```json
{
  "usingComponents": {
    "parser": "parser-wx/index"
  }
}
```

**Comment by jin-yufeng** [comment]
![微信截图_20200721091808](https://user-images.githubusercontent.com/48236054/88001619-27386780-cb33-11ea-8c9b-d1abf53088b8.png)
官方文档里说只引入包名会默认寻找包内的 `index` 组件的，我这里是不加 `/index` 就可以的，难道是工具版本问题哈哈哈，遇到这个问题就加上吧

**Comment by fanxiaocong** [comment]
嗯，刚刚确认了一下，是我这边的问题，项目配置中没有把 `使用 npm 模块` 给勾上，现在勾上后不加 `/index` 也可以了，感谢！
