### ISSUE TITLE
mpvue中使用parser插件抛错

### ISSUE THREAD

**Issue by haryzxw** [jin-yufeng/Parser#175]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

微信  

**问题描述**  

按照mpvue的使用步骤，将parser包添加到static下，并在.json文件做了配置，在.vue中使用的时候，抛了截图的错误，有空能帮我看看嘛～
![image](https://user-images.githubusercontent.com/28974350/88267953-2efb3600-cd04-11ea-9068-a0e91cb952de.png)

**html 代码**  
![image](https://user-images.githubusercontent.com/28974350/88267965-34588080-cd04-11ea-92b4-5e5d49073b86.png)
![image](https://user-images.githubusercontent.com/28974350/88267968-36224400-cd04-11ea-85a0-529971e45095.png)
![image](https://user-images.githubusercontent.com/28974350/88267973-38849e00-cd04-11ea-9b37-5513710e94c4.png)

**Comment by jin-yufeng** [comment]
确定放在 `static` 目录下了么，试试这个 [mpvue-demo.zip](https://github.com/jin-yufeng/Parser/files/4965702/mpvue-demo.zip)

**Comment by haryzxw** [comment]
嗯嗯，谢谢～我试试看



            
            
                
                    
                            
                                
                            
                            
                                郑晓雯
                            
                    
                        
                            
                                    邮箱：hary@cingta.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


            在2020年07月23日 20:01，jin-yufeng 写道： 

确定放在 static 目录下了么，试试这个 mpvue-demo.zip



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jin-yufeng/Parser/issues/175#issuecomment-662966745",

"url": "https://github.com/jin-yufeng/Parser/issues/175#issuecomment-662966745",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by haryzxw** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，这个插件对mpvue的版本有要求，我跑了你给的demo，是可以正常渲染的。但是我自己项目里还是没办法渲染，mpvue的版本为：1.0.6；你的demo版本：2.0.0项目使用截图如下：望回复～
    
        
            
        
    
    
      
    
 
    在2020年07月23日 20:01，jin-yufeng<notifications@github.com> 写道： 




确定放在 static 目录下了么，试试这个 mpvue-demo.zip

**Comment by jin-yufeng** [comment]
这是 `1.0.6` 的 [demo.zip](https://github.com/jin-yufeng/Parser/files/4970814/demo.zip)，我感觉的差别就是 `1.0.6` 好像不会自动把 `src` 目录下 `page` 中的 `json` 拷贝到 `dist` 中，需要直接添加到 `dist` 中去，其他好像没啥差别

**Comment by haryzxw** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    嗯嗯，感谢百忙之中回复！我再用你demo试试看我本来也是想实在不行就把mpvue升级到2.0.0或者直接套用你的demo包本来项目最开始使用的是微信rich-text，但当时好像不支持表格合并单元格的情况（colspan、rowspan等属性）后来改用mpvue-wxparse，但这个插件在富文本内容多的时候，就容易造成小程序的假死卡顿，很无奈现在就想尝试使用你写的这个框架～
    希望顺利，祝你一切安好！
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                郑晓雯
                            
                    
                        
                            
                                    hary@cingta.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年07月24日 16:06，jin-yufeng<notifications@github.com> 写道： 




这是 1.0.6 的 demo.zip，我感觉的差别就是 1.0.6 好像不会自动把 src 目录下 page 中的 json 拷贝到 dist 中，需要直接添加到 dist 中去，其他好像没啥差别



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
