### ISSUE TITLE
taro 微信小程序  多张图片上下之间有10px的间隔

### ISSUE THREAD

**Issue by ywanhzy** [jin-yufeng/Parser#176]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
taro  微信小程序
[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  
多张图片上下之间有10px的间隔
[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码或附件)  

```html

```

**Comment by jin-yufeng** [comment]
[图片间隙问题](https://jin-yufeng.github.io/Parser/#/question?id=%e8%bf%9e%e7%bb%ad%e5%9b%be%e7%89%87%e9%97%b4%e6%9c%89%e9%97%b4%e9%9a%99)

**Comment by ywanhzy** [comment]
谢谢  问题解决
