### ISSUE TITLE
请问Cocos开发的微信小游戏能用吗？有使用方法吗？

### ISSUE THREAD

**Issue by martianma** [jin-yufeng/Parser#177]
**新功能描述**  

[提示]: <> (描述需要的功能或改进建议)  

**应用场景**  

[提示]: <> (描述该新功能的应用场景)

**Comment by jin-yufeng** [comment]
没接触过小游戏，目前没有使用方法，不确定能不能用，可以自行探索一下

**Comment by jin-yufeng** [comment]
小游戏里好像连组件都没有，和小程序差距很大，应该没法用的
