### ISSUE TITLE
图片不居中，且图片下方有很大一块空白。

### ISSUE THREAD

**Issue by wuliaolll** [jin-yufeng/Parser#178]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

微信

**问题描述**  

图片不居中，且图片下方有很大一块空白。
![QQ图片20200729080532](https://user-images.githubusercontent.com/9691107/88741549-84a36880-d172-11ea-833b-48cef52e7beb.png)

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html
要解析的html如下：

<div class=\"view TRS_UEDITOR trs_paper_default trs_web\"><p style=\"text-indent: 2em; text-align: center;\"><strong>应勇赴监利洪湖检查指导防汛救灾工作<\/strong><\/p><p style=\"text-indent: 2em; text-align: center;\"><strong>抓实抓细防汛救灾各项措施<\/strong><\/p><p style=\"text-indent: 2em; text-align: center;\"><strong>确保大江大河大湖大库安全度汛<\/strong><\/p><p style=\"text-indent: 2em;\">万里长江，险在荆江。“七下八上”是长江防汛的关键期，长江第2号洪水即将通过荆州段。7月21日，省委书记、省防汛抗旱指挥部指挥长应勇深入监利市、洪湖市的长江大堤、排水泵站、湖堤险段、受灾群众转移安置点，检查指导防汛救灾工作。应勇强调，要深入贯彻落实习近平总书记关于防汛救灾的重要讲话和重要指示批示精神，牢固树立人民至上、生命至上的理念，始终把保障人民生命财产安全放在第一位，抓实抓细防汛救灾各项措施。要进一步加强重要堤防、重点部位、重点工程、重要设施查险排险，科学调度，严防死守，确保大江大河大湖大库安全度汛。各级党委政府特别是领导干部要深入一线、靠前指挥，守土有责、守土负责、守土尽责。要充分发挥基层党组织和党员干部的战斗堡垒作用和先锋模范作用，让党旗在防汛救灾第一线高高飘扬。确保长江干堤万无一失是必须守住的底线。长江监利白螺段堤防是江汉平原的重要防洪屏障，7月6日以来该堤段持续高水位运行。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813639087084.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813639087084.jpg\" \/><\/p><p style=\"text-indent: 2em; text-align: left;\">应勇走上长江大堤，听取荆江、洞庭湖防洪工程情况汇报；登上白螺石化码头，察看水情汛情，详细了解长江上游来水流量和水位等情况；走进防守哨棚，慰问正在值守的干部、群众。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813641542102.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813641542102.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇强调，湖北是长江径流里程最长的省份，确保长江干堤安全责任重于泰山。要做好水位实时监测和分析研判，确保预警预报精准到位，把握防汛救灾主动权；要强化底线思维，备足备齐防汛救灾物资，宁可备而不用、不可用时无备。监利白螺镇联盟村临近长江大堤的水稻田曾出现多处冒气泡异常现象，目前已采取回填、蓄水反压等处置措施。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813643687621.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813643687621.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇实地察看隐患，听取处置情况介绍。他强调，防汛是天大的事，决不能有丝毫麻痹大意。要用好“显微镜”，及时排查消除潜在的风险隐患，把任何一处风险当作重大险情来对待，确保风险不演变成隐患、隐患不演变成事故；要紧盯险工险段和易出险区域，加大巡堤查险力度，确保险情早发现、早处置、早化解。四湖流域地处江汉平原腹地，是我省重要的农业生产基地。位于洪湖市境内的新滩口泵站是四湖流域下游排水进入长江的总出口，入汛以来泵站已连续运行6000多个小时。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813645205947.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813645205947.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇在新滩口泵站听取四湖流域水利治理情况介绍，察看泵站机组运行情况。应勇强调，水利工程对减轻防洪压力起着关键作用。要统筹长江防汛与四湖流域综合治理、荆南四河堤防加固，提高四湖流域等地区洪涝灾害防御能力。要坚持以防为主、防抗救相结合，加快实施一批高标准的打基础、补短板、强功能、利长远的水利工程项目，提升水利治理体系和治理能力现代化水平。洪湖7月12日以来一直超保证水位运行，当日中午达到27.20米，超过历史最高纪录。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813647588374.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813647588374.jpg\" \/><\/p><p style=\"text-indent: 2em;\">中部战区副司令员张义瑚、副参谋长邓玉恩和省军区司令员马涛正指挥解放军指战员、民兵预备役人员，与广大干群一起，在洪湖围堤花园段加固堤防。应勇代表省委省政府和全省人民向参与防汛救灾的人民子弟兵致以崇高敬意！勉励当地民兵发扬洪湖赤卫队精神，守牢堤坝、保护家乡。大堤上红底黄字的防守责任牌上，刻写着“誓与大堤共存亡”的铿锵誓言，市镇村三级责任干部以及工程技术人员、守险劳力姓名一一标注，应勇鼓励大家再接再厉，守住不垮一堤、不溃一垸、不亡一人的底线。<\/p><p style=\"text-indent: 2em;\">因湖水漫溢，洪湖市螺山镇杨柴湖村200多名村民被转移安置在螺山小学。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813649892054.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813649892054.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇与受灾群众并肩而坐，关切询问他们吃住情况和家庭受灾情况，鼓励大家坚定信心、共渡难关。看望安置点下沉警务人员和医务人员，要求继续做好出入登记、健康体检和防疫消杀工作；走进食堂，察看饮食安排。应勇强调，要妥善安排好受灾群众基本生活，确保安置点食品和饮用水卫生、安全；做好洪水消退后的环境消杀等工作，有序组织村民安全返家，精心组织灾后重建和农业生产自救；做好困难群众帮扶救助，防止因灾致贫返贫。<\/p><p style=\"text-indent: 2em;\">副省长万勇参加检查。（李保林、周呈思、陈迹）<\/p><\/div>

```

**Comment by jin-yufeng** [comment]
我放在示例项目里显示是这样的，请提供一个能复现的 `demo` 项目
![微信截图_20200729083152](https://user-images.githubusercontent.com/48236054/88742922-05b02f00-d176-11ea-8252-9de9eee63860.png)
至于图片没有居中是因为图片大小本来就放满整个屏幕了，加上设置了 `text-indent:2em` 的缩进，前面就又空了一块，这个运行到 `H5` 直接通过浏览器显示也是这样的
![微信截图_20200729083614](https://user-images.githubusercontent.com/48236054/88743336-fed5ec00-d176-11ea-9b48-357421eb8d0e.png)

**Comment by wuliaolll** [comment]
> 我放在示例项目里显示是这样的，请提供一个能复现的 `demo` 项目
> ![微信截图_20200729083152](https://user-images.githubusercontent.com/48236054/88742922-05b02f00-d176-11ea-8252-9de9eee63860.png)
> 至于图片没有居中是因为图片大小本来就放满整个屏幕了，加上设置了 `text-indent:2em` 的缩进，前面就又空了一块，这个运行到 `H5` 直接通过浏览器显示也是这样的
> ![微信截图_20200729083614](https://user-images.githubusercontent.com/48236054/88743336-fed5ec00-d176-11ea-9b48-357421eb8d0e.png)

我去掉._img 的display: inline-block; 
._image加上display:none;
就好了。

就是个普通的vue页面。

`<template>
	<view>
		<view class="article-area">
			<view class="article-title">
				<text>{{title}}</text>
			</view>
			<view class="article-content">
				<jyf-parser :html="html" ref="article" :selectable="true" @error="error"></jyf-parser>
			</view>
		</view>
	</view>
</template>

<script>
	import jyfParser from "@/components/jyf-parser/jyf-parser"
	
	export default {
		components: {
		    jyfParser
		},
		data() {
			return {
				title:"",
				html:""
			}
		},
		onLoad(event) {
			this.html = "<div class=\"view TRS_UEDITOR trs_paper_default trs_web\"><p style=\"text-indent: 2em; text-align: center;\"><strong>应勇赴监利洪湖检查指导防汛救灾工作<\/strong><\/p><p style=\"text-indent: 2em; text-align: center;\"><strong>抓实抓细防汛救灾各项措施<\/strong><\/p><p style=\"text-indent: 2em; text-align: center;\"><strong>确保大江大河大湖大库安全度汛<\/strong><\/p><p style=\"text-indent: 2em;\">万里长江，险在荆江。“七下八上”是长江防汛的关键期，长江第2号洪水即将通过荆州段。7月21日，省委书记、省防汛抗旱指挥部指挥长应勇深入监利市、洪湖市的长江大堤、排水泵站、湖堤险段、受灾群众转移安置点，检查指导防汛救灾工作。应勇强调，要深入贯彻落实习近平总书记关于防汛救灾的重要讲话和重要指示批示精神，牢固树立人民至上、生命至上的理念，始终把保障人民生命财产安全放在第一位，抓实抓细防汛救灾各项措施。要进一步加强重要堤防、重点部位、重点工程、重要设施查险排险，科学调度，严防死守，确保大江大河大湖大库安全度汛。各级党委政府特别是领导干部要深入一线、靠前指挥，守土有责、守土负责、守土尽责。要充分发挥基层党组织和党员干部的战斗堡垒作用和先锋模范作用，让党旗在防汛救灾第一线高高飘扬。确保长江干堤万无一失是必须守住的底线。长江监利白螺段堤防是江汉平原的重要防洪屏障，7月6日以来该堤段持续高水位运行。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813639087084.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813639087084.jpg\" \/><\/p><p style=\"text-indent: 2em; text-align: left;\">应勇走上长江大堤，听取荆江、洞庭湖防洪工程情况汇报；登上白螺石化码头，察看水情汛情，详细了解长江上游来水流量和水位等情况；走进防守哨棚，慰问正在值守的干部、群众。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813641542102.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813641542102.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇强调，湖北是长江径流里程最长的省份，确保长江干堤安全责任重于泰山。要做好水位实时监测和分析研判，确保预警预报精准到位，把握防汛救灾主动权；要强化底线思维，备足备齐防汛救灾物资，宁可备而不用、不可用时无备。监利白螺镇联盟村临近长江大堤的水稻田曾出现多处冒气泡异常现象，目前已采取回填、蓄水反压等处置措施。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813643687621.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813643687621.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇实地察看隐患，听取处置情况介绍。他强调，防汛是天大的事，决不能有丝毫麻痹大意。要用好“显微镜”，及时排查消除潜在的风险隐患，把任何一处风险当作重大险情来对待，确保风险不演变成隐患、隐患不演变成事故；要紧盯险工险段和易出险区域，加大巡堤查险力度，确保险情早发现、早处置、早化解。四湖流域地处江汉平原腹地，是我省重要的农业生产基地。位于洪湖市境内的新滩口泵站是四湖流域下游排水进入长江的总出口，入汛以来泵站已连续运行6000多个小时。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813645205947.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813645205947.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇在新滩口泵站听取四湖流域水利治理情况介绍，察看泵站机组运行情况。应勇强调，水利工程对减轻防洪压力起着关键作用。要统筹长江防汛与四湖流域综合治理、荆南四河堤防加固，提高四湖流域等地区洪涝灾害防御能力。要坚持以防为主、防抗救相结合，加快实施一批高标准的打基础、补短板、强功能、利长远的水利工程项目，提升水利治理体系和治理能力现代化水平。洪湖7月12日以来一直超保证水位运行，当日中午达到27.20米，超过历史最高纪录。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813647588374.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813647588374.jpg\" \/><\/p><p style=\"text-indent: 2em;\">中部战区副司令员张义瑚、副参谋长邓玉恩和省军区司令员马涛正指挥解放军指战员、民兵预备役人员，与广大干群一起，在洪湖围堤花园段加固堤防。应勇代表省委省政府和全省人民向参与防汛救灾的人民子弟兵致以崇高敬意！勉励当地民兵发扬洪湖赤卫队精神，守牢堤坝、保护家乡。大堤上红底黄字的防守责任牌上，刻写着“誓与大堤共存亡”的铿锵誓言，市镇村三级责任干部以及工程技术人员、守险劳力姓名一一标注，应勇鼓励大家再接再厉，守住不垮一堤、不溃一垸、不亡一人的底线。<\/p><p style=\"text-indent: 2em;\">因湖水漫溢，洪湖市螺山镇杨柴湖村200多名村民被转移安置在螺山小学。<\/p><p style=\"text-indent: 2em; text-align: center;\"><img src=\"http:\/\/www.hubei.gov.cn\/zwgk\/hbyw\/hbywqb\/202007\/W020200721813649892054.jpg\" title=\"\" alt=\"\" picname=\"\" OLDSRC=\"W020200721813649892054.jpg\" \/><\/p><p style=\"text-indent: 2em;\">应勇与受灾群众并肩而坐，关切询问他们吃住情况和家庭受灾情况，鼓励大家坚定信心、共渡难关。看望安置点下沉警务人员和医务人员，要求继续做好出入登记、健康体检和防疫消杀工作；走进食堂，察看饮食安排。应勇强调，要妥善安排好受灾群众基本生活，确保安置点食品和饮用水卫生、安全；做好洪水消退后的环境消杀等工作，有序组织村民安全返家，精心组织灾后重建和农业生产自救；做好困难群众帮扶救助，防止因灾致贫返贫。<\/p><p style=\"text-indent: 2em;\">副省长万勇参加检查。（李保林、周呈思、陈迹）<\/p><\/div>";
		},
		methods:{
			navLeftAction() {
				uni.navigateBack({
					
				})
			},
			error(e) {
				console.error(e);
			}
		}
		
	}
</script>

<style>
	
	/* #ifndef APP-PLUS */
	page {
		min-height: 100%;
	}
	/* #endif */
	.article-area{padding-left: 30rpx;padding-right: 30rpx;}
	.article-title {margin-bottom: 40rpx;font-weight: bold;line-height: 1.2;font-size: 42rpx;margin-top: 20rpx;}
	
</style>
`

**Comment by wuliaolll** [comment]
知道原因了，我在全局样式里写了个
image{margin:0px auto}导致图片下方有空白。

但是text-index:2em造成图片不居中的问题是编辑器导致的，这个要解决要么就把image变为block，要么就要代码去掉图片外层的缩进了。
