### ISSUE TITLE
出现部分没有添加TagStyle，或者没加成功

### ISSUE THREAD

**Issue by hellozhang** [jin-yufeng/Parser#179]
![image](https://user-images.githubusercontent.com/6902549/89245104-ad2bd680-d63a-11ea-8ce1-6c62479aef39.png)

自定义样式
  p: 'line-height:20px;font-size:12px;text-indent:0em;',

**Comment by hellozhang** [comment]
![image](https://user-images.githubusercontent.com/6902549/89245243-fd0a9d80-d63a-11ea-9c79-5fbc1c86e0c9.png)

**Comment by jin-yufeng** [comment]
你的截图里也没看出什么问题啊
