### ISSUE TITLE
关于支持解析<style>标签中的全局样式

### ISSUE THREAD

**Issue by markbzhang** [jin-yufeng/Parser#18]
**问题描述**
我是将<style>XXXXXX</style> 的样式加在  <Parser html="{{body}}"  /> 里面的body变量里面，body是 自身的一些样式，再加后台的富文本html，一起的 字符串。

**预期的表现**
想<style>里面的一些class样式 作用于 富文本

**实际的表现**
但是实际不起作用

请问是我使用的方式问题吗？还是哪里出错了？

**Comment by jin-yufeng** [comment]
是类似这个样子吗？
```javascript
var body="<style>.a{text-align:center;}</style>";
body=body+"<div class=\"a\">Hello World!</div>"
this.setData({
  body
})
```
```html
<Parser html="{{body}}" />
```
我试了以下这样是可以生效的，你具体是怎么写的
