### ISSUE TITLE
图片之间会有间隔

### ISSUE THREAD

**Issue by gaoyong06** [jin-yufeng/Parser#180]
**使用平台**  

微信小程序

**问题描述**  

HTML代码类似：`<img src="..."></img><img src="..."></img><img src="..."></img>`
在浏览器里面显示是正常的，每个图都是紧挨在一起，没有缝隙。但是在小程序上使用
Parse就没法紧贴在一起，期望可以紧贴在一起展示

因为需求上有一些类似拼接图的东西，如果有缝隙，没有紧贴就显示错误了

![小程序上显示](https://user-images.githubusercontent.com/1861256/89599458-325cf880-d892-11ea-8107-af43c7f4271b.PNG)
![浏览器上显示](https://user-images.githubusercontent.com/1861256/89599470-3ab53380-d892-11ea-8a1a-ce25e61512d0.png)

**html 代码**  

```html

<img src="https://wx2.sinaimg.cn/mw690/723dd72fgy1ghgb8jzjluj22yo3viqve.jpg"/><img src="https://wx2.sinaimg.cn/mw690/723dd72fgy1ghgb8t3gbsj22yo3vikjr.jpg"/><img src="https://wx1.sinaimg.cn/mw690/723dd72fgy1ghgb8zr2h1j22yo3vib2f.jpg"/>

```

**Comment by jin-yufeng** [comment]
[图片间隙问题](https://jin-yufeng.github.io/Parser/#/question?id=%e8%bf%9e%e7%bb%ad%e5%9b%be%e7%89%87%e9%97%b4%e6%9c%89%e9%97%b4%e9%9a%99)
