### ISSUE TITLE
多段P标签会合并成一个rech-text，导致无法设置段间距。

### ISSUE THREAD

**Issue by citrusjunoss** [jin-yufeng/Parser#181]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
微信

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  
![image](https://user-images.githubusercontent.com/18432488/89755870-74e13800-db13-11ea-932d-333b3128e7ae.png)
新闻类型的富文本要设置段落间间距。但是parser好像把这几个P标签都合并成一个了

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by citrusjunoss** [comment]
经测试假设多个P标签外层如果使用div包裹，就会合并。
直接最外层使用P标签不会合并

**Comment by jin-yufeng** [comment]
不是合并，只是这一块通过一个 `rich-text` 显示而已  
微信里的 `p` 标签默认不带间距的，可以自行设置一下，参考 #172

**Comment by citrusjunoss** [comment]
> 不是合并，只是这一块通过一个 `rich-text` 显示而已
> 微信里的 `p` 标签默认不带间距的，可以自行设置一下，参考 #172

ok
