### ISSUE TITLE
video不能跟随滚动

### ISSUE THREAD

**Issue by xgj1988** [jin-yufeng/Parser#183]
[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

uiapp做的android APP <video></video>导致在有滚动的界面，video标签不能跟随滚动，感觉像fixed了一样

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

无

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

无

**Comment by jin-yufeng** [comment]
录个屏看看？

**Comment by xgj1988** [comment]
[视频地址](https://oss.xyzy.online/video/d025d1f0-5d50-4e35-a44a-3cd6a498d64b.mp4)

**Comment by jin-yufeng** [comment]
`video` 是原生组件，不能嵌套在 `scroll-view` 中，去掉 `scroll-view` 应该就能滚动了，具体见 [原生组件说明](https://uniapp.dcloud.io/component/native-component?id=%e5%8e%9f%e7%94%9f%e7%bb%84%e4%bb%b6%e8%af%b4%e6%98%8e)  
用 `v-html` 能滚动应该是因为 `v-html` 用的是 `webview` 自带的 `video` 而不是原生的 `video`

**Comment by xgj1988** [comment]
没有其他办法吗

**Comment by xgj1988** [comment]
@jin-yufeng  而且用你现在这种方式，还必须要勾选videoplayer模块，不然还不行。

**Comment by jin-yufeng** [comment]
要播放视频只能用 `video` 标签，`uni-app` 里的 `video` 默认采用的就是原生组件，目前感觉没有别的办法
打包需不需要 `videoplayer` 我不太清楚，没试过
