### ISSUE TITLE
HTML如下，自定义样式无法起作用

### ISSUE THREAD

**Issue by hellozhang** [jin-yufeng/Parser#184]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  

[提示]: <> (请详细描述遇到的问题，最好附上截图)  
![image](https://user-images.githubusercontent.com/6902549/90109722-ce00d400-dd7e-11ea-9f53-f9cab69274a5.png)

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

<p style="text-align:left;text-indent:2em;"><span style="font-size:18px">1、打造全国百家国民营养健康城市品牌，千家国民营养健康社区，万家国民营养健康餐饮，国民营养健康学校，十万家国民营养健康家庭的目标。</span></p><p style="text-align:left;text-indent:2em;"><span style="font-size:18px">2、与各级政府单位共建国民营养健康城市品牌（国家营养健康城市，国民营养社区，国民营养健康餐饮，国民营养健康学校，国民营养家庭）。</span></p><p style="text-align:left;text-indent:2em;"><span style="font-size:18px">3、推动国民营养健康社区，国民营养健康学校，国民营养健康家庭发展，共享精准营养配餐技术，落实国民营养干预（慢病防控），塑造全民健康生活方式系统标杆。</span></p><p style="text-align:left;text-indent:2em;"><span style="font-size:18px">4、打造国民营养健康人才孵化IP，实施国民营养健康培训，科普教育，培养食育指导师、食品安全营养师、营养配餐师、家庭健康管理师。</span></p><p style="text-align:left;text-indent:2em;"><span style="font-size:18px">5、指导推动食品安全、营养健康技术应用发展与品牌申报。核心支持推广“零农残富硒食品技术”“智能餐厨垃圾生化机处理技术”“植物工厂流水线生产技术”“精准营养配餐技术”等。</span></p><p style="text-align:left;text-indent:2em;"><span style="font-size:18px">6、推进建立功能性食品研究（植物性和动物性营养功能研究、药食同源营养膳食研究）。</span></p>
```
使用这些自定义，无法覆盖样式！！！
 tagStyle: {
      p: 'line-height:12px;font-size:12px;text-indent:0em;',
      span: 'line-height:12px;font-size:12px;text-indent:0em;',
      strong: 'line-height:12px;font-size:12px;text-indent:0em;',
      text: 'line-height:12px;font-size:12px;text-indent:0em;',
      img: 'font-size:0;display:block;',
    }

**Comment by jin-yufeng** [comment]
`tag-style` 样式的优先级低于行内样式，优先级见 [优先级](https://jin-yufeng.github.io/Parser/#/?id=%e5%8c%b9%e9%85%8d-style-%e6%a0%87%e7%ad%be)  
`html` 里的 `span` 的 `style` 里都设置了 `font-size`，所以通过 `tag-style` 是覆盖不掉的，除非 `tag-style` 里的样式都加上 `!important`
