### ISSUE TITLE
无法播放url为 /mp/videoplayer 格式的视频

### ISSUE THREAD

**Issue by smalike** [jin-yufeng/Parser#186]
**使用平台**  
微信客户端

**问题描述**  
无法播放url为 /mp/videoplayer 格式的视频
如：/mp/videoplayer?video_h=380.8125&video_w=677&scene=&vid=wxv_1338167421408067585

**Comment by jin-yufeng** [comment]
1. 这个链接没有域名
2. 请确认这是 `video` 的链接而不是 `iframe` 的链接，小程序是不支持 `iframe` 的

**Comment by smalike** [comment]
> 1. 这个链接没有域名
> 2. 请确认这是 `video` 的链接而不是 `iframe` 的链接，小程序是不支持 `iframe` 的

视频的链接是这个：http://mpvideo.qpic.cn/0bf2muaacaaakuajvfv3abpfazodafsqaaia.f10002.mp4?dis_k=930a365d9161d132b55d6bb785134dd7&dis_t=1597971390

**Comment by jin-yufeng** [comment]
这个能播放啊

**Comment by smalike** [comment]
> 这个能播

**Comment by smalike** [comment]
> 这个能播放啊

这个视频地址能播放，但是根据iframe 获得vid后通过腾讯视频插件无法获得正确的视频地址。
iframe地址是这样的：/mp/videoplayer?video_h=380.8125&video_w=677&scene=&vid=wxv_1338167421408067585
这个vid和v.qq.com不一样 wxv_1338167421408067585

**Comment by smalike** [comment]
插件文档访问不到了 https://jin-yufeng.github.io/Parser/#/question?id=%e6%97%a0%e6%b3%95%e4%bd%bf%e7%94%a8-iframe-%e8%a7%86%e9%a2%91

**Comment by jin-yufeng** [comment]
这个文档地址访问不到？我这里是能访问的
![1](https://user-images.githubusercontent.com/48236054/90845060-e7fe7000-e397-11ea-90a0-c3f1f15c177f.png)

至于这个 `vid` 放在腾讯视频插件里能不能播放和本插件无关，需要自行检查（可能这个 `wxv` 开头的不是腾讯视频的 `vid`，我看到一个挺像的[问题](https://developers.weixin.qq.com/community/develop/doc/000c207f00cd4005992a9c11756400?highLine=https%253A%252F%252Fmp.weixin.qq.com%252Fmp%252Freadtemplate%253Ft%253Dpages%252Fvideo_player_tmpl%2526amp%253Baction%253Dmpvideo%2526amp%253Bauto%253D0%2526amp%253Bvid%253Dwxv_1477547383679959040)）

**Comment by smalike** [comment]
多谢
