### ISSUE TITLE
苹果手机长按文字不能复制

### ISSUE THREAD

**Issue by pinena** [jin-yufeng/Parser#187]
安卓手机正常，苹果手机长按文字没有反应

**Comment by jin-yufeng** [comment]
这是由这个 [官方 bug](https://developers.weixin.qq.com/community/develop/doc/00086ee03a0bd096595ac5e905ac00) 导致的，长按复制是通过 `css` 里的 `user-select:text` 实现的，但这个现在在 `ios` 上不可用，官方虽然修复了这个问题（用 `user-select` 属性替代），但这个属性只能用在 `text` 上，如何通过 `css` 实现还不清楚，所以暂时无法解决

**Comment by shiyuanjieyi** [comment]
可以通过改源码来实现长按复制

**Comment by jin-yufeng** [comment]
> 可以通过改源码来实现长按复制

怎么修改？

**Comment by shiyuanjieyi** [comment]
> > 可以通过改源码来实现长按复制
> 
> 怎么修改？

可以试试把这个整合进去
[select-text](https://developers.weixin.qq.com/miniprogram/dev/extended/component-plus/select-text.html)
