### ISSUE TITLE
img tag width attribute judge  polify

### ISSUE THREAD

**Issue by gexin1** [jin-yufeng/Parser#188]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  

**html 代码**  

```javascript
// parser.uni/libs/MpHtmlParser.js
//246
else if (attrs.width) width = attrs.width.includes('%') ? attrs.width : attrs.width + 'px';
// width    1em  1px  1% 1
else if (attrs.width) width = isNaN(+attrs.width)? attrs.width : attrs.width + 'px';
```

**Comment by gexin1** [comment]
打包用java 👍

**Comment by jin-yufeng** [comment]
`img` 的 `width` 属性只支持 `px` 为单位或百分数（参考 [w3school 链接](https://www.w3school.com.cn/tags/att_img_height-width.asp)）

**Comment by gexin1** [comment]
是的文档上是这样的   
```html
<img src="./1.jpg" width="250px">
<img src="./1.jpg" width="250em">
```
  也可以写这样google 浏览器渲染dom也是带单位的   实际渲染的时候浏览器会进行一次parseFloat 去掉'px'  'em'
 edge 渲染dom直接parseFloat

**Comment by jin-yufeng** [comment]
这里加个 `parseFloat` 是会更合理一点

**Comment by gexin1** [comment]
是的 刚才看的你的回复 我仔细去看了一下是这样的 
最上边的代码也是不够严谨的
