### ISSUE TITLE
audio扩展包无法后台播放音乐

### ISSUE THREAD

**Issue by WangJie-GetHub** [jin-yufeng/Parser#189]

**Comment by jin-yufeng** [comment]
`audio` 扩展包是用 [InnerAudioContext](https://developers.weixin.qq.com/miniprogram/dev/api/media/audio/wx.createInnerAudioContext.html) 实现的，你说的后台播放可能需要 [BackgroundAudioManager](https://developers.weixin.qq.com/miniprogram/dev/api/media/background-audio/wx.getBackgroundAudioManager.html)，不过这个是全局唯一的，还需要在 `app.json` 中配置，需要的话可以自行调整
