### ISSUE TITLE
无法渲染&#39;等字符

### ISSUE THREAD

**Issue by hangaoke1** [jin-yufeng/Parser#19]
**问题描述**
html转义后在经过组件渲染，无法正常显示，直接为空

**预期的表现**
正常显示，如 你好&#39； 显示 你好 '

**实际的表现**
直接为空，连你好也不显示

**html代码**
请附上出现问题的html代码，例如：
```js
const html = '你好&#39;'
render () {
  return <ParserRichText html={html} />
}
```

**Comment by jin-yufeng** [comment]
有bug，已经修好了，重新下载试一下

**Comment by hangaoke1** [comment]
@jin-yufeng 好的，感谢
