### ISSUE TITLE
希望可以支持wepy2

### ISSUE THREAD

**Issue by liangzhiyuan2015** [jin-yufeng/Parser#191]
**新功能描述**  

[提示]: <> 希望可以支持wepy2的富文本html解析

**应用场景**  

[提示]: <> wepy2环境下

**Comment by jin-yufeng** [comment]
[在 wepy 中使用](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9c%a8-wepy-%e4%b8%ad%e4%bd%bf%e7%94%a8)
