### ISSUE TITLE
Cannot read property 'height' of null

### ISSUE THREAD

**Issue by dyyliao123** [jin-yufeng/Parser#192]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  
![image](https://user-images.githubusercontent.com/25788204/92064259-b772f900-edcf-11ea-8e16-bded1ee401ba.png)
支付宝小程序
**问题描述**  

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
提供能复现问题的 `demo` 项目

**Comment by dyyliao123** [comment]
![image](https://user-images.githubusercontent.com/25788204/93765525-9e7b9c00-fc47-11ea-8360-2ecb1a726e3f.png)
我也遇到了

**Comment by dyyliao123** [comment]
有解决吗

**Comment by dyyliao123** [comment]
微信，和支付宝小程序都有报错

**Comment by jin-yufeng** [comment]
@dyyliao123 请提供能复现问题的 `demo` 项目

**Comment by dyyliao123** [comment]
![image](https://user-images.githubusercontent.com/25788204/93847296-278ee380-fcd9-11ea-8de2-2148f892bb1d.png)
![image](https://user-images.githubusercontent.com/25788204/93847365-52793780-fcd9-11ea-9ad7-06cc0cde7f94.png)
列表页面点击进来到详情页面，详情页面的数据通过接口拿的，所以加了一个loading，数据加载完成之后才渲染富文本的内容，
列表，详情页面来回切换，就会出现上面那个问题，我把loading去掉之后来回切换就不会报错

**Comment by dyyliao123** [comment]
![image](https://user-images.githubusercontent.com/25788204/93854338-21543380-fce8-11ea-99ab-2a95cdae8959.png)
这个文件报错，本地没有，估计是远程的

**Comment by dyyliao123** [comment]
跟loading没关系，每次切换好像都会报错

**Comment by jin-yufeng** [comment]
这个文件在这里
![微信截图_20200924112448](https://user-images.githubusercontent.com/48236054/94097184-9f374c80-fe58-11ea-87c3-86eea42e5062.png)
看起来是因为找不到 `#_top` 的标签导致的  
我用示例项目无法复现你说的问题，请提供能复现问题的 `demo` 项目，不然找不到问题出在哪里
