### ISSUE TITLE
uniapp小程序富文本无解析strike标签 

### ISSUE THREAD

**Issue by fansongyuan** [jin-yufeng/Parser#196]
uniapp小程序富文本无解析strike标签，无法显示划线

<span style="font-size: 12px;">门市价：<strike>127</strike>元</span>

![image](https://user-images.githubusercontent.com/18700451/93320706-faa78000-f843-11ea-899d-92b62072bab3.png)

**Comment by fansongyuan** [comment]
<span style="font-size: 12px;">门市价：<strike>127</strike>元</span>

**Comment by fansongyuan** [comment]
“<span style="font-size: 12px;">门市价：<strike>127</strike>元</span>”

**Comment by fansongyuan** [comment]
**_`<span style="font-size: 12px;">门市价：<strike>127</strike>元</span>`_**

**Comment by jin-yufeng** [comment]
默认不支持 `strike` 标签，需要的话只要在 `config.js` 中的 `userAgentStyles` 里添加一行 `strike: 'text-decoration:line-through',` 即可

**Comment by fansongyuan** [comment]
thanks,resolved.
