### ISSUE TITLE
可以搞个支持百度小程序的吗

### ISSUE THREAD

**Issue by q764657453** [jin-yufeng/Parser#20]

**Comment by jin-yufeng** [comment]
我尝试了一下适配百度小程序，但是出现了一些问题  
1.  本插件的基本显示方式是通过自定义组件递归的方式显示节点树，这需要各类事件（如图片点击、链接点击等）穿透`trees`组件向上冒泡，在微信小程序中，可以通过给`this.triggerEvent`的第三个参数`options`中设置`composed: true`即可让这个事件穿透自定义组件边界继续冒泡；
但百度小程序中没有这个`options`参数，也无法穿透组件，这将导致顶层组件无法获取到各类事件（尝试了`dispatch`和`triggerEvent`都无法穿透组件）；也试图通过`selectAllComponents`来获取所有子组件，在微信小程序中可以通过`>>>`来穿过组件选取，但在百度小程序中同样无法实现；百度小程序组件也没有`relations`字段来实现组件间的关联  
2. 本插件在显示过程中会通过`wxs`脚本来处理一些样式；但在百度小程序中，`filter`在标签的属性中使用无效（如`s-if`、`style`等，`filter`好像只能控制标签中的文本）  
  
还有一些别的小问题，所以目前来看，本插件无法移植到百度小程序上

**Comment by jin-yufeng** [comment]
已经实现啦，参考[插件包说明](https://github.com/jin-yufeng/Parser#%E6%8F%92%E4%BB%B6%E5%8C%85%E8%AF%B4%E6%98%8E)
