### ISSUE TITLE
[渲染层网络层错误] Failed to load image <URL>

### ISSUE THREAD

**Issue by srrgithub** [jin-yufeng/Parser#200]
**使用平台**： 微信小程序端

**问题描述** ：富文本中含有多个图片的时候，第一次进入页面报 渲染层网络层错误。
![image](https://user-images.githubusercontent.com/49754587/94252283-49e16500-ff56-11ea-8b19-eed066a044fd.png)

这个问题虽然是微信上报错，网上解决办法说是可以通过wx:if控制<image>标签，但是现在是在富文本中，无法使用这种操作。

```html

```

**Comment by jin-yufeng** [comment]
这是用的图片链接有问题，403禁止访问，有防盗链吧

**Comment by srrgithub** [comment]
但是我pc浏览器，h5都是可以正常打开的，就是在小程序里不能打开

**Comment by jin-yufeng** [comment]
真机调试试一下，模拟器上好像访问不了秀米的图片的

**Comment by mylover90** [comment]
![image](https://user-images.githubusercontent.com/73025909/96808693-e4e13800-144b-11eb-9778-86abafb266d3.png)

**Comment by jin-yufeng** [comment]
> ![image](https://user-images.githubusercontent.com/73025909/96808693-e4e13800-144b-11eb-9778-86abafb266d3.png)
> 有谁也遇到这种错呢？在本地小程序跑没问题，到手机上跑就读不了url了

要用远程地址啊，`localhost` 地址只有本地能访问

**Comment by mylover90** [comment]
您好，您的虽然是localhsot 但是我使用了web网页服务器了的。您好还有一个问题，页面的默认返回上一页不起作用是怎么回事呀？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jin-yufeng/Parser"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月29日(星期四) 晚上8:54
收件人:&nbsp;"jin-yufeng/Parser"<Parser@noreply.github.com&gt;;
抄送:&nbsp;"周世友"<526260086@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jin-yufeng/Parser] [渲染层网络层错误] Failed to load image <URL&gt; (#200)





  

 有谁也遇到这种错呢？在本地小程序跑没问题，到手机上跑就读不了url了
  
要用远程地址啊，localhost 地址只有本地能访问
