### ISSUE TITLE
修复APP支持 audio问题

### ISSUE THREAD

**Issue by woxiaoyao81** [jin-yufeng/Parser#201]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
uniapp

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**  
官方audio插件在app上不完全支持，尤其是解析html中多首音乐时只能播放一个，在微信小程序中不支持自动暂停上一首，而且没适配平板横屏

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**解决方案**  
我针对audio问题进行了修改，目前可以支持APP端的audio，主要实现以下功能
- APP端支持audio，并自动暂停上一首
- 微信小程序也支持自动暂停了
- 界面调整为自适应
我的方案地址 https://github.com/woxiaoyao81/parser-audio

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
感谢反馈
关于自动暂停的问题：
视频和音频没有设置 `id` 的时候 `id` 应该会被设置成 `audio/video` + `i`（第几个），因此不需要给每个 `video` 和 `audio` 指定 `id`
我这里测试播放新的音乐时自动暂停上一首音乐在微信小程序上是正常的（`autopause`）  
但是 `app` 上确实不正常，目前实现自动暂停的机制是播放一首歌/视频的时候检查所有提前收集好的 `context`，`id` 与当前播放的不相同的就暂停，而这个 `id` 是通过 `e.currentTarget.dataset.id` 获得的，`video`、`audio` 等原生组件触发的 `play` 事件都可以获得 `currentTarget` 对象，但是用自定义的 `audio` 组件时，通过 `emit` 触发的 `play` 事件是没有 `currentTarget` 的，也获取不到 `id`
之前的解决办法是使用 `@play.native`，通过 `native` 修饰符可以在事件对象中获取到 `currentTarget`，在微信小程序上也还是正常的，但在 `app` 上，`native` 修饰符后无法触发 `play` 事件了，然后自动暂停就出问题了

**Comment by jin-yufeng** [comment]
把你的方案加到 [文档](https://jin-yufeng.github.io/Parser/#/instructions?id=audio) 里了
