### ISSUE TITLE
后代选择器样式丢失

### ISSUE THREAD

**Issue by aloha66** [jin-yufeng/Parser#202]
**使用平台**  
微信

**问题描述**  

没有返回对应的后代选择器的class内容，而是把后代的内容转义到父级
![image](https://user-images.githubusercontent.com/20942781/94546538-9db6bb80-0280-11eb-8d68-da39adab5f46.png)

**html 代码**  

```
data:{
    html:'<style>.tt .a{font-style:italic}#b{font-weight:bold}p{text-align:center}</style>'
        + '<p class="tt"><span class="a">Hello </span><span id="b">World!</span></p>'
  }

```

**Comment by jin-yufeng** [comment]
默认不支持后代选择器，需要用 [CssHandler](https://jin-yufeng.github.io/Parser/#/instructions?id=csshandler) 扩展包  
不过这个处理确实有问题，默认情况下后代选择器应该被忽略，这里有点错乱
