### ISSUE TITLE
什么时候parser使用最新vue3.0重构一下？

### ISSUE THREAD

**Issue by sonicsunsky** [jin-yufeng/Parser#203]
什么时候parser使用最新vue3.0重构一下，自己尝试改成vue-composition-api格式，但是一直报错

**Comment by jin-yufeng** [comment]
目前没打算  
一个是重构会带来很大的工作量，我对 `vue3` 也不太熟悉  
另外 `uni-app` 也还 [没完全支持](https://ask.dcloud.net.cn/article/37834) `vue3`，还有各种兼容性问题
