### ISSUE TITLE
请问怎么禁用长按图片弹出菜单

### ISSUE THREAD

**Issue by zzkung** [jin-yufeng/Parser#205]
请问怎么禁用长按图片弹出菜单

**使用平台**  

微信

**问题描述**  

请问怎么禁用长按图片弹出菜单

**Comment by jin-yufeng** [comment]
把 `trees/trees.wxml` 里 `image` 标签的 `show-menu-by-longpress` 属性去掉就可以了

**Comment by zzkung** [comment]
ok
谢谢
