### ISSUE TITLE
希望在点击链接事件中即linkpress事件中，能增加阻止事件冒泡的方法

### ISSUE THREAD

**Issue by Kkirito1** [jin-yufeng/Parser#206]
现在有这样一个需求，希望我点击大盒子触发一个事件，然后点击链接也就是a标签解析的出来的链接触发linkpress，所以希望能阻止事件冒泡，我看了下源码h5很容易就改好了，但是没找到app端调用了哪个方法，希望作者能够加一个🙏

**Comment by jin-yufeng** [comment]
非 `nvue` 的话把 `libs/trees.vue` 里的 `@tap` 改成 `@tap.stop` 就可以了
后续考虑统一设置成不冒泡

**Comment by Kkirito1** [comment]
然后我发现在h5不能只改`libs/trees.vue`里面的`@tap`还需要u-parse里面的
`// 链接处理
				var links = this.rtf.getElementsByTagName('a');
				for (var link of links) {
					link.onclick = function() {
						var jump = true,
							href = this.getAttribute('href');
						_ts.$emit('linkpress', {
							href,
							ignore: () => jump = false
						});`

**Comment by jin-yufeng** [comment]
`uview` 已经同步更新啦
