### ISSUE TITLE
微信小程序端，会出现滚动条底部的灰色底色，怎么去掉？

### ISSUE THREAD

**Issue by Small-Years** [jin-yufeng/Parser#207]
**使用平台**  
微信小程序

**问题描述**  
<img width="416" alt="1" src="https://user-images.githubusercontent.com/17693968/96565108-82c2ee80-12f6-11eb-9846-6a754fbb0657.png">

如图，解析出来后会出现灰色的滚动条底色，实际内容是不超出的，水平垂直都不需要展示滚动条，请问应该怎么去除？
（在手机上是不出现的，在PC上小程序会出现）
**html 代码**  
<img width="1016" alt="2" src="https://user-images.githubusercontent.com/17693968/96565371-dd5c4a80-12f6-11eb-84e0-a8e0a5e3458b.png">

**Comment by jin-yufeng** [comment]
把 `parser` 标签里的 `overflow: scroll` 去掉看看还有没有

**Comment by Small-Years** [comment]
> 把 `parser` 标签里的 `overflow: scroll` 去掉看看还有没有

试过，去掉的话就如果内容太多就没法上下滚动了

**Comment by jin-yufeng** [comment]
改成 `auto` 呢？

**Comment by Small-Years** [comment]
> 改成 `auto` 呢？

可以了，谢谢
