### ISSUE TITLE
图片预览支持索引吗

### ISSUE THREAD

**Issue by lanqy** [jin-yufeng/Parser#21]
**问题描述**
图片预览支持索引吗？比如富文本里有多张图片，能否定位到所点击图片索引，展示当前点击的图片？

**Comment by jin-yufeng** [comment]
有点没懂😂什么样的索引

**Comment by lanqy** [comment]
@jin-yufeng 不好意思，没描述清楚，意思从点击的那种开始预览，而不是每次都从第一张开始

**Comment by jin-yufeng** [comment]
咦，现在不是点哪张就从哪张开始预览的么😨，你在示例小程序里试一下，每次点击都是预览第一张吗？

**Comment by lanqy** [comment]
@jin-yufeng 是的，示例里预览都是从第一张开始

**Comment by lanqy** [comment]
对了，我测试的是自定义测试这个地方，输入 html 点解析，然后点图片预览

**Comment by jin-yufeng** [comment]
提供一下html？另外在示例体验里试一下有没有这样吧

**Comment by lanqy** [comment]
HTML 是用你提供的，多次复制粘贴然后点解析（自定义测试 -》前端解析 -》点击图片 tag -》多次复制粘贴你提供的 html 到输入框里 -》点击解析 -》 点击图片）

**Comment by jin-yufeng** [comment]
我知道了，这样的话所有图片的url都是一样的；用[wx.previewImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.previewImage.html)预览的时候，会被定位到urls数组中第一次出现current的位置，所以就从第一张开始了，这个确实有点问题，不过不知道有没有办法

**Comment by lanqy** [comment]
OK，明白了，另外还想问一个问题，这个插件支持 uni-app 吗？

**Comment by jin-yufeng** [comment]
uni-app应该是可以引入小程序原生自定义组件的，可以参考一下这里[小程序组件支持](https://uniapp.dcloud.io/frame?id=%e5%b0%8f%e7%a8%8b%e5%ba%8f%e7%bb%84%e4%bb%b6%e6%94%af%e6%8c%81)，不过由于插件中用了一些微信的api，因此可能也只能在微信小程序中使用

**Comment by lanqy** [comment]
OK，我试试，感谢！

**Comment by jin-yufeng** [comment]
通过出现相同`url`的图片时，给图片链接加一个没有用的参数的方法使其互不相同，已经可以解决之前的问题啦
