### ISSUE TITLE
linkpress 只能获取a标签的href属性吗 我想在其他属性里面写一个值，获取这个值，如果写上href，那么所有被a标签包裹的都会出现蓝色的字，我想不写href标签，获取其他属性

### ISSUE THREAD

**Issue by ChinaBygones** [jin-yufeng/Parser#210]
linkpress 只能获取a标签的href属性吗 我想在其他属性里面写一个值，获取这个值，如果写上href，那么所有被a标签包裹的都会出现蓝色的字，我想不写href标签，获取其他属性

**Comment by jin-yufeng** [comment]
哪个平台？

**Comment by ChinaBygones** [comment]
微信小程序

**Comment by ChinaBygones** [comment]
搞定了，改了你的源文件，增加了我需要的属性值

**Comment by jin-yufeng** [comment]
微信小程序目前的处理应该是 `a` 标签不管有没有设置 `href` 都会被默认设置成蓝色的字
至于获取其他属性，目前除了 `data-` 开头的属性（出于减小解析结果大小的考虑默认去除），其他的应该能获取到吧

**Comment by ChinaBygones** [comment]
嗯
