### ISSUE TITLE
可以加个表情解析么？

### ISSUE THREAD

**Issue by qwz873112851** [jin-yufeng/Parser#22]

**Comment by jin-yufeng** [comment]
什么样的表情解析呢？像这种emoji😂😊🤗都是可以直接显示的

**Comment by qwz873112851** [comment]
![image](https://user-images.githubusercontent.com/22510555/64107553-5b852700-cdad-11e9-9a73-aca86a0a1124.png)像这种其他平台的表情可以解析么？

**Comment by jin-yufeng** [comment]
已添加[emoji补丁包](https://github.com/jin-yufeng/Parser#%E8%A1%A5%E4%B8%81%E5%8C%85)
