### ISSUE TITLE
百度小程序，图片点击不预览和放大。

### ISSUE THREAD

**Issue by nettimes** [jin-yufeng/Parser#225]
**使用平台**  

百度小程序

**问题描述**  

使用此组件以后解析的富文本，IMG点击不预览和放大。请问怎么解决。

**html 代码**

**Comment by jin-yufeng** [comment]
提供能复现的 demo 项目

**Comment by nettimes** [comment]
> 提供能复现的 demo 项目

能给我你的联系方式吗QQ远程也行

**Comment by nettimes** [comment]
发现问题了，如果img被a标签包含点击就无法预览和放大，请问该怎么处理？谢谢！

**Comment by jin-yufeng** [comment]
这个设计上就是这个样子，`a` 标签里有图片的时候只响应 `a` 标签的点击事件，同时跳转 `a` 标签又预览图片反而影响体验

**Comment by nettimes** [comment]
好的 谢谢！
