### ISSUE TITLE
taro 3.0根据文档导入支付宝提示找不到节点

### ISSUE THREAD

**Issue by liuyunzyj** [jin-yufeng/Parser#226]
https://jin-yufeng.gitee.io/parser/#/instructions?id=%e5%9c%a8-taro-%e4%b8%ad%e4%bd%bf%e7%94%a8
![image](https://user-images.githubusercontent.com/40293335/101443855-49534a80-3959-11eb-8af0-e09408ef9553.png)

**Comment by jin-yufeng** [comment]
`3.x` 的引入方式变了吧，直接看 `taro` 的 [官方文档](https://nervjs.github.io/taro/docs/mini-third-party)

**Comment by liuyunzyj** [comment]
改成那样也不行

**Comment by liuyunzyj** [comment]
把引入方式写在XX.config.ts里咯，支付宝不行，微信小程序可以

**Comment by jin-yufeng** [comment]
编译到支付宝的时候换成支付宝的组件包了没有

**Comment by liuyunzyj** [comment]
肯定换了呀

**Comment by jin-yufeng** [comment]
那你应该问 `taro`，我也不知道

**Comment by liuyunzyj** [comment]
.....................................

**Comment by jin-yufeng** [comment]
我试了一下，直接在页面上是能引用到组件的

![微信截图_20201213174057](https://user-images.githubusercontent.com/48236054/102008315-798c5600-3d6a-11eb-982b-3b93c90aba29.png)

但是 `taro` 通过 `import` 引入对应的模板，估计是支付宝 `import` 里引用不了自定义组件吧，然后就出现元素不存在的问题了
这个问题我这里是解决不了的

**Comment by jin-yufeng** [comment]
`taro 3.1` 可以解决 [#7309](https://github.com/NervJS/taro/issues/7309)
