### ISSUE TITLE
预览图片大图。触发onShow函数

### ISSUE THREAD

**Issue by lukaijin** [jin-yufeng/Parser#23]
**问题描述**
预览图片大图。触发onShow函数

此方法能否向外暴露。为了拦截onshow函数出触发

**Comment by jin-yufeng** [comment]
可以有，马上安排

**Comment by jin-yufeng** [comment]
已添加`autopreview`属性用于控制是否允许点击图片时自动预览以及在图片点击时触发的`bindimgtap`事件
