### ISSUE TITLE
Error in mounted hook: "TypeError: Cannot read property '$options' of undefined"

### ISSUE THREAD

**Issue by Y-A-K-E** [jin-yufeng/Parser#230]
[提示]: <> (提问前请前往 https://jin-yufeng.github.io/Parser/#/question?id=常见问题 查看是否已有解决方案，如果没有请按照下述模板详细描述问题)  

**使用平台**  
uni-app

[提示]: <> (微信/qq/百度/支付宝/头条/uni-app)  

**问题描述**
  H5预览解析正常.
微信/QQ小程序都抛出
**Error in mounted hook: "TypeError: Cannot read property '$options' of undefined"**
异常

[提示]: <> (请详细描述遇到的问题，最好附上截图)  

**html 代码**  
H5页面正常,小程序解析任何HTML代码都不行.

[提示]: <> (请附上出现问题的 html 代码，如果在示例项目中无法复现的，请提供能够复现问题的 demo)  

```html

```

**Comment by jin-yufeng** [comment]
用示例项目试过没有

**Comment by Y-A-K-E** [comment]
> 
> 
> 用示例项目试过没有

我记得pages页面中使用时正常的.
然后我将pages移动到自定义组件中使用就出现这个问题了.

相当于,pages传递html参数给自定义组件,
自定义组件再传html参数调用你的解析库.

**Comment by jin-yufeng** [comment]
我试了一下 [demo.zip](https://github.com/jin-yufeng/Parser/files/5684230/demo.zip) 没有复现你说的问题，请提供能复现的 `demo`

**Comment by Y-A-K-E** [comment]
这是我项目,
麻烦帮忙看看什么问题.谢谢

[blog_mini.zip](https://github.com/jin-yufeng/Parser/files/5684255/blog_mini.zip)

**Comment by jin-yufeng** [comment]
![微信截图_20201213154110](https://user-images.githubusercontent.com/48236054/102006128-a4ba7980-3d59-11eb-812c-122b8b97deb4.png)
这里的 `module.exports =` 改成 `export default` 就好了

**Comment by Y-A-K-E** [comment]
确实,可以了,谢谢.
