### ISSUE TITLE
空格不解析啊

### ISSUE THREAD

**Issue by qidoong** [jin-yufeng/Parser#26]
你好，空格不解析啊，怎么让文字首行缩进两个字，我在我的样式中加入text-indent，图片也一块缩进了

**Comment by jin-yufeng** [comment]
用实体空格&emsp;

**Comment by qidoong** [comment]
怎么设置 我在wxss样式中设置 image{display:block}不起作用 ，在哪设置，还有空格的问题，我的编辑器用的是微信自带的editor，它生成的标签里面空格就是空格，不是标签，这没法弄啊

**Comment by jin-yufeng** [comment]
放在wxss里没有用的，可以放在tagStyle里
```html
<Parser html="{{html}}" tag-style="{{tagStyle}}" />
```
```javascript
data:{
  html: "…",
  tagStyle: {
    img: "display:block;"
  }
}
```
或者加一个style标签也可以
```javascript
html="<style>img{display:block;}</style>"+html;
```
不过这样会对所有图片生效，如果可以直接改html的话就在该img的style里加上这句
另外，html中正常情况下空格就是被忽略的，连续的空格应该就是要用实体空格才对😂

**Comment by jin-yufeng** [comment]
![1](https://user-images.githubusercontent.com/48236054/64936803-3bb03180-d88a-11e9-848c-922e1d990443.png)
在trees/trees.wxml里这个位置加上text-indent:0;试试能不能解决图片被缩进的问题
