### ISSUE TITLE
9月17日版本，a标签解析出现问题

### ISSUE THREAD

**Issue by Jiang-Rain** [jin-yufeng/Parser#28]
**问题描述**  
您好，升级到9月17日版本，a标签解析出现问题：
![123](https://user-images.githubusercontent.com/27628585/65102721-8d79c880-d9fe-11e9-8dba-aa2c415eea8f.jpg)

9月15日版本没有问题
![20190918102143](https://user-images.githubusercontent.com/27628585/65102645-50153b00-d9fe-11e9-812f-9c61adb56b1f.jpg)

辛苦！

**Comment by jin-yufeng** [comment]
啊是出bug了😂
把Parser/trees/handler.wxs里textTag第一行a:true给删掉应该就好了

**Comment by jin-yufeng** [comment]
已经修好啦

**Comment by Jiang-Rain** [comment]
谢谢 辛苦啦
