### ISSUE TITLE
请问图片如何懒加载？

### ISSUE THREAD

**Issue by xlkit456852** [jin-yufeng/Parser#30]
正在使用中...其他一切都好，但请问图片如何懒加载？

**Comment by jin-yufeng** [comment]
这是个问题
因为`rich-text`组件中的`img`是可以自动实现图片自适应的，即没有设置宽高的时候按原大小显示，设置了宽或高的按比例缩放，同时设置了宽高的按设置的值显示
如果用`image`组件实现这一效果不仅计算起来会比较麻烦，还必须在`bindload`之后进行一次`setData`，如果图片很多也挺影响性能的，效果也没有`rich-text`好
所以最后选用了`rich-text`的`img`来显示图片，不过缺陷就是没有懒加载的属性，如果自己实现懒加载的功能也有点复杂
目前的话，如果十分有必要就试一下把`Parser/trees/trees.wxml`里的图片改为这样
```html
<image wx:if="{{item.name=='img'}}" src="{{item.attrs.src}}" mode="widthFix" style="{{item.attrs.style}}" lazyload data-ignore='{{item.attrs.ignore}}' data-src='{{item.attrs.src}}' bindtap='previewEvent'/>
```

**Comment by jin-yufeng** [comment]
微信小程序中已经支持`lazy-load`啦
给`parser`标签加上`lazy-load`属性即可
主要是通过`createIntersectionObserver`实现的

**Comment by xlkit456852** [comment]
使用了9月28的新包后，以下是我的代码：
```
<Parser html="{{productInfo.basic.rich_desc}}" tag-style="{{tagStyle}}" />
```
在加上了属性lazy-load="true"后，不起作用，图片还是全部加载出来了，是不是我还有哪个地方漏了？我的html属性是html代码来的

**Comment by jin-yufeng** [comment]
是把`lazy-load`属性加在`parser`标签上了吗（代码上还没有）  
另外懒加载只有图片在当前可视范围以下1500px以外的才会先不加载，否则会直接加载，文章是否有这么长呢

**Comment by xlkit456852** [comment]
```
<Parser lazy-load="true" html="{{productInfo.basic.rich_desc}}" tag-style="{{tagStyle}}" />
```
完整代码，不过好像还真没有那么长的文章，那我再测试看看~

**Comment by jin-yufeng** [comment]
可以用`demo/wx`目录下的示例程序试一下，点示例体验-前端功能示例，向下滑动的过程中可以在`network`中看到一张懒加载出的图
![3](https://user-images.githubusercontent.com/48236054/65828257-5d1e0e00-e2cb-11e9-818e-8f7879db31ab.png)

**Comment by xlkit456852** [comment]
OK~谢谢了哦
