### ISSUE TITLE
这里有一篇样式有误的文章

### ISSUE THREAD

**Issue by Mrdoge** [jin-yufeng/Parser#32]
文章预期是下面样子（PC端，左右排列）
![1569413755(1)](https://user-images.githubusercontent.com/23443852/65599900-7d9b4f00-dfd1-11e9-973a-b2a32a87de3f.png)

在小程序是这个样子的
![1569413965(1)](https://user-images.githubusercontent.com/23443852/65599941-9ad01d80-dfd1-11e9-8106-ec3c6819165c.png)

富文本html：
[测试文章.txt](https://github.com/jin-yufeng/Parser/files/3652361/default.txt)

**Comment by jin-yufeng** [comment]
用的是最新版吗  
我试了一下是可以的  
![微信图片_20190925215129](https://user-images.githubusercontent.com/48236054/65607766-a4f91880-dfdf-11e9-82bc-fd50f16654de.jpg)

**Comment by Mrdoge** [comment]
我这边没加node服务层的转化js，会不会是这个原因导致。。。

**Comment by jin-yufeng** [comment]
这和js没关系吧，你直接把这段复制到示例小程序的自定义测试-前端解析里试一下

**Comment by Mrdoge** [comment]
原因找到了，后台存文章的时候把文章进行了压缩，导致格式变了，前端拿到的格式是下面那样子的。
[测试文章2.txt](https://github.com/jin-yufeng/Parser/files/3655445/2.txt)


效果：
![微信图片_20190926093025](https://user-images.githubusercontent.com/23443852/65651158-25e7fc80-e040-11e9-94eb-9942c994afe9.jpg)

**Comment by jin-yufeng** [comment]
那让后台处理一下吧😂

**Comment by Mrdoge** [comment]
问题不大，前端稍微处理一下即可

**Comment by Mrdoge** [comment]
不好意思，原来是后台把我的样式吞掉了。插件本身很完美，给个赞

![1569478552](https://user-images.githubusercontent.com/23443852/65662924-0cf34180-e068-11e9-86cd-61f0400d4290.jpg)
