### ISSUE TITLE
a标签解析报错

### ISSUE THREAD

**Issue by Tyoon** [jin-yufeng/Parser#34]
如果a标签没有href属性，解析的时候会报错
<navigator/> should have url attribute when using navigateTo, redirectTo or switchTab

**Comment by jin-yufeng** [comment]
是在点击的时候出现这个错误吧，不过这个错误是`console.error`打印的，应该不影响？
![1](https://user-images.githubusercontent.com/48236054/66246694-9aa9ed80-e748-11e9-8230-26856a767635.png)

**Comment by Tyoon** [comment]
是的，点击的时候报错的，是不影响使用，但是估计微信端会监控到错误并上报到小程序后台的，不知道这样会不会影响小程序评分。

**Comment by jin-yufeng** [comment]
我觉得`console.error`打印的应该不会影响测评
另外我用`wx.navigateTo`试了一下，没有`url`或者页面不存在的时候也会通过`console.error`打印一个错误，用`try`也无法捕获

**Comment by Tyoon** [comment]
好的，谢谢！只能在服务端尽量避免用没加href属性的a标签了。
