### ISSUE TITLE
img标签的 alt属性里面是一段视频的地址，该怎么播放

### ISSUE THREAD

**Issue by xieyouliang** [jin-yufeng/Parser#35]
<img src="http://vod.ppcw-ltd.com/image/cover/F4179640F5164A1BAAF51268E4B4FDFA-6-2.png" videoid="93cebd01127a4e1f81af0d1b10a7930a" alt="http://vod.ppcw-ltd.com/sv/3a25e400-16db40049ed/3a25e400-16db40049ed.mp4">

**Comment by jin-yufeng** [comment]
目前来看不可行，因为`img`是由`rich-text`显示的，`alt`属性只能显示为文本
另外这是什么神奇的操作，在`html`里`alt`也只能是显示文本吧😂

**Comment by xieyouliang** [comment]
只能改你代码了，我也不知道这些鬼才是怎么会放去img标签里面，而不是放进video标签里。关键是安卓和IOS  APP就是这么做的，我只能适应

**Comment by jin-yufeng** [comment]
可以这样子，在`DomHandler.js`中190行这里加这样一段，把这种`img`改成`video`
```javascript
if(/.mp4/.test(attrs.alt)){
  name="video";
  attrs.id = (name + (++this['_' + name + 'Num']));
  attrs.controls = true;
  attrs.src=attrs.alt;
  delete attrs.alt;
}
```
![代码](https://user-images.githubusercontent.com/48236054/66696499-1d114f00-ecff-11e9-8108-65552a899f75.png)

**Comment by xieyouliang** [comment]
OK可以了谢了，我还在源码你就帮我解决了
