### ISSUE TITLE
后端解析包parser-wxapp使用

### ISSUE THREAD

**Issue by Tyoon** [jin-yufeng/Parser#36]
根据您的建议，我们现在想在服务端解析富文本，目前的方案是用VUE写每个小程序所需的页面，但是不知道怎么跟parser-wxapp整合。按照我们的理解，小程序端请求了一个网址后就会返回HTML富文本，这时怎么在返回富文本之前用parser-wxapp转换，麻烦您给解答一下，谢谢！

**Comment by jin-yufeng** [comment]
如果后端可以使用`node.js`
```javascript
const parser = require('parser-wxapp');
const res = await parser(html);
```
其中`html`是需要解析的字符串，`res`为解析结果，可以把这个结果（是一个结构体）存在数据库里，小程序请求时直接返回这个结构体（不用返回字符串），然后把这个结果作为`html`属性送给`parser`组件即可（传入结构体组件就不需要再对字符串进行解析）

如果用不了`node.js`
可以考虑调用云函数

**Comment by Tyoon** [comment]
明白了，就是说要通过一个管理后台来维护小程序端需要用到的富文本，请求返回之前调用解析器解析后再返回。整个网站解析和文件解析呢，麻烦您再指点指点。

**Comment by jin-yufeng** [comment]
网站解析
```javascript
const parser = require('parser-wxapp');
const res = await parser("https://example.com", "website");
```
文件解析
```javascript
const parser = require('parser-wxapp');
const res = await parser("demo.html", "file");
```
第二个参数表示模式，`html`可以省略
都是在后台解析完后把结果返回给前端
