### ISSUE TITLE
Web端Vue中怎么使用此插件解析website内容

### ISSUE THREAD

**Issue by see-kr** [jin-yufeng/Parser#37]
**问题描述**  
我想在vue里面使用这个插件解析另外一个网站的内容，但是有些插件一直报错。
**背景**
因为我们服务端代码使用java写的，如果仅仅只为了这个功能而去搭建服务端node环境，是没有必要的，而且服务端node 我们也不熟悉。因此，想在vue中使用此插件 去解析另外一个已发布的网站。
**预期的表现**  
本想 都是npm插件，应该可以适配且正常解析。我的最终目标就是 通过一个vue项目解析另一个vue项目，最后将整个项目解析结果传递给微信小程序。
**实际的表现**  
但实际情况就是：
第一次尝试：报找不到puppeteer插件，于是我手动安装了puppeteer插件。
第二次尝试：报找不到phantom 和ws，于是我分别安装了。
第三~N次尝试：依然报找不到ws，最后不得已，我安装了我们平时用的vue-native-websocket
并在报错位置引入：
![image](https://user-images.githubusercontent.com/53301015/66898028-e3a45080-f02a-11e9-93f2-bdaa964cdab9.png)
然后是不报错了。
第N+1次尝试：1、解析html代码段正常了，2、使用文件模式解析html文件时报找不到这个文件（可能是我文件路径写的有问题，这里有个疑问就是：这个文件模式是单文件模式还是说也可以解析这个页面中引入的外部js以及超链接指向的外部html页面？），3、使用website模式解析时，报fs插件有错误（fs插件web端我不知道能不能使用，但我还是npm install 安装了一下，结果是没有任何效果）：
![image](https://user-images.githubusercontent.com/53301015/66898404-b99f5e00-f02b-11e9-815f-7acdf1505a24.png)
![image](https://user-images.githubusercontent.com/53301015/66898474-da67b380-f02b-11e9-811d-eabab4d5fad5.png)

另外 使用website解析时报了跨域问题，我本地使用了跨域浏览器先初步跳过的这个报错。
期望您能够在百忙之中为晚辈指点迷津，我的这种思路是否可行，如果不可行 那么有没有什么可行之策呢？
冒昧叨扰，晚辈深表歉意，万望前辈海涵。承蒙不弃，教诲之恩无以为报，拜谢，再拜谢。
**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<template>
  <div id="app">
    aaaaaaaaaaaaaaaa
  </div>
</template>
<script>
import parser from 'parser-wxapp';

export default {
  name: 'app',
  components: {},
  created() {
    var promise = parser('http://127.0.0.1:8888/home', 'website');
    promise.then(function(response) {
      console.log(response);
    });
  }
}
</script>
<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

**Comment by jin-yufeng** [comment]
这可能是写的最详细的`issue`了哈哈哈
![微信图片_20191016161223](https://user-images.githubusercontent.com/48236054/66900636-c756e280-f02f-11e9-8314-8c25600f6ea3.jpg)
你的意思是想通过一个`vue`项目去解析另一个`vue`生成的网页，然后获取解析结果
个人觉得这样太绕了哈哈哈哈
方法一：
1. 本地安装[nodejs](http://nodejs.cn/download/)
2. 新建一个`test.js`文件
  ```javascript
  const parser = requrie("parser-wxapp");
  var promise = parser('http://127.0.0.1:8888/home', 'website');
  promise.then(function(response) {
    console.log(response);
  });
  ```
3. 命令行执行
  ```cmd
  node test.js
  ```
就可以看到结果了

方法二：
用微信小程序的云函数
```javascript
const parser=require('parser-wxapp');
exports.main = async (event, context) => {
    return await parser('http://127.0.0.1:8888/home', 'website');
}
```
本地执行一下也可以获得结果

如果非要在`web`端执行的话
我没试过，一些错误我也不知道怎么回事哈哈哈哈
因为用了很多`node`的东西，出错也是正常的
使用`website`模式时需要`fs`包是因为需要打开代码高亮的`css`（`parser`函数第三个参数传入`{autohighlight: false}`也许可以绕过去），为啥用不了`fs`我就不知道了
使用文件模式时，`link`标签（仅限`css`且是网络链接）时会发起请求并获取，`iframe`、`frame`标签（是网络链接）时会发起请求并获取，`a`标签仅会保留链接，在小程序中点击时会复制链接
但是**js是没有用的**，小程序中不能执行动态脚本，所有`script`标签都会被忽略（在`js`中动态加载的内容一般也是不行的，除非用类似`puppeteer`这种浏览器加载好后再解析）
总之，个人不太建议用这种方式

**Comment by see-kr** [comment]
好的，正在尝试。非常感谢！！！
