### ISSUE TITLE
图片样式统一支持自适应大小

### ISSUE THREAD

**Issue by caiqiuxia** [jin-yufeng/Parser#39]
**新功能描述**  
图片样式统一支持自适应大小

**应用场景**  
对图片数据不统一的处理

**Comment by jin-yufeng** [comment]
具体点？什么是统一支持自适应大小

**Comment by caiqiuxia** [comment]
响应式样式
解决办法：tagStyle.img = "max-width:100%;max-height:100%;height:auto !important";
请看一下有问题吗？
再问一个问题，如何调试字体大小？

**Comment by jin-yufeng** [comment]
一般来说这样就可以，但是`tagStyle`的优先级是最低的，如果`img`标签的`style`属性中有`height:1000px !important`可能就失效了
可以把`img-mode`属性设置成`widthFix`，也是宽度不变，高度自适应（具体参考[组件属性](https://github.com/jin-yufeng/Parser#%E7%BB%84%E4%BB%B6%E5%B1%9E%E6%80%A7)中的`img-mode`）
至于字体大小，在`style`中设置`font-size`就可以了
如果要设置全局的字体大小，就直接在`parser`标签上加
```html
<parser style="font-size:30px" />
```

**Comment by caiqiuxia** [comment]
多谢多谢~

**Comment by caiqiuxia** [comment]
![image](https://user-images.githubusercontent.com/20104546/67071429-15492300-f1b5-11e9-8e1b-6993f721fcc7.png)
你好，如何让小图片的宽度自适应屏幕宽度展示（宽度撑满屏幕），高度等比例缩放展示呢？

**Comment by jin-yufeng** [comment]
是对所有图片都这样吗？那就这样试一下
```javascript
data:{
  tagStyle:{
    img: "width:100% !important;"
  }
}
```
```html
<parser img-mode="widthFix" tag-style="{{tagStyle}}">
```
如果是对单张图片这样的话就在那个`img`的`style`属性里加上`width:100%;height:auto`

**Comment by caiqiuxia** [comment]
您好，我以上说的可能不清楚，我再阐述一下问题：对于一篇文章，穿插几张图片，有的图片较大，有的图片较小。对于较大的图片，您组件中已经处理，现在是针对其中某一张较小的图片的处理方式。
期待结果：无论图片大小，都统一展示成宽度自适应屏幕，高度按照宽度等比例缩放。
您的方法“在那个img的style属性里加上width:100%;height:auto” 暂时实现不了较小图片按照屏幕宽度展示的效果。请问还有其他方式吗？

**Comment by caiqiuxia** [comment]
抱歉，是我文件中有冲突。。。感谢，您耐心的解答💕
