### ISSUE TITLE
图片预览当一页中解析多条html时会出现只能预览最后一条的问题

### ISSUE THREAD

**Issue by sxs1995** [jin-yufeng/Parser#4]
![image](https://user-images.githubusercontent.com/22333956/57593421-eaa3d000-756d-11e9-86a4-7b148ac68193.png)

就像这样有两条html  当预览后第二张再预览第一张就会出现只能预览第二张的情况.

**Comment by jin-yufeng** [comment]
可以提供一下html字符串吗

**Comment by sxs1995** [comment]
![image](https://user-images.githubusercontent.com/22333956/57665233-ae37a900-762d-11e9-91b0-e0156d66d749.png)
![image](https://user-images.githubusercontent.com/22333956/57665243-b859a780-762d-11e9-92a3-b40600751ad4.png)
大致是这种情况  同一page解析多条html每解析一条html  都把上一条的imgList清空了

**Comment by jin-yufeng** [comment]
你是指希望预览第二张的时候通过左滑来预览第一张吗？单独点击预览单张图片应该是可以的吧（我这里是可以的）因为使用了多个Parser组件，组件之间是相互之间是独立的，每个组件的imgList都只有一张图片，因此只能预览单张（组件无法判断是不是处于同一个页面），如果希望左右滑动查看所有图片的话建议是放在一个Parser组件里

**Comment by sysweet** [comment]
页面上有两个Parser组件，每个组件里面都有一张图片，点击第一张图片预览，显示是第二个组件里面的图片。

**Comment by jin-yufeng** [comment]
发现问题了，会尽快修复

**Comment by jin-yufeng** [comment]
下载一下最新版的，应该没有问题了哦
