### ISSUE TITLE
摄像头调用及拍照

### ISSUE THREAD

**Issue by Tyoon** [jin-yufeng/Parser#40]
请教个问题，有什么办法实现摄像头拍照并上传。

**Comment by jin-yufeng** [comment]
这个不属于富文本的范畴了吧😂
[wx.chooseImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html)是可以使用相机获取图片的
或者用[camera组件](https://developers.weixin.qq.com/miniprogram/dev/component/camera.html)

**Comment by Tyoon** [comment]
😪微信端现在不允许上传带人脸的照片，弄得没办法了才问您这边。

**Comment by Tyoon** [comment]
如果在小程序里用Webview，体验又不太好。

**Comment by jin-yufeng** [comment]
现在还有这种限制的吗，这我就不知道了

**Comment by Tyoon** [comment]
是的，应该是新的政策，不允许在小程序采集个人生物信息，所以才想着能不能用您的这个组件解决目前的问题。
