### ISSUE TITLE
@keyframes

### ISSUE THREAD

**Issue by anndaming** [jin-yufeng/Parser#41]
**问题描述**  
style标签中使用@keyframes是解析不了的吗

**预期的表现**  
style标签中使用@keyframes能解析，这样就可以操作动画

**实际的表现**  
style标签中使用@keyframes带上后，动画无效果

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<style>
    @keyframes avatar_animation {
        0% {
            transform: rotate(30deg);
        }
        50% {
            transform: rotate(-30deg);
        }
        100% {
            transform: rotate(30deg);
        }
    }
    .avatar_img {
        animation-name: avatar_animation;
        animation-duration: 2s;
        animation-timing-function: cubic-bezier(0, 0, 1, 0.5, 0, 0, 1, 0.5);
        animation-iteration-count: infinite;
    }
</style>
<p>xxxxxxx</p>
"""
```

**Comment by jin-yufeng** [comment]
是的，目前`style`标签不支持`@keyframes`
因为`style`标签解析的原理是把样式解析到各个标签的`style`属性中去，像`@keyframes`（还有伪类等）是无法写在行内样式里的，所以无法支持
一个替代办法是写在`/trees/trees.wxss`里，写在`wxss`里的`@keyframes`是可以生效的（需要注意一下在组件中只能使用`class`选择器）
