### ISSUE TITLE
部分行内标签换行

### ISSUE THREAD

**Issue by xiexyao** [jin-yufeng/Parser#43]
**问题描述**  
部分行内标签，比如<strong>粗体</strong>A<strong>粗体</strong>A<strong>粗体</strong>A<strong>粗体</strong>A<strong>粗体</strong>，后面几个粗体被换行了

在Parser.js的71行是否可以换成continue，这样？

**Comment by jin-yufeng** [comment]
是指 `H5` 端吗，确实是应该改成 `continue`

**Comment by xiexyao** [comment]
是H5的，改成continue后测试是好的

**Comment by seldom1024** [comment]
**存在没有controls属性的video标签，可能导致无法播放**,解析后出现的问题，原因是在没有controls属性的vidio标签，Parser解析后无法播放，但是使用WxParser是可以播放的，↵换行符号解析不了
