### ISSUE TITLE
微信小程序中出现滚动条

### ISSUE THREAD

**Issue by xiexyao** [jin-yufeng/Parser#44]
**问题描述**  
在微信小程序中滑动时，界面会出现滚动条，导致文章滚动不了
/Users/fei/Desktop/QQ20191102-191448@2x.png
是否可以去掉index.vue的最后的样式
/* #ifndef MP-BAIDU */
	:host {
		display: block;
		overflow: scroll;
		-webkit-overflow-scrolling: touch;
	}
	/* #endif */

**Comment by jin-yufeng** [comment]
若出现内容的横向宽度超出了屏幕宽度，加上 `overflow:scroll` 可以横向滑动（若去掉则无法横向滑动，如果觉得不需要可以去掉）
另外，出现滚动条不会导致文章滚动不了吧

**Comment by xiexyao** [comment]
会滑动不了的，这里不知道怎么发图片，不然可以给你看看现象

**Comment by xiexyao** [comment]
<img width="316" alt="QQ20191102-191448@2x" src="https://user-images.githubusercontent.com/24327607/68073574-9bc44e00-fdcc-11e9-8360-cc6caaf33f73.png">

**Comment by jin-yufeng** [comment]
提供一下这段的 `html` ?

**Comment by xiexyao** [comment]
随便一段代码都行，只要高度超过微信可视区域，滑动都会出现。

**Comment by jin-yufeng** [comment]
你用示例项目能滑动吗？

**Comment by xiexyao** [comment]
试了一下，并没有出现问题，可能是我css不对，不好意思啊，另外感谢一下，项目十分好用，谢谢！
