### ISSUE TITLE
vedio 没有controls属性无法播放

### ISSUE THREAD

**Issue by seldom1024** [jin-yufeng/Parser#45]
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div>Hello World!</div>
```

**Comment by seldom1024** [comment]
存在没有controls属性的video标签，可能导致无法播放,解析后出现的问题，原因是在没有controls属性的vidio标签，Parser解析后无法播放，但是使用WxParser是可以播放的，↵换行符号解析不了

**Comment by jin-yufeng** [comment]
本插件是参照 `html` 的标准，`video` 标签没有 `controls` 属性的时候就是可能无法播放的，这点在解析的时候也会有警告提醒（毕竟不排除有不需要 `controls` 的应用场景）  
如果你需要所有视频都加上 `controls` ，把 `/trees/trees.wxml` 里 `18` 行的 `video` 里把 `controls` 属性改成 `true` 就好了  
换行符也是同样的道理，你把↵放在 `html` 文件里也是原样显示的，在 `html` 里换行应该使用 `br` 标签，可以自行正则替换一下  
```javascript
html = html.replace(/↵/g, "<br />");
```

**Comment by seldom1024** [comment]
非常感谢
