### ISSUE TITLE
苹果手机无法全部渲染，卡死问题

### ISSUE THREAD

**Issue by FJDJHD** [jin-yufeng/Parser#46]
在iphone7,系统12.3.1，会出现页面渲染一部分，或者卡死的情况，这是什么问题的。。。，代码是用的示例代码，这会和返回的html字符串有关吗？

**Comment by jin-yufeng** [comment]
用的是示例项目吗？
把`html`改短一点试一下吧

**Comment by FJDJHD** [comment]
我用的git里面的 uniappdemo测试的，是百度小程序，html渲染下面会部分出现空白，安卓手机华为测试正常，苹果有问题，百度小程序可以兼容苹果吗 ？

**Comment by FJDJHD** [comment]
![623e512018a99fe525d175b2c5289fc](https://user-images.githubusercontent.com/8232835/68520973-465dd480-02d7-11ea-8862-c097ddadff07.jpg)
这是截图

**Comment by jin-yufeng** [comment]
这有点超出我的能力范围了
照理说百度小程序应该能保证各端的显示情况相同
我没有 `ios` 设备也只在模拟器上测试过
猜测可能是因为这个示例比较复杂，节点比较多导致渲染不出来了，可以试一下用一个短一点的 `html` 测试一下

**Comment by FJDJHD** [comment]
因为html内容是后台富文本编辑返回的，可能文章有比较长的，这个没法改变，这个如果要改的话，在代码具体哪里可以改，要不加QQ聊吧（260149524），uniapp插件市场其他的插件也试过，对这个插件很满意，就差这点适配了。。

**Comment by jin-yufeng** [comment]
已解决，升级百度 `APP` 版本即可
