### ISSUE TITLE
如何解决长内容的渲染问题？

### ISSUE THREAD

**Issue by mlsjla** [jin-yufeng/Parser#47]
**问题描述**  

当长内容并且节点复杂情况下，渲染会特别卡。
使用节点array方式只能提升渲染部分效率。但是内容长了，占用内存太多，还是会卡。

### 长内容卡的主要原因：
* 内容太多，节点太多，占用内容太多，如长内容，通过array方式引入，开发工具会直接报`setdata内存占用过大`
* 长内容，图片太多，需要解析的时间太久，递归太多内容导致资源占用过大，时间比较久。

### 如果无法解决效率问题，我感觉内容页面用webview还更加流畅些。

**预期的表现**  
#### 希望能有一个类似于懒加载的按需解析功能。
比如array下面，比如有3个节点。
那么优先解析第一个，如果第一个占满了屏幕，则后面的先不解析；如果屏幕没占满，则解析第二个array
当滚动往下，触发继续解析操作。

希望能有方案解决长内容渲染效率问题

**实际的表现**  
希望能有方案解决长内容渲染效率问题

**Comment by jin-yufeng** [comment]
现在图片是可以懒加载的，设置`lazy-load`属性即可
按节点懒加载可能会好一点，但是标签数过多后难免会卡（官方`Audits`测评建议是一个页面<1000个标签）
你这个`setData`都会报内存占用过大了，估计是太多了，更建议分页显示吧

**Comment by mlsjla** [comment]
@jin-yufeng  
就算是分页显示或者超过1000个标签， 建议还是由Parser来处理这个分页或者滚动触发解析。

也就是，默认我们先解析个800个标签，然后当页面滚动，再触发滚动个800个标签，这样似乎好一些对吗？

**Comment by mlsjla** [comment]
我这边测试，1600个标签
微信小程序直接卡死微信崩溃。
chrome开发工具卡着显示不出来，只显示出来一点内容。 
图片是用了懒加载的。

**Comment by jin-yufeng** [comment]
这么大的数据通过`setData`传给`Parser`就容易卡了，`setData`一次传过大的数据就容易卡住
我建议是先把`html` `setData`成`Array[0]`，底下放个翻页组件，翻页后再设置成`Array[1]`......这样

**Comment by mlsjla** [comment]
@jin-yufeng 

感谢建议。
我想了一个方案，不采用翻页功能，翻页体验不好。

我想通过改进组件方式， 我们默认一次显示500个标签（可配置），即array（0-500）。这个标签量基本上足够显示一个完整屏幕。

当用户滚动页面到100%个屏幕高度，则再解析500个标签。
然后当用户再次滚动100%屏幕高度，这样再解析个。

也就是， 本来1个
```
<parser v-if="postlist.message" :html="postlist.message"></parser>
```
变更为
```
<parser v-if="postlist.message" :html="postlist.message[0-499]"></parser>
<parser v-if="postlist.message" :html="postlist.message[500-999]"></parser>
<parser v-if="postlist.message" :html="postlist.message[1000-1499]"></parser>

```

当然我希望我们解析工具可以向这个方向改进下。

**Comment by mlsjla** [comment]
我们通过v-if 来改进是否解析。默认第一个是显示。其他都是v-if="false"。  当滚动页面，调整v-if的参数即可实现这个解析。

**Comment by mlsjla** [comment]
这种方式的缺点，是，万一一个一级标签只有1个，但是下面的二级标签特别多达到数千个，也容易卡。但是这种情况特别少。
比如

**Comment by jin-yufeng** [comment]
不进行渲染是无法知道这里的内容有多高的，所以这么做必须是提供内容的时候已经分好了，每块渲染出来大约一两个屏幕高度这样，如果可以做到感觉和官方这个[长列表组件](https://developers.weixin.qq.com/miniprogram/dev/extended/functional/recycle-view.html)的思想差不多
也许可以直接把`Parser`组件放在这个`recycle-item`里

**Comment by mlsjla** [comment]
@jin-yufeng  是这样， 用recycle-view来解决这个问题似乎可以。
不过有个问题， 因为富文本本身如果属于某个recycle-view里面的某个内容，相互嵌套recycle-view
是否有问题？

**Comment by jin-yufeng** [comment]
你试试呗，我也没试过

**Comment by jin-yufeng** [comment]
这里添加了一个示例 [链接](https://jin-yufeng.github.io/Parser/#/instructions?id=%e9%95%bf%e5%86%85%e5%ae%b9%e5%a4%84%e7%90%86)
