### ISSUE TITLE
子元素里有样式超过100%则会出现横向滚动条

### ISSUE THREAD

**Issue by liuyong** [jin-yufeng/Parser#5]
`<section class="" style="font-size: 16px;"><section style="margin-top: 10px;margin-bottom: 10px;box-sizing: border-box;"><section data-width="96%" style="display: inline-block;width: 535.672px;vertical-align: top;box-shadow: rgb(0, 0, 0) 0px 0px 0px;box-sizing: border-box;"><section style="box-sizing: border-box;"><section style="background-image: linear-gradient(135deg, rgb(163, 241, 142) 0%, rgb(57, 186, 121) 100%);box-sizing: border-box;"><section style="padding: 4px;box-sizing: border-box;"><section style="text-align: right;box-sizing: border-box;"><section data-width="100%" style="padding-top: 10px;padding-bottom: 10px;display: inline-block;width: 527.672px;vertical-align: top;background-color: rgb(254, 255, 255);box-sizing: border-box;"><section style="text-align: center;box-sizing: border-box;transform: translate3d(12px, 0px, 0px);"><section style="max-width: 100%;vertical-align: middle;display: inline-block;box-sizing: border-box;overflow: hidden !important;"><img class="" data-copyright="0" data-cropselx1="0" data-cropselx2="528" data-cropsely1="0" data-cropsely2="293" data-ratio="0.667" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/SiaRjbGUeWDNibwWNsIicQLF8UE1kXp3psFYgoFbYdvKxUlP8tepItnn4icBCrUqNAibs8AGo4QbyHk4WbDiaiaHFEKEQ/640?wx_fmt=jpeg" data-type="jpeg" data-w="1000" data-backw="528" data-backh="352" data-before-oversubscription-url="https://mmbiz.qpic.cn/mmbiz_jpg/SiaRjbGUeWDNibwWNsIicQLF8UE1kXp3psFYgoFbYdvKxUlP8tepItnn4icBCrUqNAibs8AGo4QbyHk4WbDiaiaHFEKEQ/640?wx_fmt=jpeg" style="vertical-align: middle; box-sizing: border-box; width: 527.672px !important; height: auto !important; visibility: visible !important;" _width="527.672px" src="https://mmbiz.qpic.cn/mmbiz_jpg/SiaRjbGUeWDNibwWNsIicQLF8UE1kXp3psFYgoFbYdvKxUlP8tepItnn4icBCrUqNAibs8AGo4QbyHk4WbDiaiaHFEKEQ/640?wx_fmt=jpeg&amp;tp=webp&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" crossorigin="anonymous" data-fail="0"></section></section></section></section></section></section></section></section></section></section>`

以上代码在小程序上跑会有横向滚动条，估计是宽超过100%，transform: translate3d(12px, 0px, 0px);
这个样式导致，盼完善

**Comment by jin-yufeng** [comment]
这个也是因为好几个地方设置了宽度超过了手机屏幕的宽度，所以会出现滚动条
![2](https://user-images.githubusercontent.com/48236054/58562161-48693500-825b-11e9-9379-a0a2b3ad4142.png)

**Comment by liuyong** [comment]
Duplicate of #6
