### ISSUE TITLE
富文本自带样式宽度超出手机屏幕，出现横向滚动条怎么解决呢？

### ISSUE THREAD

**Issue by ZYZ12589** [jin-yufeng/Parser#50]
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div>Hello World!</div>
```

**Comment by jin-yufeng** [comment]
不出现滚动条不就看不到超出的部分了么，所以你是想要什么样的效果
如果你想怎么样都不滚动就给 `parser`  标签的 `style` 里加上 `overflow:hidden`
