### ISSUE TITLE
点击a标签，有办法不直接跳转吗？

### ISSUE THREAD

**Issue by JIANHUI2015** [jin-yufeng/Parser#51]
`链接点击效果
点击a标签，若href为小程序内部页面路径，将直接跳转；`

**应用场景**  
我想拿到a标签里的链接做一些参数拼接后再手动调用wx.navigatiTo跳转。我知道可以用linkpress拿到href，现在希望禁止直接跳转，有解决办法吗

**Comment by JIANHUI2015** [comment]
我把Parser/trees/trees.wxml里a标签对应的navigator控件改成了view，目前解决了我的需求。

**Comment by jin-yufeng** [comment]
目前最新版在 `linkpress` 和 `imgtap` 回调的返回值中都增加了一个 `ignore`，在回调中调用此函数就可以不自动跳转链接/预览图片（类似于 `a` 标签的 `onclick` 返回 `false` 不跳转一样，由于 `event` 获取不到返回值，因此添加了一个函数实现），示例：
```html
<parser html="{{html}}" bindlinkpress="linkpress"></parser>
```
```javascript
linkpress(e){
  if(e.detail.href[0] == '/') // 内部页面路径
    e.detail.ignore(); // 调用此函数将不进行自动跳转
  // 自定义处理
}
```

**Comment by JIANHUI2015** [comment]
感谢~
