### ISSUE TITLE
在使用uni-app的parser组件解析富文本表格，表格内的链接变成rich-text

### ISSUE THREAD

**Issue by godkun** [jin-yufeng/Parser#54]
**问题描述**  

在使用uni-app的parser组件解析富文本表格，表格内的链接变成rich-text

```html
<td>
<a href="https://xxxxxx.com" target="_self">demo</a>
</td>
```
在被parser解析的时候，链接没有了，并且都是rich-text，点击没有反应。

想问parser支持解析表格内部的a链接，并且支持跳转么

**Comment by jin-yufeng** [comment]
`table` 样式十分复杂，`colspan` 和 `rowspan` 等几乎无法模拟，只有 `rich-text` 能够实现最佳效果，所以 `table` 只能用 `rich-text` 显示，内部的链接和图片都无法点击

**Comment by godkun** [comment]
嗯嗯，这样的话，电商之类的商品详情页富文本里面，如果表格内有a链接的话，就没有办法跳转了。我来想想其他办法吧，谢谢你

**Comment by jin-yufeng** [comment]
目前最新版对于没有使用 `colspan` 和 `rowspan` 的表格里的链接已经可以点击了

**Comment by godkun** [comment]
> 目前最新版对于没有使用 `colspan` 和 `rowspan` 的表格里的链接已经可以点击了

感谢，不过怎么跳转呢，我好像没看到使用说明，我点击表格里面的链接，貌似没反应

**Comment by godkun** [comment]
> 目前最新版对于没有使用 `colspan` 和 `rowspan` 的表格里的链接已经可以点击了

还有个问题，现在老哥的parser有没有支持table里面有热区的场景
