### ISSUE TITLE
a标签是否能支持文章内的锚点跳转？

### ISSUE THREAD

**Issue by CHANGSHAQI** [jin-yufeng/Parser#55]
**新功能描述**  
锚点跳转

**应用场景**  
小程序使用elasticsearch进行搜索文章,返回富文本标签,其中有高亮标签,在打开文章的时候,直接跳转到高亮的地方

**Comment by jin-yufeng** [comment]
最新版已经支持，使用方法：
设置锚点：给标签加上 `id` 属性即可
跳转锚点：
1. 通过 `a` 标签跳转：将 `a` 标签的 `href` 属性设置为 `#id` 即可
2. 通过获取组件实例手动跳转：可在页面中通过 `this.selectComponent("#id").navigateTo({id, success, fail})` 实现手动跳转，`id` 是要跳转的锚点的 `id`（不加 `#`，为空时将跳转到插件顶部），`success` 和 `fail` 为成功和失败回调。此函数**必须在** `ready` 回调及以后才能使用

另外需要给 `parser` 标签设置 `use-anchor` 属性

示例代码
```html
<parser id="article" html="{{html}}" use-anchor bindready="ready"></parser>
```
```javascript
data:{
  html: "<a href='#test'>点我跳转锚点</a>" + // 点击此 a 标签可以跳转锚点
  "..." +
  "<div id='test'></div>"
},
ready(){
  // 通过获取组件实例按需手动跳转
  this.selectComponent("#article").navigateTo({
    id: "test",
    success: console.log,
    fail: console.error
  })
}
```

更多信息可见：[组件属性](https://jin-yufeng.github.io/Parser/#/instructions?id=%e7%bb%84%e4%bb%b6%e5%b1%9e%e6%80%a7)

**Comment by CHANGSHAQI** [comment]
@jin-yufeng 你是真的厉害！而且真的高效！！感谢！！

**Comment by CHANGSHAQI** [comment]
@jin-yufeng 代码中已实现,效果很好！
后端:
`highlightBuilder.preTags("<em id=\"highlight\" style=\"color:red;font-style:normal;\">");
		highlightBuilder.postTags("</em>");`

小程序:
`   <parser  id="article" html="{{content}}" style="line-height:40rpx;" use-anchor bindready="ready"></parser>`

` ready() {
    // 通过获取组件实例按需手动跳转
    this.selectComponent("#article").navigateTo({
      id: "highlight",
      success: console.log,
      fail: console.error
    })
  },`

同时在onLoad方法里加上ready函数

效果
![image](https://user-images.githubusercontent.com/34267233/70103187-54eca100-1675-11ea-95ba-20543b369488.png)
打开文章的同时,自动跳转高亮的地方,同时高亮位于第一行

一开始担心多处高亮,有多个 id="highlight" ,会不会出错,看来包容性还是很好

**Comment by CHANGSHAQI** [comment]
发现个问题
`
   <block wx:if="{{light==1&&type!=5}}">
 <parser id="article" html="{{content}}" style="line-height:40rpx;" use-anchor bindready="ready"></parser>
   </block>
`
写了判断条件,如果不满足条件,不去用这个标签,还是会调用ready方法
![image](https://user-images.githubusercontent.com/34267233/70116709-72823080-169e-11ea-9484-eaf38e2cecd1.png)
 然后去调用navigateTo报null

**Comment by CHANGSHAQI** [comment]
发现个问题
我有个判断条件:文章为pdf就不调用这个组件
````
<block wx:if="{{light==1&&type!=5}}">
<parser id="article" html="{{content}}" style="line-height:40rpx;" use-anchor bindready="ready"></parser>
</block>
````
判断条件也为false
但它还是调用了ready函数,导致
![image](https://user-images.githubusercontent.com/34267233/70118570-4a490080-16a3-11ea-96b2-2c8287b3a349.png)

**Comment by CHANGSHAQI** [comment]
解决方法:
````
 ready() {
    if (this.selectComponent("#article")==null){

    }else{
        // 通过获取组件实例按需手动跳转
        this.selectComponent("#article").navigateTo({
        id: "highlight",
        success: console.log,
        fail: console.error
      })
    }
  },
````

**Comment by jin-yufeng** [comment]
`content` 和 `light`, `type` 是同时被 `setData` 的吗，如果是同时 `setData` 的应该不会出现这个问题（`parser` 标签不会被创建），但是如果先 `setData` 了 `content` 和 `light` ，然后再设置 `type` 就会出现这个问题，因为 `parser` 标签先被创建并开始解析了，但 `ready` 回调时标签被销毁了，因此就会出错
这样判断一下可以解决也可以

**Comment by CHANGSHAQI** [comment]
是这样的！同时赋值没有报错了

**Comment by CHANGSHAQI** [comment]
@jin-yufeng 小程序开发者工具更新到最新后警告
![image](https://user-images.githubusercontent.com/34267233/70196715-9b5d0100-1744-11ea-8b66-8760c7cef943.png)

![image](https://user-images.githubusercontent.com/34267233/70196735-a9ab1d00-1744-11ea-8b24-112820039064.png)

**Comment by CHANGSHAQI** [comment]
或许写成
````
wx:key="index"
````
不知到这样有没有问题

**Comment by jin-yufeng** [comment]
已解决
