### ISSUE TITLE
请问可以新增配置host吗

### ISSUE THREAD

**Issue by Mrdoge** [jin-yufeng/Parser#56]
**新功能描述**  
后台富文本上传的图片是相对路径，到了手机端就看不到了

**应用场景**  
这个是wxParser的
![image](https://user-images.githubusercontent.com/23443852/69930046-5ba3d880-14fc-11ea-81f3-5019b45150ca.png)

这个是parser的
![image](https://user-images.githubusercontent.com/23443852/69930078-8857f000-14fc-11ea-81d4-53116b0be807.png)

可以新增一个host的配置吗？

**Comment by jin-yufeng** [comment]
最新版已经支持，设置 `domain` 属性即可，设置后会给图片链接自动拼接上主域名或协议名
示例：
```html
<parser html="{{html}}" domain="https://example.com" />
```
```javascript
data:{
  html:"<img src='/path/xxx.png'>" + // 将被拼接为 https://example.com/path/xxx.png
  "<img src='//example.com/path/xxx.jpg'>" // 将被拼接为 https://example.com/path/xxx.jpg
}
```

**Comment by Mrdoge** [comment]
收到，辛苦了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jin-yufeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 凌晨0:25
收件人:&nbsp;"jin-yufeng/Parser"<Parser@noreply.github.com&gt;;
抄送:&nbsp;"非凡哥"<1647487387@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jin-yufeng/Parser] 请问可以新增配置host吗 (#56)




最新版已经支持，设置 domain 属性即可，设置后会给图片链接自动拼接上主域名或协议名
 示例：
 <parser html="{{html}}" domain="https://example.com" /&gt;
 data:{   html:"<img src='/path/xxx.png'&gt;" + // 将被拼接为 https://example.com/path/xxx.png   "<img src='//example.com/path/xxx.jpg'&gt;" // 将被拼接为 https://example.com/path/xxx.jpg }
