### ISSUE TITLE
关于tag-style的问题

### ISSUE THREAD

**Issue by JIANHUI2015** [jin-yufeng/Parser#57]
**问题描述**  
我希望在img标签没有样式的时候给一个默认的样式，所以添加了如下代码：
```
tag-style= {img:"display:block;width:100%;"}
```
但是在一些特殊的地方，我要单独给img设置一个样式：
```
.xximg {
    display:inline-block;
}
```

**预期的表现**  
我以为该图片的display应该是inline-block的

**实际的表现**  
实际上display是block， 请问这个是feature还是我使用方法有问题？

我希望在一些特殊的地方可以自己设置样式去覆盖掉tag-style中定义的默认样式，能做到吗？感谢

**Comment by jin-yufeng** [comment]
这个 `.xximg` 的样式是写在哪里的，是在 `style` 标签里还是 `wxss` 文件里

**Comment by JIANHUI2015** [comment]
> 这个 `.xximg` 的样式是写在哪里的，是在 `style` 标签里还是 `wxss` 文件里

写在一个我自定义的`component`对应的`wxss`文件里，该组件封装了`Parser`，在`trees.wxss`中我引入了该`wxss`文件。

**Comment by jin-yufeng** [comment]
各类样式的优先级是 外部样式（写在 `wxss` 里的） < `tag-style` < `style` 标签里的样式 < 标签的行内样式
理论上应该是 `tag-style` 的优先级最低，但是因为匹配时，不管是 `tag-style` 还是 `style` 标签的匹配，最终都只能添加到标签的 `style` 属性中去（因为不能动态写入 `wxss`），而 `style` 里的样式优先级高于 `class` 匹配的样式，所以写在 `wxss` 里的样式优先级最低
解决方案要么给这个样式后面加上 `!important` 让其优先级提高；要么把这个 `xximg` 的样式写在一个 `style` 标签里

**Comment by JIANHUI2015** [comment]
已解决，感谢！
