### ISSUE TITLE
出现横向滚动条

### ISSUE THREAD

**Issue by liuyong** [jin-yufeng/Parser#6]
`<section style="background-image: url(&quot;https://mmbiz.qpic.cn/mmbiz_jpg/Ljib4So7yuWg7a9PAmMjiaT076OLfiaqKT3ZWDbCf6Tcd7jNWToeuKOsOYuujjibtxQ0ABxZr2tcuicJOPolFGmqiayQ/640?wx_fmt=jpeg&quot;);background-position: initial;background-repeat: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-size: 100%;"><section data-width="92%" style="margin-right: auto;margin-left: auto;padding: 5px;box-sizing: border-box;width: 513.359px;"><section style="color: rgb(135, 173, 109);letter-spacing: 1.5px;line-height: 22px;text-align: justify;"><p class="">&nbsp; &nbsp;&nbsp;</p><p class="">&nbsp; &nbsp; 肇庆砚坑紫云谷位于广东省肇庆市东南郊烂柯山，西江羚羊峡省级自然保护区内。砚坑拥有端砚开采、加工的悠久历史，中国品质最好的端砚都出自于紫云谷的老坑、坑子、麻子坑三大名坑。这里有唐朝年间开采砚石的千年老坑洞，并可观赏到一年一度盛开的烂柯仙钟之称的吊钟花，铁索桥，户外拓展基地，绿色长廓，古磨群遗址，沟谷雨林品氧谷、侗族歌舞表演，沿着脚下的小溪，就开始进入风景如画的山谷。只见脚下流水淙淙，溪水清澈见底，两旁长满青苔的石壁背后，一会儿是竹林，一会儿是开满野花的山坡。巨石、流水、光影、蝉鸣、鸟声、醉人的清风<span class="">……</span>清幽的画面不断切换，让人目不暇接。分布着众多的水潭、怪石，珍珠水叠群，独特的自然风光。涉溪探险、觅玉寻金，溯流而上途经多处天然山水乐园、瀑布群。天青潭，天下第一砚，跳涧潭，紫背天葵保护区，神龟潭，冰纹潭与大自然融为一体。凤凰岩、古塔岩、宣德岩、朝天岩，麻子坑更是青山环抱，苍翠蜿蜒，绿水环绕，宛如一幅天然图画。</p></section></section></section>`

这个也会超过宽度，在小程序里出现横向滚动条，盼复

**Comment by liuyong** [comment]
![image](https://user-images.githubusercontent.com/664463/58549682-a2a7cd00-823e-11e9-9131-54780b9b418f.png)

**Comment by liuyong** [comment]
![image](https://user-images.githubusercontent.com/664463/58549785-e39fe180-823e-11e9-8261-a43fe0cba6dd.png)

**Comment by jin-yufeng** [comment]
这个是因为里面设置了宽度width:513.359px，超出了屏幕宽度，所以会显示滚动条
![1](https://user-images.githubusercontent.com/48236054/58561561-f70c7600-8259-11e9-9db5-42cdda528e4b.png)  
如果是上面在class中设置了max-width:100%没生效的检查一下是不是把相应的style标签加进去了

**Comment by liuyong** [comment]
原因我知道的，因为帖子是在别的公众号或者其他如135editer和秀米之类的文章拿的HTML片段，不好改，所以能否在库的层级上限制一下 max-width: 100%!important; 之类的

**Comment by jin-yufeng** [comment]
目前可以通过传入tag-style对section标签设置默认效果来解决
`<Parser html="{{html}}" tag-style="{{tagStyle}}">`
`tagStyle:{
  section:"max-width:100%;"
}`
这样会对所有section都设置max-width
另外通配符的话在后端加强包中是可以解析的，有条件的话也可以尝试一下

**Comment by liuyong** [comment]
感谢，这个文本过宽问题解决了，但 [https://github.com/jin-yufeng/Parser/issues/5](url) 中的 transform: translate3d(12px, 0px, 0px); 造成的问题仍在，
i尝试了如下配置却仍不起作用
![image](https://user-images.githubusercontent.com/664463/58567891-d1856980-8265-11e9-99de-b013255a7926.png)
盼复~

**Comment by jin-yufeng** [comment]
这个就不太好解决了，这是平移后超出范围了，可能只能在html中限制宽度了；还有tag-style中只能对html本身的标签设置样式（div,p,section这种）,对rich-text，trees设置是无效的

**Comment by liuyong** [comment]
刚试了，加上overflow: hidden; 就可以了，太谢谢啦。问题解决，结帖
`tagStyle: {
      section: "max-width: 100%!important; overflow: hidden; box-sizing: border-box!important; word-wrap: break-word!important;"
    }`
