### ISSUE TITLE
回调函数@parse="parseHandler"没反应

### ISSUE THREAD

**Issue by chenruifu** [jin-yufeng/Parser#60]
**问题描述**  
uniapp开发环境：回调函数@parse="parseHandler"没反应

**预期的表现**  
应该能打印出解析的node

**实际的表现**  
没反应

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<parser @linkpress="link2Page" @parse="parseHandler" show-with-animation :html="article.content" />

methods: {
  parseHandler(node) {
			console.log(node);
		},
}
```

**Comment by jin-yufeng** [comment]
插件包是不是最新版
传入的 `html` 是不是字符串类型（另外 `H5` 端没有这个回调，因为不进行解析）
都没有问题的话用示例项目试一下
