### ISSUE TITLE
如何支持class 类名 并支持样式

### ISSUE THREAD

**Issue by PlutoCA** [jin-yufeng/Parser#62]
**问题描述**  
好像class 名没有正确解析
```html
// html 片段
"<p class="ql-align-center">这是测试功能的，可删除</p>
<p class="ql-align-right">这是测试功能的，可删除</p>
<ol>
<li class="ql-align-right">2</li>
<li class="ql-align-right">3</li>
<li class="ql-align-right">4</li>
<li class="ql-align-right">2</li>
</ol>"
```
![image](https://user-images.githubusercontent.com/31099607/70987693-5c8f5980-20fb-11ea-85db-c9733efa3320.png)

类名没有正确解析，我在demo里面测试 添加class 样式也没有生效

**Comment by jin-yufeng** [comment]
![1](https://user-images.githubusercontent.com/48236054/70991329-34572900-2102-11ea-9a55-673c9f930adf.png)
是不是版本太老了
