### ISSUE TITLE
font标签的size属性会报错

### ISSUE THREAD

**Issue by HighSpecific** [jin-yufeng/Parser#63]
**问题描述**  
使用最新版的Parser时，font标签的size属性会出错
<font size="100"><b>Color简历小程序相关设计</b></font>

![Snipaste_2019-12-21_18-45-22](https://user-images.githubusercontent.com/16721075/71306937-41d22300-2422-11ea-82aa-8af4f6ab4781.png)

**html代码**  
使用的文本为：
```html
var html = '<font size="100"><b>Color简历小程序相关设计</b></font>';
```

**解决办法**
最后发现是libs/config.js文件的第261行
```
var size = parseInt(attrs.size);
```
修改为
```
var size = parseInt(node.attrs.size);
```

**Comment by jin-yufeng** [comment]
已修复
