### ISSUE TITLE
domain  uni-app包在H5端应该是不自动补全

### ISSUE THREAD

**Issue by likui0632** [jin-yufeng/Parser#64]
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div>Hello World!</div>
```

**Comment by jin-yufeng** [comment]
`domain` 属性在 `H5` 是无效的，浏览器会自动获取 `domain`

**Comment by likui0632** [comment]
感谢大神，我看下怎么可以自动补全，项目图片是单独放的一个目录，浏览器匹配的目录不对！！

**Comment by jin-yufeng** [comment]
如果需要的话可以在 `jyf-Parser/index.vue` 中这个位置添加：
```javascript
if (this.domain && img.getAttribute("src")[0] == "/") {
  if (img.getAttribute("src")[1] == "/")
    img.src = (this.domain.includes("://") ? this.domain.split("://")[0] : "http") + ':' + img.getAttribute("src");
  else img.src = this.domain + img.getAttribute("src");
}
```
![1](https://user-images.githubusercontent.com/48236054/71321613-0b1a0c80-24f7-11ea-989c-62a62600c335.png)
就可以支持 `domain` 属性了（因为浏览器本身就支持拼接，所以原插件包里没有进行处理）

**Comment by likui0632** [comment]
感谢大神,H5端已经可以了，大神辛苦了
