### ISSUE TITLE
图文编辑器-图片滚动位置不对，文字自动靠右

### ISSUE THREAD

**Issue by jason-yiren** [jin-yufeng/Parser#66]
**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/59196388/71405296-ff058a80-266f-11ea-9e7f-8394045a1b4e.png)

**预期的表现**  
图片居中，文字居中

**实际的表现**  
图片右移，文字靠右

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
https://paste.ubuntu.com/p/n3vzCkfv2m/
```

**Comment by jason-yiren** [comment]
图片居中问题麻烦忽略。谢谢

**Comment by jin-yufeng** [comment]
![1](https://user-images.githubusercontent.com/48236054/71407830-18f69b80-2677-11ea-889a-e928b22ba676.png)
你是指这个文字应该居中吗？
这个是因为这个 `section` 设置了 `width: 526px` 导致宽度超出了屏幕范围，所以居中就变成了屏幕的右边
![2](https://user-images.githubusercontent.com/48236054/71407902-53f8cf00-2677-11ea-89a1-fb4c036c384b.png)

**Comment by jason-yiren** [comment]
因为客户直接从356编辑器处理的。我看365那边有个这个标签
.preview-body * {
    max-width: 100%;
}
![image](https://user-images.githubusercontent.com/59196388/71408237-67f10080-2678-11ea-9469-48acfd6628ad.png)

**Comment by jason-yiren** [comment]
目前我想到的是后台输出的时候对超出375px的统一调整375px

**Comment by jin-yufeng** [comment]
可以通过 `tag-style` 属性给 `section` 设置默认的样式 `max-width: 100%`  
```html
<parser html="{{html}}" tag-style="{{tagStyle}}" />
```
```javascript
data: {
  tagStyle:{
    section: "max-width:100%"
  }
}
```
![1](https://user-images.githubusercontent.com/48236054/71409166-8c9aa780-267b-11ea-9f19-3210dbe234b3.png)

**Comment by jason-yiren** [comment]
感谢，已经完成。预祝圣诞快乐
