### ISSUE TITLE
ios真机，头条小程序，图片加载不出来

### ISSUE THREAD

**Issue by tingyuxuan2302** [jin-yufeng/Parser#69]
**问题描述**  
ios真机，头条小程序，图片加载不出来，头条小程序客户端开发工具可以正常展示，而且支付宝小程序真机可以正常加载。

**预期的表现**  
ios真机，头条小程序，图片正常加载

**实际的表现**  
ios真机，头条小程序，图片加载不出来

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div style="margin:auto;line-height: 1.6;font-size: 16px;color: #333333;">   <p style="margin-bottom: 20px;margin-top: 0;">       在二手车市场，一直流传着“一车一况、一况一价”这样的说法。同一款车，因为车况不同，所售价格也不同。最近两年，随着汽车保有量的不断增加，二手车市场越来越受到人们的关注。那么，如何正确评估一辆二手车的价格呢？我们以五菱汽车五菱之光为例，看看二手车评估师怎么说！   </p>          <div style="margin-bottom: 20px;">       <p style="margin: 0 auto;">车辆基本信息：</p>       <p style="margin: 0 auto;">车型：五菱汽车五菱之光2008款 1.0L基本型</p>       <p style="margin: 0 auto;">车型系列：五菱汽车五菱之光</p>       <p style="margin: 0 auto;">上牌时间：2008年09月</p>       <p style="margin: 0 auto;">行驶里程：12.9万公里</p>       <p style="margin:0 auto 20px auto;">新车指导价：3.85万</p>       <img style="margin: auto; display: block; margin-bottom: 20px;max-width: 100%;" src="//pic001.ttpaicdn.com/images/T1J_EvB_dv1RXrhCrK.jpg" alt="">       <p style="margin: 0 auto 20px auto;">车主的这款车于2008年购买，10年车龄，现在想要转手卖掉，可以卖多少钱呢？一起来看下。</p>       <img style="margin: auto; display: block; margin-bottom: 20px;max-width: 100%;" src="//pic001.ttpaicdn.com/images/T1phYvB_LT1RXrhCrK.jpg" alt="">       <p style="margin: 0 auto 20px auto;">该款车2008年上牌启用，行驶12.9万公里，新车指导价3.85万元，车况良好的情况下，成交价0.40万。</p>       <img style="margin: auto; display: block; margin-bottom: 20px;max-width: 100%;" src="//pic001.ttpaicdn.com/images/T1IDCvBvYT1RXrhCrK.jpg" alt="">   </div>   <p style="margin-bottom: 20px;margin-top: 0;">       以上为这款车在各个地区二手车的成交价格，由此可见，影响二手车价格的因素很多，不能单从一两个因素去看。   </p>   <p style="margin-bottom: 20px;margin-top: 0;">      总而言之，二手车评估是一个科学、严谨的事情，这不仅是规范市场的需要，更是对买卖双方的负责。目前中国的二手车评估师很多在这方面做的还不够到位，需要加强。现实生活中如果要买二手车或者卖二手车，最好带一位足够了解车的老司机，帮忙掌掌眼。   </p>   <p style="margin-bottom: 50px;margin-top: 0;">      如果车主想要知道自己的能卖多少钱？欢迎来天天拍车！   </p></div>
```

**Comment by jin-yufeng** [comment]
真机调试一下看看？我没有头条账号也只在开发工具里试过
会不会是真机不支持这种省略协议名的链接？
![微信截图_20191231103813](https://user-images.githubusercontent.com/48236054/71608126-ab3bf980-2bb9-11ea-901f-a7428c315c2f.png)
可以加上协议名之后试一下

**Comment by tingyuxuan2302** [comment]
> 真机调试一下看看？我没有头条账号也只在开发工具里试过
> 会不会是真机不支持这种省略协议名的链接？
> ![微信截图_20191231103813](https://user-images.githubusercontent.com/48236054/71608126-ab3bf980-2bb9-11ea-901f-a7428c315c2f.png)
> 可以加上协议名之后试一下

确实是因为没有协议，真机识别不了造成的，谢谢老哥提醒。
还有个问题，我看老哥这个插件有个参数：domain,但是我设置为https:之后，没有效果，是不是我这种情况不符合呀哈哈。
谢谢🙏，回复的太及时了。

**Comment by jin-yufeng** [comment]
把 `domain` 设置成 `https://` 应该就可以

**Comment by tingyuxuan2302** [comment]
> 真机调试一下看看？我没有头条账号也只在开发工具里试过
> 会不会是真机不支持这种省略协议名的链接？
> ![微信截图_20191231103813](https://user-images.githubusercontent.com/48236054/71608126-ab3bf980-2bb9-11ea-901f-a7428c315c2f.png)
> 可以加上协议名之后试一下

确实是因为没有协议，真机识别不了造成的，谢谢老哥提醒。
还有个问题，我看老哥这个插件有个参数：domain,但是我设置为https:之后，没有效果，是不是我这种情况不符合呀哈哈。
谢谢🙏，回复的太及时了。

> 把 `domain` 设置成 `https://` 应该就可以

老哥，试了一下，好像不行，哈哈，应该是这种情况你没做兼容吧，你有时间可以试一下，我先自己正则匹配一下哈哈哈，感谢感谢
