### ISSUE TITLE
图片变形

### ISSUE THREAD

**Issue by Iamdadousj** [jin-yufeng/Parser#7]
解析出来html图片明显比原图高

**Comment by jin-yufeng** [comment]
是不是图片设置了宽高？可以提供一下html字符串吗

**Comment by Iamdadousj** [comment]
这是数据，图片出来变形





------------------ 原始邮件 ------------------
发件人: "jin-yufeng"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午3:45
收件人: "jin-yufeng/Parser"<Parser@noreply.github.com>;
抄送: "大豆博文"<2425676647@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jin-yufeng/Parser] 图片变形 (#7)




是不是图片设置了宽高？可以提供一下html字符串吗

**Comment by jin-yufeng** [comment]
是不是给img设置了height？数据呢？？？

**Comment by Iamdadousj** [comment]
没有设置，这篇文章直接是微信平台的文章，后台直接给我返回html了




------------------ 原始邮件 ------------------
发件人: "jin-yufeng"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:04
收件人: "jin-yufeng/Parser"<Parser@noreply.github.com>;
抄送: "大豆博文"<2425676647@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jin-yufeng/Parser] 图片变形 (#7)




是不是给img设置了height？数据呢？？？

**Comment by Iamdadousj** [comment]
数据在附件里，我这块是html直接前端处理





------------------ 原始邮件 ------------------
发件人: "jin-yufeng"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:04
收件人: "jin-yufeng/Parser"<Parser@noreply.github.com>;
抄送: "大豆博文"<2425676647@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jin-yufeng/Parser] 图片变形 (#7)




是不是给img设置了height？数据呢？？？

**Comment by jin-yufeng** [comment]
我这儿没有收到附件😂微信文章的要不直接给我网址看一下？

**Comment by Iamdadousj** [comment]
https://xcx.wutom360.com:8003/momentslink/getMomentsHtmlBodyPkg?momentsId=56cbf7b24f40477eb4893bc58f345707




上面是后台接口，返回html的json数据





------------------ 原始邮件 ------------------
发件人: "jin-yufeng"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:16
收件人: "jin-yufeng/Parser"<Parser@noreply.github.com>;
抄送: "大豆博文"<2425676647@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jin-yufeng/Parser] 图片变形 (#7)




我这儿没有收到附件😂微信文章的要不直接给我网址看一下？

**Comment by jin-yufeng** [comment]
我看了一下确实是因为img的style中设置了width和height，因为设置的width超出屏幕大小，被max-width:100%限制，因此宽度小了，高度不变，就变形了
可以试下这样，通过设置tag-style给图片设置自动高度
`<Parser html="{{html}}" tag-style="{{tagStyle}}" />`
`data:{
  tagStyle:{
    img:"height:auto !important"
  }
}`

**Comment by Iamdadousj** [comment]
感谢大佬！已经ok





------------------ 原始邮件 ------------------
发件人: "jin-yufeng"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 下午4:44
收件人: "jin-yufeng/Parser"<Parser@noreply.github.com>;
抄送: "大豆博文"<2425676647@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jin-yufeng/Parser] 图片变形 (#7)




我看了一下确实是因为img的style中设置了width和height，因为设置的width超出屏幕大小，被max-width:100%限制，因此宽度小了，高度不变，就变形了
 可以试下这样，通过设置tag-style给图片设置自动高度
 <Parser html="{{html}}" tag-style="{{tagStyle}}" />
 data:{ tagStyle:{ img:"height:auto !important" } }
