### ISSUE TITLE
支持jpeg动图吗？ 

### ISSUE THREAD

**Issue by bfwinxp** [jin-yufeng/Parser#70]
我这里有个jpeg的动图，发现用这个解析以后一直空白不能加载

**Comment by jin-yufeng** [comment]
以实际情况为准吧，不能加载应该就不行
图片是用 `rich-text` 的 `img` 显示的，可以单独放在里面试一下
另外 `jpeg` 动图是指 `gif` 吗？我试过我这个 `gif` 是可以显示的 `https://6874-html-foe72-1259071903.tcb.qcloud.la/demo1-3.gif?sign=4dd623d040aba5e2ca781e9e975800bd&t=1560247351`
