### ISSUE TITLE
文本中有序号时，文案不对齐怎么处理，详情见图

### ISSUE THREAD

**Issue by caiqiuxia** [jin-yufeng/Parser#75]
![image](https://user-images.githubusercontent.com/20104546/72197702-11990580-345f-11ea-964d-df27ee82122c.png)

**Comment by jin-yufeng** [comment]
这个应该是 `rich-text` 显示的 `ol` 和 `ul`？

**Comment by caiqiuxia** [comment]
不是的，我本地文本的问题。
再问一个问题，预览大图支持仅单张预览吗？

**Comment by jin-yufeng** [comment]
可以左右滑动查看所有图片的
