### ISSUE TITLE
一些属性定义的问题

### ISSUE THREAD

**Issue by waxJava2615** [jin-yufeng/Parser#76]
trees.js中的这个方法
tapEvent(e) {
      console.log(this);
      if (!this._top) return;
      var jump = true,
        attrs = e.currentTarget.dataset.attrs;
      attrs.ignore = () => jump = false;
      this._top.triggerEvent('linkpress', attrs);
其中this._top是在哪里定义的呢！一直没有看明白，新手一枚。

**Comment by jin-yufeng** [comment]
这个插件的结构是顶层一个 `parser` 组件，下面是递归的 `trees` 组件，这个 `this._top` 就是指向顶层的 `parser` 组件，定义在 `index.js` 中 237 行 `node._top = this;`

**Comment by waxJava2615** [comment]
想请问一下您是直接将这个写进了node的结构里面吗？这样写有什么便捷之处吗？
发自我的iPhone

**Comment by jin-yufeng** [comment]
在 `trees` 组件中会用到一些全局的信息，比如说图片预览的时候，需要从顶层组件获取所有图片的数组，还有 `autopreview` 属性的值等，都需要通过 `_top` 获取

**Comment by waxJava2615** [comment]
明白了我 就是说这样也能调用到对吧。  新手 第一次看到这个写法。直接写到node里面也能调用。就有点奇怪……。新手一枚。

发自我的iPhone
