### ISSUE TITLE
2020.1.22 在小程序中直接报错

### ISSUE THREAD

**Issue by sweetXiaoyan** [jin-yufeng/Parser#78]
你好, 我直接运行示例项目, 使用在小程序中运行, 也报同样的错误,这是保错的截图: 
http://img.xiaogangzai.cn/1579659087(1).png
![](http://img.xiaogangzai.cn/1579659087(1).png)

**Comment by jin-yufeng** [comment]
`Hbuilder X` 的版本是多少？

**Comment by sweetXiaoyan** [comment]
> `Hbuilder X` 的版本是多少？

版本是: 2.1.3.20190723

**Comment by jin-yufeng** [comment]
需要`2.2.5`以上，否则`wxs`编译不了，升级一下吧

**Comment by sweetXiaoyan** [comment]
> 需要`2.2.5`以上，否则`wxs`编译不了，升级一下吧

好的, 谢谢,
