### ISSUE TITLE
可以改成遵守easycom规则么？

### ISSUE THREAD

**Issue by he426100** [jin-yufeng/Parser#79]
**新功能描述**  
修改后就无需引入了，可以直接使用

**应用场景**

**Comment by jin-yufeng** [comment]
可以具体点吗？没有了解过

**Comment by he426100** [comment]
[easycom](https://uniapp.dcloud.io/collocation/pages?id=easycom)

> 传统vue组件，需要安装、引用、注册，三个步骤后才能使用组件。easycom将其精简为一步。只要组件安装在项目的components目录下，并符合components/组件名称/组件名称.vue目录结构的组件。就可以不用引用、注册，直接在页面中使用。同时打包后会自动剔除没有使用的组件。
自HBuilderX 2.5.5起支持easycom组件模式。可以在HBuilderX新建项目界面选择uni-ui项目模板体验。只需在页面中敲u，拉出大量代码块，直接选择，即可使用。大幅提升开发效率，降低使用门槛。
在uni-app插件市场下载符合components/组件名称/组件名称.vue目录结构的组件后，也可以直接使用。

**Comment by jin-yufeng** [comment]
最新版已修改为符合要求
