### ISSUE TITLE
公众号文章直接复制的html代码，图片无法解析出来

### ISSUE THREAD

**Issue by ehcsa** [jin-yufeng/Parser#8]
比如这个，也可能是嵌套比较深？
`<img class="rich_pages" data-copyright="0" data-ratio="0.9795918367346939" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/a1HupTryX2wRibph6FWHPMQDMXuA17Zu03pBEB3GKBDpjSTiaoPZ0SUPbOV4Fr22uQBAGr92wDF4OiaibvW8UWoic2g/640?wx_fmt=png" data-type="png" data-w="147" style="">`

文章页面如下：
https://mp.weixin.qq.com/s?__biz=MzA3MTA0ODYyOA==&mid=2651155714&idx=1&sn=e2a8aeb4c22b8d8be284431c509fe304&chksm=84c241d9b3b5c8cf59ad83a79d8845fe63e4ef1d6aa4d09579cd4c5fe24cf2ce636aa133fdaa&scene=21#wechat_redirect

**Comment by jin-yufeng** [comment]
公众号文章直接复制的代码，`img`标签都是只有`data-src`属性，没有`src`属性的（网页上是在`js`脚本里动态的把`data-src`赋给`src`的）；因此直接是无法显示的
现在最新版已经默认在没有`src`时自动把`data-src`赋给`src`了，可以重新下载一下试试；之前的版本可以在`DomHandler.js`里一百多行的地方把这段注释打开也可以的，你可以试一下
![1](https://user-images.githubusercontent.com/48236054/59081533-3190a580-8921-11e9-9d69-8013ae3bfd6e.png)

**Comment by moshanghan** [comment]
@ehcsa 您好，我遇到了类似的问题，请问，渲染公众号文章需要做额外处理吗？
#259
