### ISSUE TITLE
解析 会带< 

### ISSUE THREAD

**Issue by hellozhang** [jin-yufeng/Parser#80]
**问题描述**  
请详细描述遇到的问题（可附图）

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<p class="Style0" style="margin-left:21.0pt;text-indent:-21.0pt;"><span style="font-size:14px;">1、外出旅行请各位游客务必携带好本人身份证，注意人身及财产安全，看管好自己的小孩，</span> </p><p class="MsoBodyTextIndent3" style="margin-left:0cm;"><span style="font-size:14px;">2、为让旅游更安心，建议游客购买旅游意外险；</span> </p><p class="MsoBodyTextIndent3" style="margin-left:0cm;"><span style="font-size:14px;">3、如遇不可抗力因素，延误团队行程，按旅游法相关条款所超出费用由客人自理；</span> </p><p><br /></p>
```
<p class="Style0" style="margin-left:21.0pt;text-indent:-21.0pt;"><span style="font-size:14px;">1、外出旅行请各位游客务必携带好本人身份证，注意人身及财产安全，看管好自己的小孩，</span> </p><p class="MsoBodyTextIndent3" style="margin-left:0cm;"><span style="font-size:14px;">2、为让旅游更安心，建议游客购买旅游意外险；</span> </p><p class="MsoBodyTextIndent3" style="margin-left:0cm;"><span style="font-size:14px;">3、如遇不可抗力因素，延误团队行程，按旅游法相关条款所超出费用由客人自理；</span> </p><p><br /></p>

**Comment by jin-yufeng** [comment]
具体是什么问题？

**Comment by hellozhang** [comment]
就是 parse 后，输出带<

**Comment by jin-yufeng** [comment]
截个图？我这里没看到问题
![微信截图_20200217200225](https://user-images.githubusercontent.com/48236054/74652206-7b27d480-51c0-11ea-93d6-bdd057a01053.png)
