### ISSUE TITLE
遇到图片尺寸表现不一致的情况

### ISSUE THREAD

**Issue by Mrdoge** [jin-yufeng/Parser#81]
一个是图片会超出显示范围
![ec2e3a6722b84874e664c2303a6df6f](https://user-images.githubusercontent.com/23443852/74554937-9bc01680-4f95-11ea-8ced-699baca90357.png)

另外就是图片并排的时候小程序没效果
![1a773e54e45b2a958738a942e05f1e4](https://user-images.githubusercontent.com/23443852/74554943-9d89da00-4f95-11ea-9492-3e67f639dff9.png)

问题代码：
[问题文章.txt](https://github.com/jin-yufeng/Parser/files/4205911/default.txt)

**Comment by jin-yufeng** [comment]
第一个问题，我这边看向右滑动的时候是可以看到完整的图片的，只是整个框被缩进了 `20px` ，这是因为这个框前面有一个 `20px` 的 `section`  
![3](https://user-images.githubusercontent.com/48236054/74582670-c2179d80-4ff9-11ea-98cb-3da2177c8d54.png)

------

第二个问题主要是屏幕宽度不够并排显示吧
![4](https://user-images.githubusercontent.com/48236054/74582698-102ca100-4ffa-11ea-9e25-b07f9649fa62.png)
两个 `section` 都是 `inline-block` 且设置了 `width`，即使是 `max-width:100%` 也只能限制每一个都不超过父级的宽度，不能让两个图片的宽度之和不超过 `100%`
不过，这里都有设置 `data-width:50%`，如果把这个转为 `width`，可以解决这个问题
只要在 `config.js` 里的 `trustAttrs` 里增加 `data-width`，然后在 `LabelAttrsHandler` 里添加 
```javascript
if(node.attrs["data-width"])
      node.attrs.style += ";width:" + node.attrs["data-width"];
```
就可以解决这个问题
![5](https://user-images.githubusercontent.com/48236054/74582853-060ba200-4ffc-11ea-963d-fb17fa94a898.png)
![6](https://user-images.githubusercontent.com/48236054/74582858-0d32b000-4ffc-11ea-8764-9da86bf37431.png)

**Comment by Mrdoge** [comment]
像第一种问题有没有什么解决方案呀。我这边是想在小程序上的富文本展示尽量贴近网页版的处理方式，目前被用户诟病比较多也是这块。。
之前想到过遇到富文本的情况直接在小程序跳转webview了，但是遇到商品详情这种需要原生代码 + 富文本的就gg了

**Comment by jin-yufeng** [comment]
个人感觉这种从网页上移植来的可能由于缺少了一些 `style` 或者一些样式是由 `js` 动态设置的或者过于复杂等原因，偶尔遇到些问题挺难免的
可能也只能碰到时去修改 `html` 的内容，想要完全自动处理还是挺难的

**Comment by jin-yufeng** [comment]
参考：[显示公众号网页](https://jin-yufeng.github.io/Parser/#/instructions?id=%e6%98%be%e7%a4%ba%e5%85%ac%e4%bc%97%e5%8f%b7%e7%bd%91%e9%a1%b5)  
试了一下，效果不错  
![1](https://user-images.githubusercontent.com/48236054/74707946-259e0700-5256-11ea-873f-bdb1b7e5c335.png)
![2](https://user-images.githubusercontent.com/48236054/74707951-29ca2480-5256-11ea-96dc-c08fd6bedc24.png)

**Comment by Mrdoge** [comment]
辛苦了，试试先

**Comment by Mrdoge** [comment]
用了CssHandler.js，还是不行呀
![image](https://user-images.githubusercontent.com/23443852/74763900-9a575c80-52bb-11ea-8e9f-7cd7e63d8e32.png)

**Comment by jin-yufeng** [comment]
那一堆自带的 `style` 保留了吗
![1](https://user-images.githubusercontent.com/48236054/74796033-7834fd00-5302-11ea-8037-7243bbd66f2a.png)
试试这个 [代码片段](https://developers.weixin.qq.com/s/WOo3Xfml7nfR)
