### ISSUE TITLE
页面打开时会出现白屏的情况

### ISSUE THREAD

**Issue by snakelenas** [jin-yufeng/Parser#82]
**问题描述**   

1. 一打开会出现白屏，如下图
https://www.gejuptx.com/user/issue/1.jpg

2. 然后要点一下空白的部分，即预览图片后，一旦出现图片了
https://www.gejuptx.com/user/issue/2.jpg

3. 关掉图片预览，回去看就正常了
https://www.gejuptx.com/user/issue/3.jpg

如果白屏状态，一直不操作，那么它一直都白屏，不是图片加载慢的问题

  
**html代码**  

```html
 <p>
    课程时间：2020年2月28日 16:00-17:00&nbsp;
</p>
<p>
    收听本次课程方式：保存下方👇海报到相册，然后微信扫描海报二维码进入！
</p>
<p>
    <img src="/cdnres/Editor/200228/F2SvRO7IXv0UNNxT.jpeg">
</p>
```

domain 为 https://www.gejuptx.com/

**Comment by jin-yufeng** [comment]
是哪个平台呢（还是都会）？

**Comment by snakelenas** [comment]
只做了 微信小程序 和 安卓版本，
微信小程序 如上面所述，
安卓版本出现的几率小一些，但也有出现，我已截图

https://www.gejuptx.com/user/issue/4.jpg

您看看

**Comment by jin-yufeng** [comment]
用这个示例项目试试看？ [test.zip](https://github.com/jin-yufeng/Parser/files/4269838/test.zip)  
我好像没复现问题
![微信截图_20200229104455](https://user-images.githubusercontent.com/48236054/75599519-9f4cb500-5ae0-11ea-9ef0-4842549b1060.png)

**Comment by snakelenas** [comment]
您再得多点几次，

然后，我这2天抽个时间，剥离掉其它页面，单独做个能重现的页面，再发您

**Comment by snakelenas** [comment]
[Parser - 副本.zip](https://github.com/jin-yufeng/Parser/files/4270044/Parser.-.zip)

https://www.gejuptx.com/user/issue/Parsertest.zip

这个可以重现，点击25次，出现2次

得以微信小程序预览 模式启动，如果是调试或者 开发者工具是不会出现这个问题。

还有一个是 我的机器 iphone7p, 另一个微信安卓 尺寸大，也不会出现。

是不是和某种计算页面尺寸有关系？

**Comment by jin-yufeng** [comment]
是说真机上点击预览图片，再关掉，这样重复多次时有时会变成空白？

**Comment by jin-yufeng** [comment]
我用 华为 P10 Plus 试了三十多次都没有出现
这种偶现的就比较麻烦了

**Comment by jin-yufeng** [comment]
有没有可能是这样，这种较大的图片，有一定概率（在网络条件较差的时候）加载失败，然后预览的时候可能超时的时间较长能够加载出来这样？
图片是由 `rich-text` 显示的，预览是通过原生的 `previewImage`，具体原理我也不太清楚

**Comment by snakelenas** [comment]
> 是说真机上点击预览图片，再关掉，这样重复多次时有时会变成空白？

不是这个意思，我录个视频

**Comment by snakelenas** [comment]
https://www.gejuptx.com/user/issue/5.mp4

**Comment by snakelenas** [comment]
有一定几率会白屏，数据其实已经加载了，但如果不点一下 图片进行 预览，那么等多久它都是白屏，一旦点下预览，就好了

**Comment by snakelenas** [comment]
> 有没有可能是这样，这种较大的图片，有一定概率（在网络条件较差的时候）加载失败，然后预览的时候可能超时的时间较长能够加载出来这样？
> 图片是由 `rich-text` 显示的，预览是通过原生的 `previewImage`，具体原理我也不太清楚

网络很好，如果只是图片还是可以区别的，但是 连文字 都一起不渲染，只有 点了 预览后，文字才出来

**Comment by jin-yufeng** [comment]
把 `show-with-animation` 属性去掉试试看？

**Comment by snakelenas** [comment]
> 把 `show-with-animation` 属性去掉试试看？

好 我马上试试

**Comment by snakelenas** [comment]
抓到他了，就是 show-with-animation 的问题

出问题的代码
`<jparser gesture-zoom show-with-animation lazy-load use-anchor ref="rtf" @linkpress="uParseNavigate" :domain="domain">加载中...</jparser>`

去掉后  show-with-animation 我点击了50次，一次都没有白屏

**Comment by jin-yufeng** [comment]
因为设置了 `show-with-animation` 会先把内容设成透明，再通过动画变成不透明
这么说这个动画会概率性失效，然后就一直透明了
有空的话可以真机调试一下看看加上动画出问题时顶层的这个 `trees` 组件的样式是什么情况（正常应该是这样）
![微信截图_20200229170755](https://user-images.githubusercontent.com/48236054/75604657-16e90700-5b16-11ea-9875-5d4b3abd0fde.png)

**Comment by snakelenas** [comment]
调试是不出现这个问题的，因为 微信的调试 和 预览 使用的引擎还是有差异的。 我只能通过代码 传教查询

你的预判是对的

![6](https://user-images.githubusercontent.com/16239691/75605438-cd9cb580-5b1d-11ea-8a9c-1ca6144acd4a.jpg)

https://www.gejuptx.com/user/issue/6.jpg
![7](https://user-images.githubusercontent.com/16239691/75605442-d1c8d300-5b1d-11ea-8acd-69c37c899836.jpg)

https://www.gejuptx.com/user/issue/7.jpg


你还需要什么信息，我再帮你查

**Comment by jin-yufeng** [comment]
谢谢，再试一下给这个设个延时试试
![微信截图_20200229185801](https://user-images.githubusercontent.com/48236054/75606224-8a464500-5b25-11ea-849b-f233edd955dd.png)

**Comment by snakelenas** [comment]
按照你说的改了，试了50次，没有问题

**Comment by jin-yufeng** [comment]
这样的话应该是时序问题，可能是偶尔组件还没创建的时候动画先设置了导致失效，我看看能不能优化一下

**Comment by snakelenas** [comment]
好的，需要我验证或做什么事，随时

**Comment by taoqiyang** [comment]
帮大忙了  我这也有这个问题。 主要是iphone出出概率大点，  测试同学自己的iphone微信版本7.0.8出现概率挺大的有1/3左右， 我用另一个iphone微信版本7.0.10一直复现不了。

**Comment by jin-yufeng** [comment]
@snakelenas 麻烦有空试一下这个版本有没有问题
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4271615/jyf-parser.zip)

**Comment by snakelenas** [comment]
好的，今天外出，现在才回到电脑面前，马上试试

**Comment by snakelenas** [comment]
很可惜，不行，问题依旧， 15次里有3次出现， opacity为0

**Comment by jin-yufeng** [comment]
那再试试这个
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4271904/jyf-parser.zip)

**Comment by snakelenas** [comment]
机率好像小了些， 70次出现了5次 ， opacity为0

**Comment by jin-yufeng** [comment]
太难了，延时久了又怕影响体验

**Comment by jin-yufeng** [comment]
最后试一下这样吧
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4271934/jyf-parser.zip)

**Comment by jin-yufeng** [comment]
最后试试这样吧，用了 `css3` 的 `animation`
[jyf-parser.zip](https://github.com/jin-yufeng/Parser/files/4271968/jyf-parser.zip)

**Comment by snakelenas** [comment]
bingo! 试了50次，都很OK！

**Comment by jin-yufeng** [comment]
太棒了！！

**Comment by snakelenas** [comment]
太不容易了你~ 点赞

**Comment by snakelenas** [comment]
奇怪，现在轮到 安卓 出问题了 ，
文字渲染出来了，但是图片 是个框，点击能预览，关闭预览 还是个框 

https://www.gejuptx.com/user/issue/4.jpg
