### ISSUE TITLE
图片的懒加载 lazy-load 属性开启没有生效，使用了 原生开发的引入方式

### ISSUE THREAD

**Issue by liangjuncheng1995** [jin-yufeng/Parser#84]
![image](https://user-images.githubusercontent.com/30004721/75769416-17d1a100-5d81-11ea-90ac-c909057cccfe.png)

在设备的第一屏，已经将文章的所有图片的资源已经加载了

![image](https://user-images.githubusercontent.com/30004721/75769561-59fae280-5d81-11ea-901c-cbccc2a37955.png)

**Comment by jin-yufeng** [comment]
看看这里提到的问题能不能解决（主要是内容是否足够长）？[图片懒加载问题](https://jin-yufeng.github.io/Parser/#/instructions?id=%e5%9b%be%e7%89%87%e6%87%92%e5%8a%a0%e8%bd%bd%e9%97%ae%e9%a2%98)

**Comment by liangjuncheng1995** [comment]
![image](https://user-images.githubusercontent.com/30004721/75836624-73417480-5dfd-11ea-8fa9-1e8742b6fa37.png)
懒加载问题的第二点是 整个文章，就是整个被撑开的富文本是否超过 1000px 的意思吗
内容显示的长度是有 1万多的，不知道这个高度是否是 时机的问题
![image](https://user-images.githubusercontent.com/30004721/75836762-d6330b80-5dfd-11ea-9ea3-057569cb98ff.png)

**Comment by jin-yufeng** [comment]
可以提供一个代码片段吗？

**Comment by liangjuncheng1995** [comment]
![image](https://user-images.githubusercontent.com/30004721/75837060-b6501780-5dfe-11ea-8ebb-e42a304391d8.png)
也设置了图片的最小高度
![image](https://user-images.githubusercontent.com/30004721/75837098-cc5dd800-5dfe-11ea-840b-6f196f5145f0.png)

**Comment by liangjuncheng1995** [comment]
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>在动漫中，我们经常能看到这样的景象，那就是女主一方战败，在无可奈何之下，自己惨遭地方囚禁，有的甚至遭到了敌人的羞辱，她们虽然奋力抵抗，但却无济于事，只好苦苦等待着男主来解救自己，今天我们就来欣赏几位惨遭囚禁的女神。</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>saber</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox"><img src="http://image.uc.cn/s/wemedia/s/upload/2020/49623570a4f8c381705f6fd5064f2291.png" d-h="485" d-w="842"></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>武力强盛的saber竟然也会有这样的遭遇？这是让很多人都想不到的事情。她被caster用咒术捕获，身穿白色婚纱，白皙的肌肤让人垂涎欲滴，脸红的瞬间好像能看到她那清澈的眸子在慢慢变得迷乱，saber虽然知道自己并没有生命危险，而且也知道自己能随时逃脱，但是她好像更加享受被调x的感觉。</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>这一段可以说是我见过saber所有姿势中最美的，她没有穿上厚厚的盔甲，一身白色的婚纱，吹弹可破的白色肌肤，真是美到极致。</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox text-image"><img src="http://image.uc.cn/s/wemedia/s/upload/2020/49dac3974ded3eee1e817a0ea180afbe.png" d-h="458" d-w="688"></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox_desc"><span>亚丝娜</span></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>看过这部动漫的应该都知道，亚丝娜可是没少遇到过这样的事情，她被关在笼子里面，以前总以为她是一位傲娇大小姐，没想到也会有屈服的一面 ，没想到她竟然会被敌人羞辱到这般地步，让桐人老爷的脸可往哪放啊，亚丝娜刚开始还有点不从，但是后来就不再有任何反抗了，因为她知道自己的处境，因为她知道自己只有这样做才能解脱......慢着，剧情可能让我给搞混了。</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox"><img src="http://image.uc.cn/s/wemedia/s/upload/2020/32bf7a231a84787cf5bf48533713aede.png" d-h="378" d-w="667"></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox_desc"><span class="1582449426979_0">被困住的天使</span></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>其实我并没有看这部动漫，而是听我一个朋友说的，其中的女主非常凄惨，每天都过着被欺辱的生活，可是她有没办法反抗，也没有人来拯救她，她的身体和心灵上遭受到了重创......心理脆弱的观众还是远离这样的动漫比较好。</p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class="imgbox"><img src="http://image.uc.cn/s/wemedia/s/upload/2020/8f02997f0d38ed2b3b4a3ce248973d07.png" d-h="453" d-w="613"></p>
<p style="margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;"class="content-p" class>最后，这些囚禁的天使虽然在某些时候能给人一种别样的美，但是这种畸形的爱却不是所有人都能承受的，也是希望我们不会遭遇到这样的事情。</p>

### **上面是后台返回的原数据**

**Comment by liangjuncheng1995** [comment]
"<p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>在动漫中，我们经常能看到这样的景象，那就是女主一方战败，在无可奈何之下，自己惨遭地方囚禁，有的甚至遭到了敌人的羞辱，她们虽然奋力抵抗，但却无济于事，只好苦苦等待着男主来解救自己，今天我们就来欣赏几位惨遭囚禁的女神。</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>saber</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox\"><img src=\"http://image.uc.cn/s/wemedia/s/upload/2020/49623570a4f8c381705f6fd5064f2291.png\" d-h=\"485\" d-w=\"842\"></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>武力强盛的saber竟然也会有这样的遭遇？这是让很多人都想不到的事情。她被caster用咒术捕获，身穿白色婚纱，白皙的肌肤让人垂涎欲滴，脸红的瞬间好像能看到她那清澈的眸子在慢慢变得迷乱，saber虽然知道自己并没有生命危险，而且也知道自己能随时逃脱，但是她好像更加享受被调x的感觉。</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>这一段可以说是我见过saber所有姿势中最美的，她没有穿上厚厚的盔甲，一身白色的婚纱，吹弹可破的白色肌肤，真是美到极致。</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox text-image\"><img src=\"http://image.uc.cn/s/wemedia/s/upload/2020/49dac3974ded3eee1e817a0ea180afbe.png\" d-h=\"458\" d-w=\"688\"></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox_desc\"><span>亚丝娜</span></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>看过这部动漫的应该都知道，亚丝娜可是没少遇到过这样的事情，她被关在笼子里面，以前总以为她是一位傲娇大小姐，没想到也会有屈服的一面 ，没想到她竟然会被敌人羞辱到这般地步，让桐人老爷的脸可往哪放啊，亚丝娜刚开始还有点不从，但是后来就不再有任何反抗了，因为她知道自己的处境，因为她知道自己只有这样做才能解脱......慢着，剧情可能让我给搞混了。</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox\"><img src=\"http://image.uc.cn/s/wemedia/s/upload/2020/32bf7a231a84787cf5bf48533713aede.png\" d-h=\"378\" d-w=\"667\"></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox_desc\"><span class=\"1582449426979_0\">被困住的天使</span></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>其实我并没有看这部动漫，而是听我一个朋友说的，其中的女主非常凄惨，每天都过着被欺辱的生活，可是她有没办法反抗，也没有人来拯救她，她的身体和心灵上遭受到了重创......心理脆弱的观众还是远离这样的动漫比较好。</p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class=\"imgbox\"><img src=\"http://image.uc.cn/s/wemedia/s/upload/2020/8f02997f0d38ed2b3b4a3ce248973d07.png\" d-h=\"453\" d-w=\"613\"></p><p style=\"margin-bottom:50rpx;font-size:40rpx;line-height:68rpx;letter-spacing:2px;text-align: justify;\"class=\"content-p\" class>最后，这些囚禁的天使虽然在某些时候能给人一种别样的美，但是这种畸形的爱却不是所有人都能承受的，也是希望我们不会遭遇到这样的事情。</p>"

**Comment by liangjuncheng1995** [comment]
上面是后台返回的原数据

**Comment by liangjuncheng1995** [comment]
GitHub 的富文本好像把 </p>闭合的标签去掉了，你可以模拟下数据可以 传入html 的里面调用组件试试

**Comment by jin-yufeng** [comment]
![微信截图_20200304100714](https://user-images.githubusercontent.com/48236054/75837507-05e31300-5e00-11ea-9ef3-9304bdfea114.png)
我这里看高度是 `2423px` ，在可视范围以下 `1000px` 内的图片会被加载（即图片的位置要在屏幕高度加 `1000px` 以外的才会先不加载），所以会被全部加载

**Comment by liangjuncheng1995** [comment]
这个 1000px 这个值 在插件里面可以设置小点的吗

**Comment by jin-yufeng** [comment]
可以，在
![微信截图_20200304100714](https://user-images.githubusercontent.com/48236054/75837833-fa441c00-5e00-11ea-955f-3dcf48ac5652.png)
不过设的太小可能导致下滑的时候图片还没加载出来

**Comment by liangjuncheng1995** [comment]
我下载的插件的版本是不是 不是最新的？
我这个好像是压缩版 
![image](https://user-images.githubusercontent.com/30004721/75838854-1c8a6980-5e02-11ea-9a32-e1f76f42a09a.png)

**Comment by jin-yufeng** [comment]
改 `bottom`，`bottom` 表示视图以下 `1000px`

**Comment by liangjuncheng1995** [comment]
![image](https://user-images.githubusercontent.com/30004721/75839239-50b25a00-5e03-11ea-99b0-f21954a6d128.png)

**Comment by liangjuncheng1995** [comment]
嗯，已经可以了
