### ISSUE TITLE
关于组件事件 的问题 bindready （渲染完成时触发）

### ISSUE THREAD

**Issue by liangjuncheng1995** [jin-yufeng/Parser#85]
bindready 事件是指富文本数据加载完成之后产生的回调吗
因为我这边的需求是 要拿到整个富文本的高度
![image](https://user-images.githubusercontent.com/30004721/75770110-5025af00-5d82-11ea-84b7-c09ec66b321e.png)
在组件 添加 bindready 的事件 的时候 ，返回的对象的里面并没有 boundingClientRect 属性

因为看到文档会返回 boundingClientRect  的属性

![image](https://user-images.githubusercontent.com/30004721/75770209-85320180-5d82-11ea-9d27-79a2af006187.png)

而真实 的情况会被调用 三次这个回调，也没有返回 对应的  boundingClientRect属性，
![image](https://user-images.githubusercontent.com/30004721/75770359-be6a7180-5d82-11ea-9b12-f551c10608fe.png)

为什么呢？请大神指教

**Comment by jin-yufeng** [comment]
`e.detail` 里的 `width`, `height`, `left`, `right` 等就是 `boundingClientRect` 的返回结果，没有一个 `boundingClientRect` 属性的（`e.detail.height` 就是高度）
不过这个回调只能说明所有节点已经被添加，不能确定图片已经加载完毕，因此加载完后高度还是可能增加的（这确实是个问题，因为等待所有图片加载完毕可能时间比较长，处理起来也复杂一点），如果要获取最终的高度，可能还要加一个延时后再查询
至于触发了三次，目前是每设置一次 `html` 都会触发一次（包括初始设置为空），可能是这个问题

**Comment by jin-yufeng** [comment]
考虑增加一个图片加载完毕的周期返回准确的高度

**Comment by liangjuncheng1995** [comment]
明白意思了，谢谢回答

**Comment by jin-yufeng** [comment]
最新版的 `ready` 事件中应该已经可以获取到准确的大小了（等图片加载完才触发，但延时较长，原来的 `ready` 事件改成了 `load` 事件（`dom` 加载完毕））

**Comment by liangjuncheng1995** [comment]
好的，我试试

**Comment by liangjuncheng1995** [comment]
![image](https://user-images.githubusercontent.com/30004721/76376272-e0678380-6382-11ea-9644-e070e5d0b06e.png)
下载了最新版本，可是ready 事件会一直在触发

**Comment by liangjuncheng1995** [comment]
load 事件没有预测准确计算出渲染完之后的高度

**Comment by jin-yufeng** [comment]
给我个代码片段？  
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by liangjuncheng1995** [comment]
https://developers.weixin.qq.com/s/n3q4OLmq7Sfi

**Comment by liangjuncheng1995** [comment]
我是在中间 多做了 一个组件引入富文本的组件，之前在 页面上直接调用富文本是不会有问题的

**Comment by liangjuncheng1995** [comment]
我好像找到原因了，组件的数据传输换了变量
![image](https://user-images.githubusercontent.com/30004721/76381708-24fa1b80-6391-11ea-973f-f638279a6697.png)

**Comment by liangjuncheng1995** [comment]
是不是 组件里面的 properties 和 data 下面的属性不能设置成同一个属性名称

**Comment by jin-yufeng** [comment]
一直触发 `ready` 是有个 `bug`（原理是每 `350ms` 检查一次高度，不再变化后触发（并清除计时器），如果前一次还没有触发就再次设置了数据，就会导致前一次的计时器没有被清除而不停触发）
不过你这里只要有 `properties` 就可以了，`data` 和 `attached` 都是不必要的，去掉就不会这样了
![微信截图_20200311122904](https://user-images.githubusercontent.com/48236054/76382518-f6317480-6393-11ea-8984-71fbf3991bc8.png)

**Comment by jin-yufeng** [comment]
一直触发的 `bug` 修复了

**Comment by liangjuncheng1995** [comment]
你好，又来打扰你了
这个问题最终想拿到的是 这个富文本插件渲染完成后，这个组件整个高度，因为需求需要 
拿到这个高度
可是在具体情况中还是 会出现高度缺少的情况
ready 返回的高度：
![image](https://user-images.githubusercontent.com/30004721/76820541-751c2680-6846-11ea-9ad3-6798a9350326.png)

在开发者工具上抓取的高度：

![image](https://user-images.githubusercontent.com/30004721/76820584-91b85e80-6846-11ea-9150-37b63a2de83c.png)
