### ISSUE TITLE
点击富文本的链接，出现 内容已复制 tip 提示

### ISSUE THREAD

**Issue by godkun** [jin-yufeng/Parser#86]
**问题描述**  

如图所示：

![image](https://user-images.githubusercontent.com/26134303/76521025-f8ccc080-649e-11ea-9be1-5ad94077e2fb.png)

我在搜索parser组件内容时，并没有发现 内容已复制 关键字，这是在哪设置的呢

**Comment by jin-yufeng** [comment]
在这里
![微信截图_20200312213517](https://user-images.githubusercontent.com/48236054/76527028-74cc0600-64a9-11ea-90be-7926d6b97b39.png)
如果不需要的话在 `bindlinkpress` 事件中调用 `e.detail.ignore` 函数即可
```html
<parser bindlinkpress="linkpress">
```
```javascript
linkpress(e) {
  e.detail.ignore();
}
```
