### ISSUE TITLE
a 标签 换行了

### ISSUE THREAD

**Issue by shengbowen** [jin-yufeng/Parser#87]
**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/5378783/76673914-feccb980-65e4-11ea-9a99-430226265a55.png)
一段带a 标签的问题，出现了换行，请问有什么办法可以避免吗

**预期的表现**  
请描述预期的表现
a 标签后文本不换行

**实际的表现**  
请描述实际的表现
a标签后文本换行了
**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<p>自从1月31日<a style="color: #295FCC; text-decoration: underline" href="chat?key=世界卫生组织">世界卫生组织</a>（WHO）宣布将新型冠状病毒<a style="color: #295FCC; text-decoration: underline" href="chat?key=疫情">疫情</a>列为&ldquo;国际关注的突发公共卫生事件（PHEIC）&rdquo;以来，本次<a style="color: #295FCC; text-decoration: underline" href="chat?key=疫情">疫情</a>对经济的负面影响，便成了热点话题。</p><p>&nbsp;</p>
```

**Comment by shengbowen** [comment]
好像是 &ldquo; 导致的，把他换成“ 就好了

**Comment by jin-yufeng** [comment]
确实有这个问题，因为 `&ldquo;` 这种实体是通过 `rich-text` 显示的（自行处理的话这种实体非常多，会大大增加大小），而 `rich-text` 无法被设置成 `inline`，所以就变成了这个样子，我看看能不能解决

**Comment by jin-yufeng** [comment]
已修复

**Comment by shengbowen** [comment]
> 已修复

非常感谢，很及时啊，不过发现iphone在系统版本比较低（ios9.3.3）的系统下，所有的链接多换行了，这个是不是无解了

**Comment by jin-yufeng** [comment]
可以真机调试一下看看？
