### ISSUE TITLE
相对路径的图片无法正常

### ISSUE THREAD

**Issue by wearwlnd** [jin-yufeng/Parser#9]
![image](https://user-images.githubusercontent.com/6396728/59670410-7c969c80-91ee-11e9-9495-762172e04f08.png)

**Comment by jin-yufeng** [comment]
这是本地图片？

**Comment by wearwlnd** [comment]
> 这是本地图片？

这个是编辑器里面上传的图片  保存的路径是相对路径

**Comment by wearwlnd** [comment]
> 这是本地图片？

我在trees.wxml里面把data-src的路径补充完整，DomHandler.js里面的
if (attrs['data-src']) {
        attrs.src = attrs.src || attrs['data-src'];
        delete attrs['data-src'];
      }
好像不起作用 不知道是什么原因

**Comment by jin-yufeng** [comment]
那个是在没有src时把data-src赋给src，有src的时候就不起效果了；而且wxml里的data-src是用来点击预览用的；没有办法直接把src补充完整吗？

**Comment by jin-yufeng** [comment]
在后端加强包里是可以通过设置domain来自动把src补全的，前端插件包暂时还没有这样的功能

**Comment by wearwlnd** [comment]
> 那个是在没有src时把data-src赋给src，有src的时候就不起效果了；而且wxml里的data-src是用来点击预览用的；没有办法直接把src补充完整吗？

这倒是个办法 我去看一下编辑器 有没有办法把编辑器保存的图片路径变成绝对路径

**Comment by jin-yufeng** [comment]
不行的话我觉得暂时可以用正则替换上去😂(反正一定要有完整的地址才能显示)
html=html.replace(/src="\//g,"src=http://xxx.com/")

**Comment by wearwlnd** [comment]
> 不行的话我觉得暂时可以用正则替换上去😂(反正一定要有完整的地址才能显示)
> `html=html.replace(/src="\//g,'src="http://xxx.com/')`

也对哦 我怎么没想到 太感谢啦🙏
