### ISSUE TITLE
有支持Latex的计划吗

### ISSUE THREAD

**Issue by MakerGYT** [jin-yufeng/Parser#90]
**新功能描述**  
数学公式渲染

**Comment by jin-yufeng** [comment]
这个在前端实现比较困难，可以自行在后端转为图片，然后通过 `config.js` 里的 [onText](https://jin-yufeng.github.io/Parser/#/instructions?id=%e9%85%8d%e7%bd%ae%e9%a1%b9) 方法替换  
```javascript
// 仅做示例
onText(text, hasTag) {
  if(/\$.+?\$/.test(text)) {
    hasTag(); // 返回值中含有标签
    return text.replace(/\$(.+?)\$/, function($, $1){
      return `<img src="https://latex.codecogs.com/gif.latex?${encodeURI($1)}">`;
    })
  }
}
```

**Comment by MakerGYT** [comment]
好的，谢谢

**Comment by MakerGYT** [comment]
## 解决方案
在markdown解析html过程中，使用`markdown-it`和[markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img)，将其转化为图片，服务端渲染效果可控，从而让小程序端和网页可以统一显示。
![](https://static01.imgkr.com/temp/e57a651deabf4953b88ffb34c91e7363.jpg)
