### ISSUE TITLE
mpvue框架 @linkpress  e.mp.detail.ignore()还是会出现报错问题

### ISSUE THREAD

**Issue by tzwrick** [jin-yufeng/Parser#91]
**问题描述**  
mpvue框架 @linkpress 方法中调用了e.mp.detail.ignore()， 还是会出现跳转的报错

VM1065:1 Uncaught (in promise) thirdScriptError
{"errMsg":"navigateTo:fail page \"pages/culture/\" is not found"}
Object

**预期的表现**  
调用方法后不会出现报错问题

**实际的表现**  
调用方法后出现报错

**html代码**  

```html
 <parser :html="content" @linkpress="navigate" :tag-style="tagStyle"></parser>
```

```js
let { href } = e.mp.detail;
if(href == "xxx") {
   e.mp.detail.ignore();
}
```

**Comment by jin-yufeng** [comment]
提供一个 `demo` 项目？我这里没复现

**Comment by tzwrick** [comment]
我的问题，跳转没处理好
