### ISSUE TITLE
H5可以播放视频但是小程序不可以

### ISSUE THREAD

**Issue by yanZhangX** [jin-yufeng/Parser#93]
**问题描述**  
![image](https://user-images.githubusercontent.com/33448102/77141030-73589a00-6ab6-11ea-9788-e505ce2e9ae1.png)

**预期的表现**  
请描述预期的表现
视频正常播放
**实际的表现**  
请描述实际的表现
视频无法播放
**html代码**  
请附上出现问题的html代码（或附件），例如：
<view>
<videobinderror="__e"bindplay="__e"data-event-opts="play,play,$event,error,error,$event"data-from="video"data-source="https://ksv-video-publish.cdn.bcebos.com/bade757a915d3597012cc8a4646efceca702ec72.mp4?auth_key=1631176349-0-0-0e6e714d49aa5ad2e280d1e44954d1d5"id="video1"style="height:%;width:%">
00:0000:0000:00
</video>
</view>

**Comment by jin-yufeng** [comment]
提供视频链接

**Comment by jin-yufeng** [comment]
已修复
