### ISSUE TITLE
无法解析<svg>标签导致页面崩溃

### ISSUE THREAD

**Issue by liuhe37186** [jin-yufeng/Parser#94]
**问题描述**  
使用秀米模板编辑的资讯，无法解析导致小程序崩溃，无法进行任何操作

**预期的表现**  
能正常解析html代码

**实际的表现**  
页面空白，小程序崩溃

**html代码**  
请附上出现问题的html代码（或附件），例如：
[秀米模板.txt](https://github.com/jin-yufeng/Parser/files/4379980/default.txt)

**Comment by liuhe37186** [comment]
![WX20200325-173638](https://user-images.githubusercontent.com/12229493/77522454-3f6ae380-6ebf-11ea-9c01-15e6b4f46134.png)

**Comment by jin-yufeng** [comment]
确实死循环了，我检查一下原因

**Comment by liuhe37186** [comment]
![企业微信20200325180952](https://user-images.githubusercontent.com/12229493/77525413-f6695e00-6ec3-11ea-9eb0-d3b4f5c141ba.png)
我查找了一下秀米模板的源码，发现有个标签svg标签成了单标签，麻烦您看一下是不是这个原因导致的死循环

**Comment by jin-yufeng** [comment]
是这个问题，已修复

**Comment by liuhe37186** [comment]
经过验证已经解决，感谢！请问svg标签的图片有没有计划支持呢？

**Comment by liuhe37186** [comment]
刚刚又发现一个问题，还是有个svg标签错误，成了单标签，导致页面样式解析异常，将错误的svg标签去掉之后就恢复了正常，不知道作者有没有计划增加一些纠错的能力呢？

**Comment by jin-yufeng** [comment]
`svg` 标签图片应该已经可以用了吧？
`svg` 这个因为按照 `html` 标准，是不能 `<svg />` 结束的，所以会出一些问题，打算加一个能以 `xml` 方式解析的功能，使得这样的单标签 `svg` 也能正常结束和解析

**Comment by liuhe37186** [comment]
svg图片还是展示不了，同样的代码，在浏览器是可以展示出来的
<img width="324" alt="浏览器" src="https://user-images.githubusercontent.com/12229493/77614421-dd19ed80-6f67-11ea-874c-fa5648ad8b98.png">
<img width="289" alt="小程序" src="https://user-images.githubusercontent.com/12229493/77614423-df7c4780-6f67-11ea-96e0-02bb0bdad026.png">

svg：
<svg xmlns="http://www.w3.org/2000/svg" class="svg"
                                            style="vertical-align: middle; max-width: 100%; box-sizing: border-box;"
                                            viewBox="0 0 199.3 173.1" x="0px" y="0px" width="100%">
                                            <g style="box-sizing: border-box;">
                                                <path style="box-sizing: border-box;" fill="rgb(33, 147, 255)"
                                                    d="M 26 173.1 c -2.8 -2.4 -5.1 -4.9 -3.5 -8.9 c 1.5 -3.8 4.8 -4.1 8.3 -4.1 c 46.1 0 92.2 0 138.4 0 c 3.5 0 6.7 0.3 8.3 4.1 c 1.7 4 -0.7 6.6 -3.5 8.9 C 124.7 173.1 75.4 173.1 26 173.1 Z" />
                                                <path style="box-sizing: border-box;" fill="rgb(33, 147, 255)"
                                                    d="M 41.9 21.1 c 4.1 8.7 7.9 16.8 11.7 24.9 c 2.7 5.7 4.7 11.9 8.3 17.1 c 8.1 11.6 0.1 30.7 -11.9 38.1 c -20 12.3 -45.8 0.6 -49.6 -22.6 c -0.8 -5.2 0.3 -10.2 2.5 -15 C 9.6 49.3 16.5 35 23.3 20.8 c 0.6 -1.3 1.4 -2.7 1.7 -4.1 c 1.4 -6.9 2.1 -7.5 9.2 -7.5 c 15.5 0 31 0 46.5 0 c 2.7 0 4.4 -0.7 6.2 -2.9 c 6.7 -8.4 18.8 -8.2 25.5 0.2 c 1.7 2.1 3.4 2.7 5.9 2.7 c 15.3 -0.1 30.7 0.1 46 -0.1 c 5.6 -0.1 8.4 1.5 10.6 7.2 c 4.3 11.2 10 21.8 15.1 32.6 c 2.2 4.7 4.4 9.3 6.6 14 c 6.5 14.3 1.6 29.5 -12.1 37.6 c -19.9 11.7 -44.8 0.3 -49 -22.5 c -0.9 -4.9 0.2 -9.6 2.3 -14 c 6.1 -12.8 12.2 -25.5 18.3 -38.3 c 0.6 -1.3 1.7 -2.5 1.3 -4.5 c -13.1 0 -26.2 0 -39.3 0 c -1.8 0 -2.6 0.6 -3.3 2.2 c -1.2 2.8 -3 5.2 -5.7 6.8 c -1.8 1 -1.9 2.5 -1.9 4.2 c 0 34.7 0.1 69.3 -0.1 104 c 0 3.2 1.2 3.9 4.1 3.8 c 12.2 -0.1 24.3 -0.1 36.5 0 c 5.5 0 8.3 2.2 8.5 6.3 c 0.1 4.3 -2.9 6.7 -8.6 6.7 c -31.7 0 -63.3 0 -95 0 c -5.4 0 -8.3 -2.3 -8.4 -6.4 c 0 -4.1 2.9 -6.6 8.2 -6.6 c 12.3 0 24.7 -0.1 37 0.1 c 3.6 0.1 4.9 -0.6 4.9 -4.6 C 93.9 103.8 94 69.9 94 36.1 c 0 -0.5 0 -1 0 -1.5 c 0 -1.2 -0.1 -2.6 -1.4 -2.9 C 86.1 30.6 86.9 20.8 79 21 C 66.9 21.4 54.8 21.1 41.9 21.1 Z M 48.6 67.1 C 47.4 62.3 34.9 35.9 32 32.3 C 26.9 43 21.8 53.7 16.6 64.2 c -1.1 2.4 -0.1 2.9 2.1 2.9 C 28.6 67.1 38.6 67.1 48.6 67.1 Z M 167.5 31.4 C 162 42.8 157 53.2 151.9 63.6 c -1 2.1 -0.2 2.5 1.8 2.5 c 8.8 0 17.6 -0.1 26.4 0 c 3 0 3.4 -0.9 2.2 -3.5 C 177.5 52.6 172.8 42.6 167.5 31.4 Z M 149.4 79.2 c 3.5 9.3 11.1 13.8 20.7 12.9 c 7.2 -0.7 13.9 -6.3 15.1 -12.9 C 173.4 79.2 161.6 79.2 149.4 79.2 Z M 50.4 80.1 c -10.6 0 -21 0 -31.4 0 c -1.4 0 -3 -0.4 -4.3 0.4 c 2.5 7.9 9.4 12.7 18.1 12.7 C 41.1 93.1 48.1 88.1 50.4 80.1 Z" />
                                            </g>
                                        </svg>

**Comment by jin-yufeng** [comment]
确实，不过上面这个  `svg` 是可以的
![微信截图_20200326134848](https://user-images.githubusercontent.com/48236054/77614743-a55f7580-6f68-11ea-8054-7e6ee9670290.png)
我看看为啥

**Comment by jin-yufeng** [comment]
现在那几个 `svg` 应该可以了  
另外设置 `xml` 属性后像 `<svg />` 这种应该可以被正常解析

**Comment by liuhe37186** [comment]
其他的svg图片可以显示了，这个页面还是有点问题
<img width="292" alt="WX20200327-131916@2x" src="https://user-images.githubusercontent.com/12229493/77724314-9abae400-702d-11ea-9bb7-99422bfd1d8e.png">

[xiumi.txt](https://github.com/jin-yufeng/Parser/files/4391636/xiumi.txt)

**Comment by jin-yufeng** [comment]
加上 `xml` 属性就可以了  
```html
<parser html="{{html}}" xml />
```
![微信截图_20200327132008](https://user-images.githubusercontent.com/48236054/77726919-1750c100-7034-11ea-8f33-a2a696453874.png)

**Comment by liuhe37186** [comment]
可以了，感谢大佬支持！

**Comment by mgbq** [comment]
最新写法如何支持

**Comment by liuhe37186** [comment]
> 最新写法如何支持

我用的时候是直接增加了一个xml属性

**Comment by typing233** [comment]
我按照了mp-html插件，为什么还提示没有parser组件：<parser html="{{html}}" xml />
21:06:03.317 [Vue warn]: Failed to resolve component: parser
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
 at <Index__pageId=1__pagePath="pages/index/index"__pageQuery={} ...>
