### ISSUE TITLE
uni-app小程序开启lazy-load， 图片只加载第一张

### ISSUE THREAD

**Issue by q310550690** [jin-yufeng/Parser#95]
**问题描述**  
uni-app小程序开启lazy-load， 图片只加载第一张
![Snipaste_2020-03-26_14-44-06.jpg](https://i.loli.net/2020/03/26/7CeoudvQOYXLDZc.jpg)
![Snipaste_2020-03-26_14-44-46.jpg](https://i.loli.net/2020/03/26/dyEfUnRukNKgTS4.jpg)
**预期的表现**  
图片应该显示

**实际的表现**  
图片只显示第一张

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/14941585102806035.jpg"/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/32321585102649112.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/96951585102653409.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/93831585102656862.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/52221585102659909.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/36691585102663346.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/17291585102667159.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/25661585102676175.jpg" style=""/></p><p><img src="http://oa.yngfwy.com/js/umeditor/jsp/upload/20200325/77101585102686268.jpg" style=""/></p><p><br/></p>
```

**Comment by jin-yufeng** [comment]
看起来是懒加载没有监控到图片进入视图的问题  
但是我这样直接放在示例项目里是没问题的，你可以试试  
[demo.zip](https://github.com/jin-yufeng/Parser/files/4386139/demo.zip)
![微信截图_20200326165927](https://user-images.githubusercontent.com/48236054/77629411-6c34fe80-6f84-11ea-8a54-b2c76e451145.png)
懒加载是在这里处理的，可以调试一下  
![2](https://user-images.githubusercontent.com/48236054/77629438-7820c080-6f84-11ea-921d-4cf38d5dbae5.png)

**Comment by q310550690** [comment]
确实是没有进入视图
