### ISSUE TITLE
iframe标签能不能支持解析

### ISSUE THREAD

**Issue by liuhe37186** [jin-yufeng/Parser#96]
**新功能描述**  
描述需要的功能或改进建议
iframe标签能不能支持解析
**应用场景**  
描述该新功能的应用场景
编辑的资讯中嵌入腾讯视频的iframe，目前无法显示

**Comment by jin-yufeng** [comment]
小程序不太可能  
一个是 `iframe` 需要发起网络请求获取网页内容，而小程序中发起网络请求有限制  
最主要的是像腾讯视频这种 `iframe` 都是 `script` 脚本中动态加载的，而小程序中无法执行动态的 `js` （而且还涉及到 `dom`），所以不可行

**Comment by liuhe37186** [comment]
了解~

**Comment by XinJiangQingMang** [comment]
那文章里含腾讯视频 iframe 进来的 怎么处理呢  视频不显示

**Comment by jin-yufeng** [comment]
@XinJiangQingMang 
微信里可以用 [腾讯视频插件](https://developers.weixin.qq.com/community/develop/doc/000ece3c044210190ef61a4a954c09?highLine=%25E8%2585%25BE%25E8%25AE%25AF%25E8%25A7%2586%25E9%25A2%2591)  
然后自行添加到组件里：[添加自定义标签](https://jin-yufeng.github.io/Parser/#/instructions?id=%e6%b7%bb%e5%8a%a0%e4%b8%80%e4%b8%aa%e8%87%aa%e5%ae%9a%e4%b9%89%e6%a0%87%e7%ad%be)

**Comment by XinJiangQingMang** [comment]
app

**Comment by XinJiangQingMang** [comment]
我们编辑后台有时候需要直接iframe 腾讯视频   uniapp 里我看文档说的无法解析iframe   

> 不能正确显示一些网站的问题
很多网站的内容是在 js 脚本中动态加载的，这些内容在本插件解析中将被直接忽略（包括 iframe 视频）；本插件并不能替代 web-view 的功能，仅建议用于富文本编辑器编辑的富文本或简单的静态网页

**Comment by jin-yufeng** [comment]
`App` 上应该可以的，稍后我更新一下（`v3` 下可以直接用 `iframe` 标签）

**Comment by jin-yufeng** [comment]
@XinJiangQingMang 
去插件市场上重新下载一下，在 `App(v3)` 上应该可以用 `iframe` 了
