### ISSUE TITLE
html字符实体不会被解析

### ISSUE THREAD

**Issue by macanfa108** [jin-yufeng/Parser#97]
**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/15627064/77881494-b1617500-7291-11ea-8081-ba60a643efc7.png)
html字符实体不会解析，查看示例源码后，发现获取文本方法：getText （有处理实体字符）也并未被外界调用

**预期的表现**  
实体字符被正常解析

**实际的表现**  
未将html字符实体转换

**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
&lt;p style="line-height:1.5em;"&gt;示例文本&lt;/p&gt;
```

**Comment by jin-yufeng** [comment]
`&lt;` 被转为 `<` ，`&gt;` 被转为 `>`，有什么问题吗？
要使用标签应该直接使用 `<>`，而不是转为实体

**Comment by macanfa108** [comment]
后端接口返回的富文本格式是含有实体的，原本使用的是wxParse，可以转换为对应的排版格式。
再测试使用Parser，发现仅是转为text节点，并没有进一步转换为html格式

如同一段代码：&lt;p style="color:red;"&gt;示例文本&lt;/p&gt;

wxParse：实例文本  （红色）
Parser：<p style="color:red;">实例文本</p>

**Comment by macanfa108** [comment]
后端接口返回的富文本格式是含有实体的，原本使用的是wxParse，可以转换为对应的排版格式。
再测试使用Parser，发现仅是转为text节点，并没有进一步转换为html格式

如同一段代码：
`&lt;p style="color:red;"&gt;示例文本&lt;/p&gt;`

wxParse：示例文本 （红色）
Parser：
`<p style="color:red;">示例文本</p>`

**Comment by jin-yufeng** [comment]
你把 `&lt;p style="color:red;"&gt;示例文本&lt;/p&gt;` 放在浏览器里显示的也是 `<p style="color:red;">示例文本</p>`
`html` 的标准就是这样，使用实体本身就是为了让 `<>` 不被解析为标签

**Comment by macanfa108** [comment]
经排查，后端做了转义处理，去掉就可以了
非常感谢！
