### ISSUE TITLE
组件tapEvent事件不执行wx.navigateTo或者wx.redirectTo等方法

### ISSUE THREAD

**Issue by dingyu0810** [jin-yufeng/Parser#98]
**问题描述**  
请详细描述遇到的问题（可附图）
![image](https://user-images.githubusercontent.com/40651005/77887773-c47a4200-729d-11ea-8225-e3d682a32978.png)
![image](https://user-images.githubusercontent.com/40651005/77887812-d0660400-729d-11ea-91ab-77de764d3ba6.png)

**预期的表现**  
请描述预期的表现

**实际的表现**  
请描述实际的表现
但是可以执行wx.showToast这样的api
**html代码**  
请附上出现问题的html代码（或附件），例如：
```html
<div>Hello World!</div>
```

**Comment by jin-yufeng** [comment]
提供一个代码片段吧

**Comment by dingyu0810** [comment]
> 提供一个代码片段吧

不好意思 我这个好像是几个月前的版本了，我刚才下了新的  好像我发的这些都取消了
