### ISSUE TITLE
embed标签无法显示

### ISSUE THREAD

**Issue by liuhe37186** [jin-yufeng/Parser#99]
**问题描述**  
embed标签无法显示
**预期的表现**  
能正确解析embed标签，播放视频
**实际的表现**  
embed标签无法解析，视频不显示

**html代码**  
请附上出现问题的html代码（或附件），例如：

**Comment by jin-yufeng** [comment]
`embed` 目前不支持  
因为有时候不能从链接中判断出这个文件的类型（`embed` 可以用多种类型，有些类型可能还不支持），处理也比较麻烦  
如果用的 `embed` 都是视频，可以这样自定义处理一下  
1. 将 `embed` 从 `config.js` 的 `ignoreTags` 中移除  
2. 将 `config.js` 中的 `filter` 修改为  

    ```javascript
    filter(node, cxt) {
      if (node.name == 'embed') {
        node.name = 'video'; // 改名为 video
        node.attrs.id = 'video' + (++cxt.videoNum); // 内部需要，必须有不重复的 id
        node.attrs.source = [node.attrs.src]; // 内部需要
        node.attrs.controls = 'controls'; // 设置 controls
        cxt.bubble(); // 使其不被 rich-text 包含
      }
    },
    ```

**Comment by liuhe37186** [comment]
可以了，感谢~
